function [fitresult, gof] = create_fourier_series_4th_order(t_loc, y_loc)
%CREATEFIT(T_LOC,Y_LOC)
%  Create a fit.
%
%  Data for 'wb_fourier_series_4th_order' fit:
%      X Input : t_loc
%      Y Output: y_loc
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 21-May-2013 10:45:51


%% Fit: 'wb_fourier_series_4th_order'.
[xData, yData] = prepareCurveData( t_loc, y_loc );

% Set up fittype and options.
ft = fittype( 'a0 + a1*cos(2*pi()*x) + b1*sin(2*pi()*x)  + a2*cos(2*2*pi()*x) + b2*sin(2*2*pi()*x)  + a3*cos(3*2*pi()*x) + b3*sin(3*2*pi()*x)  + a4*cos(4*2*pi()*x) + b4*sin(4*2*pi()*x)', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( ft );
opts.Algorithm = 'Levenberg-Marquardt';
opts.Display = 'Off';
opts.Lower = [-Inf -Inf -Inf -Inf -Inf -Inf -Inf -Inf -Inf];
opts.StartPoint = [0.365816176838171 0.763504640848813 0.627896379614169 0.771980385554245 0.93285357027882 0.972740854003014 0.192028349427775 0.138874202829155 0.696266337082995];
opts.Upper = [Inf Inf Inf Inf Inf Inf Inf Inf Inf];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'wb_fourier_series_4th_order' );
plot( fitresult, xData, yData );
% Label axes
xlabel( 't_loc' );
ylabel( 'y_loc' );
grid on


