function [fitresult, gof, coeffs] = create_gaussian_fit(t,y,plotting)

%CREATEFIT Create plot of data sets and fits
%   CREATEFIT(t,y)
%   Creates a plot, similar to the plot in the main Curve Fitting Tool,
%   using the data that you provide as input.  You can
%   use this function with the same data you used with CFTOOL
%   or with different data.  You may want to edit the function to
%   customize the code and this help message.
%
%   Number of data sets:  1
%   Number of fits:  1

% Data from data set "response":
%     X = t:
%     Y = y:
%     Unweighted

% Auto-generated by MATLAB on 24-Oct-2013 09:53:06

% --- Create fit "fit 1"
fo_ = fitoptions('method','NonlinearLeastSquares','Lower',[-Inf -Inf    0]);
ok_ = isfinite(t) & isfinite(y);
if ~all( ok_ )
    warning( 'GenerateMFile:IgnoringNansAndInfs',...
        'Ignoring NaNs and Infs in data.' );
end
st_ = [1.1350764768976782104 -0.15277777777777828971 0.26304011640559404883 ];
set(fo_,'Startpoint',st_);
ft_ = fittype('gauss1');

% Fit this model using new data
[fitresult, gof] = fit(t(ok_),y(ok_),ft_,fo_);

if plotting == 1;
    % Plot fit with data.
    figure( 'Name', 'dFh_dir_resp' );
    plot( fitresult, t, y );
    % Label axes
    xlabel( 't' );
    ylabel( 'y' );
    grid on
end

coeffs = coeffvalues(fitresult);