function [fitresult, gof] = ParabolaFit_FixedConst(x, y, fixed_const)
%CREATEFIT(AMP_RATIO,FZ_NORM_CUT)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : x
%      Y Output: y
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 04-Mar-2015 08:50:09


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( x, y );

% Set up fittype and options.
ft = fittype( 'poly2' );
opts = fitoptions( ft );
opts.Lower = [-Inf -Inf fixed_const];
opts.Upper = [Inf Inf fixed_const];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% % Plot fit with data.
% figure( 'Name', 'untitled fit 1' );
% plot( fitresult, xData, yData );
% % Label axes
% xlabel( 'x' );
% ylabel( 'y' );
% grid on


