function [fitresult, gof] = createFit(t_per, dev)
%CREATEFIT(T_PER,DEV)
%  Create a fit.
%
%  Data for 'dev_steady_fourier_series_10th_order' fit:
%      X Input : t_per
%      Y Output: dev
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 20-May-2013 23:03:56


%% Fit: 'dev_steady_fourier_series_10th_order'.
[xData, yData] = prepareCurveData( t_per, dev );

% Set up fittype and options.
ft = fittype( 'a0 + a1*cos(x) + b1*sin(x)  + a2*cos(2*x) + b2*sin(2*x)  + a3*cos(3*x) + b3*sin(3*x)  + a4*cos(4*x) + b4*sin(4*x)  + a5*cos(5*x) + b5*sin(5*x)  + a6*cos(6*x) + b6*sin(6*x)  + a7*cos(7*x) + b7*sin(7*x)  + a8*cos(8*x) + b8*sin(8*x)  + a9*cos(9*x) + b9*sin(9*x)  + a10*cos(10*x) + b10*sin(10*x)', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( ft );
opts.Algorithm = 'Levenberg-Marquardt';
opts.Display = 'Off';
opts.Lower = [-Inf -Inf -Inf -Inf -Inf -Inf -Inf -Inf -Inf -Inf -Inf -Inf -Inf -Inf -Inf -Inf -Inf -Inf -Inf -Inf -Inf];
opts.StartPoint = [0.0503399867389541 0.228687584020221 0.834189061056899 0.015644692696527 0.863710865055866 0.0780690530324343 0.669042590081555 0.500211324281102 0.217993798750154 0.571615725404089 0.12218915092342 0.671166232988653 0.599585548122814 0.0559761573877905 0.0563430185433568 0.15250063700247 0.0196210667655841 0.435175545696952 0.832221475282818 0.617390171454084 0.520129415310742];
opts.Upper = [Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Create a figure for the plots.
figure( 'Name', 'dev_steady_fourier_series_10th_order' );

% Plot fit with data.
subplot( 2, 1, 1 );
plot( fitresult, xData, yData );
% Label axes
xlabel( 't_per' );
ylabel( 'dev' );
grid on

% Plot residuals.
subplot( 2, 1, 2 );
plot( fitresult, xData, yData, 'residuals' );
% Label axes
xlabel( 't_per' );
ylabel( 'dev' );
grid on


