% calc wb MOD CLIP d3rdMom

n_now=0;

%% variables

% bodyMODs
velMOD_d3rdMom = [];

slipMOD_d3rdMom = [];
pitchMOD_d3rdMom = [];
rollMOD_d3rdMom = [];

Fsp_pitchMOD_d3rdMom = [];
Fsp_rollMOD_d3rdMom = [];

% wbMOD
freqMOD_wb_d3rdMom = [];

strokeMOD_wb_L_d3rdMom_bins = [];
strokeMOD_wb_R_d3rdMom_bins = [];
strokeMOD_ds_L_d3rdMom_bins = [];
strokeMOD_ds_R_d3rdMom_bins = [];
strokeMOD_us_L_d3rdMom_bins = [];
strokeMOD_us_R_d3rdMom_bins = [];

pitchMOD_wb_L_d3rdMom_bins = [];
pitchMOD_wb_R_d3rdMom_bins = [];
pitchMOD_ds_L_d3rdMom_bins = [];
pitchMOD_ds_R_d3rdMom_bins = [];
pitchMOD_us_L_d3rdMom_bins = [];
pitchMOD_us_R_d3rdMom_bins = [];

devMOD_wb_L_d3rdMom_bins = [];
devMOD_wb_R_d3rdMom_bins = [];
devMOD_ds_L_d3rdMom_bins = [];
devMOD_ds_R_d3rdMom_bins = [];
devMOD_us_L_d3rdMom_bins = [];
devMOD_us_R_d3rdMom_bins = [];

DstrokeMOD_wb_d3rdMom_bins = [];
DstrokeMOD_ds_d3rdMom_bins = [];
DstrokeMOD_us_d3rdMom_bins = [];

DpitchMOD_wb_d3rdMom_bins = [];
DpitchMOD_ds_d3rdMom_bins = [];
DpitchMOD_us_d3rdMom_bins = [];

DdevMOD_wb_d3rdMom_bins = [];
DdevMOD_ds_d3rdMom_bins = [];
DdevMOD_us_d3rdMom_bins = [];

% seq&wb
seq_nr_d3rdMom = [];
wb_nr_d3rdMom = [];

% clip data
clip_side_d3rdMom = [];
clip_type_d3rdMom = [];

FirstMomentNormClipped_d3rdMom = [];
FirstMomentNormIntact_d3rdMom = [];
FirstMomentRatio_d3rdMom = [];

SecondMomentNormClipped_d3rdMom = [];
SecondMomentNormIntact_d3rdMom = [];
SecondMomentRatio_d3rdMom = [];

ThirdMomentNormClipped_d3rdMom = [];
ThirdMomentNormIntact_d3rdMom = [];
ThirdMomentRatio_d3rdMom = [];

AreaNormClipped_d3rdMom = [];
AreaNormIntact_d3rdMom = [];
AreaRatio_d3rdMom = [];

LengthClipped_pixels_d3rdMom = [];
LengthIntact_pixels_d3rdMom = [];
LengthRatio_d3rdMom = [];

% body kin
vel_d3rdMom = [];

slip_d3rdMom = [];
pitch_d3rdMom = [];
roll_d3rdMom = [];

Fsp_pitch_d3rdMom = [];
Fsp_roll_d3rdMom = [];

% wingbeat kin
dt_wb_d3rdMom = [];
dt_ds_d3rdMom = [];
dt_us_d3rdMom = [];
f_wb_d3rdMom = [];
Rds_d3rdMom = [];

t_wb_L_d3rdMom = [];
t_wb_R_d3rdMom = [];
stroke_wb_L_d3rdMom = [];
stroke_wb_R_d3rdMom = [];
pitch_wb_L_d3rdMom = [];
pitch_wb_R_d3rdMom = [];
dev_wb_L_d3rdMom = [];
dev_wb_R_d3rdMom = [];
aoa_wb_L_d3rdMom = [];
aoa_wb_R_d3rdMom = [];
U_wb_L_d3rdMom = [];
U_wb_R_d3rdMom = [];
Dstroke_wb_d3rdMom = [];
Dpitch_wb_d3rdMom = [];
Ddev_wb_d3rdMom = [];
Daoa_wb_d3rdMom = [];
DU_wb_d3rdMom = [];

t_ds_L_d3rdMom = [];
t_ds_R_d3rdMom = [];
stroke_ds_L_d3rdMom = [];
stroke_ds_R_d3rdMom = [];
pitch_ds_L_d3rdMom = [];
pitch_ds_R_d3rdMom = [];
dev_ds_L_d3rdMom = [];
dev_ds_R_d3rdMom = [];
aoa_ds_L_d3rdMom = [];
aoa_ds_R_d3rdMom = [];
U_ds_L_d3rdMom = [];
U_ds_R_d3rdMom = [];
Dstroke_ds_d3rdMom = [];
Dpitch_ds_d3rdMom = [];
Ddev_ds_d3rdMom = [];
Daoa_ds_d3rdMom = [];
DU_ds_d3rdMom = [];

t_us_L_d3rdMom = [];
t_us_R_d3rdMom = [];
stroke_us_L_d3rdMom = [];
stroke_us_R_d3rdMom = [];
pitch_us_L_d3rdMom = [];
pitch_us_R_d3rdMom = [];
dev_us_L_d3rdMom = [];
dev_us_R_d3rdMom = [];
aoa_us_L_d3rdMom = [];
aoa_us_R_d3rdMom = [];
U_us_L_d3rdMom = [];
U_us_R_d3rdMom = [];
Dstroke_us_d3rdMom = [];
Dpitch_us_d3rdMom = [];
Ddev_us_d3rdMom = [];
Daoa_us_d3rdMom = [];
DU_us_d3rdMom = [];

t_wb_d3rdMom_bins = [];
stroke_wb_L_d3rdMom_bins = [];
stroke_wb_R_d3rdMom_bins = [];
pitch_wb_L_d3rdMom_bins = [];
pitch_wb_R_d3rdMom_bins = [];
dev_wb_L_d3rdMom_bins = [];
dev_wb_R_d3rdMom_bins = [];
aoa_wb_L_d3rdMom_bins = [];
aoa_wb_R_d3rdMom_bins = [];
U_wb_L_d3rdMom_bins = [];
U_wb_R_d3rdMom_bins = [];
Dstroke_wb_d3rdMom_bins = [];
Dpitch_wb_d3rdMom_bins = [];
Ddev_wb_d3rdMom_bins = [];
Daoa_wb_d3rdMom_bins = [];
DU_wb_d3rdMom_bins = [];

t_ds_d3rdMom_bins = [];
stroke_ds_L_d3rdMom_bins = [];
stroke_ds_R_d3rdMom_bins = [];
pitch_ds_L_d3rdMom_bins = [];
pitch_ds_R_d3rdMom_bins = [];
dev_ds_L_d3rdMom_bins = [];
dev_ds_R_d3rdMom_bins = [];
aoa_ds_L_d3rdMom_bins = [];
aoa_ds_R_d3rdMom_bins = [];
U_ds_L_d3rdMom_bins = [];
U_ds_R_d3rdMom_bins = [];
Dstroke_ds_d3rdMom_bins = [];
Dpitch_ds_d3rdMom_bins = [];
Ddev_ds_d3rdMom_bins = [];
Daoa_ds_d3rdMom_bins = [];
DU_ds_d3rdMom_bins = [];

t_us_d3rdMom_bins = [];
stroke_us_L_d3rdMom_bins = [];
stroke_us_R_d3rdMom_bins = [];
pitch_us_L_d3rdMom_bins = [];
pitch_us_R_d3rdMom_bins = [];
dev_us_L_d3rdMom_bins = [];
dev_us_R_d3rdMom_bins = [];
aoa_us_L_d3rdMom_bins = [];
aoa_us_R_d3rdMom_bins = [];
U_us_L_d3rdMom_bins = [];
U_us_R_d3rdMom_bins = [];
Dstroke_us_d3rdMom_bins = [];
Dpitch_us_d3rdMom_bins = [];
Ddev_us_d3rdMom_bins = [];
Daoa_us_d3rdMom_bins = [];
DU_us_d3rdMom_bins = [];

for wb = 1:size(wb_nr,1)
    counter = size(wb_nr,1) -wb
        
        if steady_nr_mean_wb(wb) == 1 && ThirdMomentRatio(wb) < ThirdMomentRatio_cut
            
            % current wb
            seq_nr_now = seq_nr(wb);
            wb_nr_now = wb_nr(wb);
            
            % clip data
            clip_side_now = clip_side(wb);
            clip_type_now = clip_type(wb);

            FirstMomentNormClipped_now = FirstMomentNormClipped(wb);
            FirstMomentNormIntact_now = FirstMomentNormIntact(wb);
            FirstMomentRatio_now = FirstMomentRatio(wb);

            SecondMomentNormClipped_now = SecondMomentNormClipped(wb);
            SecondMomentNormIntact_now = SecondMomentNormIntact(wb);
            SecondMomentRatio_now = SecondMomentRatio(wb);

            ThirdMomentNormClipped_now = ThirdMomentNormClipped(wb);
            ThirdMomentNormIntact_now = ThirdMomentNormIntact(wb);
            ThirdMomentRatio_now = ThirdMomentRatio(wb);

            AreaNormClipped_now = AreaNormClipped(wb);
            AreaNormIntact_now = AreaNormIntact(wb);
            AreaRatio_now = AreaRatio(wb);

            LengthClipped_pixels_now = LengthClipped_pixels(wb);
            LengthIntact_pixels_now = LengthIntact_pixels(wb);
            LengthRatio_now = LengthRatio(wb);

            % body kin
            vel_now = V_mean_wb(wb);
            
            slip_now = slip_mean_wb(wb);
            pitch_now = pitch_mean_wb(wb);
            roll_now = roll_mean_wb(wb);
            
            Fsp_pitch_now = Fsp_pitch_mean_wb(wb);
            Fsp_roll_now = Fsp_roll_mean_wb(wb);
            
            % wingbeat kin
            dt_ds_now = ([dt_ds_L(wb),dt_ds_R(wb)]);
            dt_us_now = ([dt_us_L(wb),dt_us_R(wb)]);
            f_wb_now = ([f_wb_L(wb),f_wb_R(wb)]);
            Rds_now = dt_ds_now ./ (dt_ds_now + dt_us_now);
            
            stroke_wb_L_now = stroke_wb_L(:,wb);
            stroke_wb_R_now = stroke_wb_R(:,wb);
            stroke_ds_L_now = stroke_ds_L(:,wb);
            stroke_ds_R_now = stroke_ds_R(:,wb);
            stroke_us_L_now = stroke_us_L(:,wb);
            stroke_us_R_now = stroke_us_R(:,wb);
            
            pitch_wb_L_now = pitch_wb_L(:,wb);
            pitch_wb_R_now = pitch_wb_R(:,wb);
            pitch_ds_L_now = pitch_ds_L(:,wb);
            pitch_ds_R_now = pitch_ds_R(:,wb);
            pitch_us_L_now = pitch_us_L(:,wb);
            pitch_us_R_now = pitch_us_R(:,wb);
            
            dev_wb_L_now = dev_wb_L(:,wb);
            dev_wb_R_now = dev_wb_R(:,wb);
            dev_ds_L_now = dev_ds_L(:,wb);
            dev_ds_R_now = dev_ds_R(:,wb);
            dev_us_L_now = dev_us_L(:,wb);
            dev_us_R_now = dev_us_R(:,wb);
            
            U_wb_L_now = U_wb_L(:,wb);
            U_wb_R_now = U_wb_R(:,wb);
            U_ds_L_now = U_ds_L(:,wb);
            U_ds_R_now = U_ds_R(:,wb);
            U_us_L_now = U_us_L(:,wb);
            U_us_R_now = U_us_R(:,wb);
            
            aoa_wb_L_now = aoa_wb_L(:,wb);
            aoa_wb_R_now = aoa_wb_R(:,wb);
            aoa_ds_L_now = aoa_ds_L(:,wb);
            aoa_ds_R_now = aoa_ds_R(:,wb);
            aoa_us_L_now = aoa_us_L(:,wb);
            aoa_us_R_now = aoa_us_R(:,wb);
            
            t_wb_L_now = t_wb_L(:,wb);
            t_wb_R_now = t_wb_R(:,wb);
            t_ds_L_now = t_ds_L(:,wb);
            t_ds_R_now = t_ds_R(:,wb);
            t_us_L_now = t_us_L(:,wb);
            t_us_R_now = t_us_R(:,wb);

            % interpolated data
            stroke_wb_L_interp = stroke_wb_L_bins(:,wb);
            stroke_wb_R_interp = stroke_wb_R_bins(:,wb);
            stroke_ds_L_interp = stroke_ds_L_bins(:,wb);
            stroke_ds_R_interp = stroke_ds_R_bins(:,wb);
            stroke_us_L_interp = stroke_us_L_bins(:,wb);
            stroke_us_R_interp = stroke_us_R_bins(:,wb);
            
            pitch_wb_L_interp = pitch_wb_L_bins(:,wb);
            pitch_wb_R_interp = pitch_wb_R_bins(:,wb);
            pitch_ds_L_interp = pitch_ds_L_bins(:,wb);
            pitch_ds_R_interp = pitch_ds_R_bins(:,wb);
            pitch_us_L_interp = pitch_us_L_bins(:,wb);
            pitch_us_R_interp = pitch_us_R_bins(:,wb);
            
            dev_wb_L_interp = dev_wb_L_bins(:,wb);
            dev_wb_R_interp = dev_wb_R_bins(:,wb);
            dev_ds_L_interp = dev_ds_L_bins(:,wb);
            dev_ds_R_interp = dev_ds_R_bins(:,wb);
            dev_us_L_interp = dev_us_L_bins(:,wb);
            dev_us_R_interp = dev_us_R_bins(:,wb);
            
            U_wb_L_interp = U_wb_L_bins(:,wb);
            U_wb_R_interp = U_wb_R_bins(:,wb);
            U_ds_L_interp = U_ds_L_bins(:,wb);
            U_ds_R_interp = U_ds_R_bins(:,wb);
            U_us_L_interp = U_us_L_bins(:,wb);
            U_us_R_interp = U_us_R_bins(:,wb);
            
            aoa_wb_L_interp = aoa_wb_L_bins(:,wb);
            aoa_wb_R_interp = aoa_wb_R_bins(:,wb);
            aoa_ds_L_interp = aoa_ds_L_bins(:,wb);
            aoa_ds_R_interp = aoa_ds_R_bins(:,wb);
            aoa_us_L_interp = aoa_us_L_bins(:,wb);
            aoa_us_R_interp = aoa_us_R_bins(:,wb);

            Dstroke_wb_interp = Dstroke_wb_bins(:,wb);
            Dstroke_ds_interp = Dstroke_ds_bins(:,wb);
            Dstroke_us_interp = Dstroke_us_bins(:,wb);
            
            Dpitch_wb_interp = Dpitch_wb_bins(:,wb);
            Dpitch_ds_interp = Dpitch_ds_bins(:,wb);
            Dpitch_us_interp = Dpitch_us_bins(:,wb);
            
            Ddev_wb_interp = Ddev_wb_bins(:,wb);
            Ddev_ds_interp = Ddev_ds_bins(:,wb);
            Ddev_us_interp = Ddev_us_bins(:,wb);
            
            DU_wb_interp = DU_wb_bins(:,wb);
            DU_ds_interp = DU_ds_bins(:,wb);
            DU_us_interp = DU_us_bins(:,wb);
            
            Daoa_wb_interp = Daoa_wb_bins(:,wb);
            Daoa_ds_interp = Daoa_ds_bins(:,wb);
            Daoa_us_interp = Daoa_us_bins(:,wb);
            
            
            %% calc bodykin modifications
            velMOD_now   = (nanmean(vel_now) - vel_steady)          / (ThirdMomentRatio_now-1);

            slipMOD_now  =  nanmean(slip_now)                       / (ThirdMomentRatio_now-1);
            pitchMOD_now = (nanmean(pitch_now) - pitch_body_steady) / (ThirdMomentRatio_now-1);
            rollMOD_now  =  nanmean(roll_now)                       / (ThirdMomentRatio_now-1);

            Fsp_pitchMOD_now = nanmean(Fsp_pitch_now)               / (ThirdMomentRatio_now-1);
            Fsp_rollMOD_now  = nanmean(Fsp_roll_now)                / (ThirdMomentRatio_now-1);

            %% calc wingbeat modifications
            freqMOD_wb_now =     (nanmean(f_wb_now)  - f_wb_steady)      / (ThirdMomentRatio_now-1);
            
            strokeMOD_wb_L_now = (stroke_wb_L_interp - stroke_wb_steady) / (ThirdMomentRatio_now-1);
            strokeMOD_wb_R_now = (stroke_wb_R_interp - stroke_wb_steady) / (ThirdMomentRatio_now-1);
            strokeMOD_ds_L_now = (stroke_ds_L_interp - stroke_ds_steady) / (ThirdMomentRatio_now-1);
            strokeMOD_ds_R_now = (stroke_ds_R_interp - stroke_ds_steady) / (ThirdMomentRatio_now-1);
            strokeMOD_us_L_now = (stroke_us_L_interp - stroke_us_steady) / (ThirdMomentRatio_now-1);
            strokeMOD_us_R_now = (stroke_us_R_interp - stroke_us_steady) / (ThirdMomentRatio_now-1);
            
            pitchMOD_wb_L_now = (pitch_wb_L_interp - pitch_wb_steady) / (ThirdMomentRatio_now-1);
            pitchMOD_wb_R_now = (pitch_wb_R_interp - pitch_wb_steady) / (ThirdMomentRatio_now-1);
            pitchMOD_ds_L_now = (pitch_ds_L_interp - pitch_ds_steady) / (ThirdMomentRatio_now-1);
            pitchMOD_ds_R_now = (pitch_ds_R_interp - pitch_ds_steady) / (ThirdMomentRatio_now-1);
            pitchMOD_us_L_now = (pitch_us_L_interp - pitch_us_steady) / (ThirdMomentRatio_now-1);
            pitchMOD_us_R_now = (pitch_us_R_interp - pitch_us_steady) / (ThirdMomentRatio_now-1);
            
            devMOD_wb_L_now = (dev_wb_L_interp - dev_wb_steady) / (ThirdMomentRatio_now-1);
            devMOD_wb_R_now = (dev_wb_R_interp - dev_wb_steady) / (ThirdMomentRatio_now-1);
            devMOD_ds_L_now = (dev_ds_L_interp - dev_ds_steady) / (ThirdMomentRatio_now-1);
            devMOD_ds_R_now = (dev_ds_R_interp - dev_ds_steady) / (ThirdMomentRatio_now-1);
            devMOD_us_L_now = (dev_us_L_interp - dev_us_steady) / (ThirdMomentRatio_now-1);
            devMOD_us_R_now = (dev_us_R_interp - dev_us_steady) / (ThirdMomentRatio_now-1);
            
            DstrokeMOD_wb_now = Dstroke_wb_interp / (ThirdMomentRatio_now-1);
            DstrokeMOD_ds_now = Dstroke_ds_interp / (ThirdMomentRatio_now-1);
            DstrokeMOD_us_now = Dstroke_us_interp / (ThirdMomentRatio_now-1);

            DpitchMOD_wb_now = Dpitch_wb_interp / (ThirdMomentRatio_now-1);
            DpitchMOD_ds_now = Dpitch_ds_interp / (ThirdMomentRatio_now-1);
            DpitchMOD_us_now = Dpitch_us_interp / (ThirdMomentRatio_now-1);

            DdevMOD_wb_now = Ddev_wb_interp / (ThirdMomentRatio_now-1);
            DdevMOD_ds_now = Ddev_ds_interp / (ThirdMomentRatio_now-1);
            DdevMOD_us_now = Ddev_us_interp / (ThirdMomentRatio_now-1);
            
            %% store data
            n_now=n_now+1;

            seq_nr_d3rdMom(n_now,1) = seq_nr_now;
            wb_nr_d3rdMom(n_now,1) = wb_nr_now;

            % clip data
            clip_side_d3rdMom(n_now,1) = clip_side_now;
            clip_type_d3rdMom(n_now,1) = clip_type_now;

            FirstMomentNormClipped_d3rdMom(n_now,1) = FirstMomentNormClipped_now;
            FirstMomentNormIntact_d3rdMom(n_now,1) = FirstMomentNormIntact_now;
            FirstMomentRatio_d3rdMom(n_now,1) = FirstMomentRatio_now;

            SecondMomentNormClipped_d3rdMom(n_now,1) = SecondMomentNormClipped_now;
            SecondMomentNormIntact_d3rdMom(n_now,1) = SecondMomentNormIntact_now;
            SecondMomentRatio_d3rdMom(n_now,1) = SecondMomentRatio_now;

            ThirdMomentNormClipped_d3rdMom(n_now,1) = ThirdMomentNormClipped_now;
            ThirdMomentNormIntact_d3rdMom(n_now,1) = ThirdMomentNormIntact_now;
            ThirdMomentRatio_d3rdMom(n_now,1) = ThirdMomentRatio_now;

            AreaNormClipped_d3rdMom(n_now,1) = AreaNormClipped_now;
            AreaNormIntact_d3rdMom(n_now,1) = AreaNormIntact_now;
            AreaRatio_d3rdMom(n_now,1) = AreaRatio_now;

            LengthClipped_pixels_d3rdMom(n_now,1) = LengthClipped_pixels_now;
            LengthIntact_pixels_d3rdMom(n_now,1) = LengthIntact_pixels_now;
            LengthRatio_d3rdMom(n_now,1) = LengthRatio_now;

            % body kin
            vel_d3rdMom(n_now,1) = vel_now;

            slip_d3rdMom(n_now,1) = slip_now;
            pitch_d3rdMom(n_now,1) = pitch_now;
            roll_d3rdMom(n_now,1) = roll_now;

            Fsp_pitch_d3rdMom(n_now,1) = Fsp_pitch_now;
            Fsp_roll_d3rdMom(n_now,1) = Fsp_roll_now;

            % wingbeat kin
            dt_ds_d3rdMom(n_now,1) = nanmean(dt_ds_now);
            dt_us_d3rdMom(n_now,1) = nanmean(dt_us_now);
            f_wb_d3rdMom(n_now,1) = nanmean(f_wb_now);
            Rds_d3rdMom(n_now,1) = nanmean(Rds_now);

            t_wb_L_d3rdMom(1:length(t_wb_L_now),n_now) = t_wb_L_now;
            t_wb_R_d3rdMom(1:length(t_wb_R_now),n_now) = t_wb_R_now;
            stroke_wb_L_d3rdMom(1:length(t_wb_L_now),n_now) = stroke_wb_L_now;
            stroke_wb_R_d3rdMom(1:length(t_wb_R_now),n_now) = stroke_wb_R_now;
            pitch_wb_L_d3rdMom(1:length(t_wb_L_now),n_now) = pitch_wb_L_now;
            pitch_wb_R_d3rdMom(1:length(t_wb_R_now),n_now) = pitch_wb_R_now;
            dev_wb_L_d3rdMom(1:length(t_wb_L_now),n_now) = dev_wb_L_now;
            dev_wb_R_d3rdMom(1:length(t_wb_R_now),n_now) = dev_wb_R_now;
            aoa_wb_L_d3rdMom(1:length(t_wb_L_now),n_now) = aoa_wb_L_now;
            aoa_wb_R_d3rdMom(1:length(t_wb_R_now),n_now) = aoa_wb_R_now;
            U_wb_L_d3rdMom(1:length(t_wb_L_now),n_now) = U_wb_L_now;
            U_wb_R_d3rdMom(1:length(t_wb_R_now),n_now) = U_wb_R_now;
            
            t_ds_L_d3rdMom(1:length(t_ds_L_now),n_now) = t_ds_L_now;
            t_ds_R_d3rdMom(1:length(t_ds_R_now),n_now) = t_ds_R_now;
            stroke_ds_L_d3rdMom(1:length(t_ds_L_now),n_now) = stroke_ds_L_now;
            stroke_ds_R_d3rdMom(1:length(t_ds_R_now),n_now) = stroke_ds_R_now;
            pitch_ds_L_d3rdMom(1:length(t_ds_L_now),n_now) = pitch_ds_L_now;
            pitch_ds_R_d3rdMom(1:length(t_ds_R_now),n_now) = pitch_ds_R_now;
            dev_ds_L_d3rdMom(1:length(t_ds_L_now),n_now) = dev_ds_L_now;
            dev_ds_R_d3rdMom(1:length(t_ds_R_now),n_now) = dev_ds_R_now;
            aoa_ds_L_d3rdMom(1:length(t_ds_L_now),n_now) = aoa_ds_L_now;
            aoa_ds_R_d3rdMom(1:length(t_ds_R_now),n_now) = aoa_ds_R_now;
            U_ds_L_d3rdMom(1:length(t_ds_L_now),n_now) = U_ds_L_now;
            U_ds_R_d3rdMom(1:length(t_ds_R_now),n_now) = U_ds_R_now;
            
            t_us_L_d3rdMom(1:length(t_us_L_now),n_now) = t_us_L_now;
            t_us_R_d3rdMom(1:length(t_us_R_now),n_now) = t_us_R_now;
            stroke_us_L_d3rdMom(1:length(t_us_L_now),n_now) = stroke_us_L_now;
            stroke_us_R_d3rdMom(1:length(t_us_R_now),n_now) = stroke_us_R_now;
            pitch_us_L_d3rdMom(1:length(t_us_L_now),n_now) = pitch_us_L_now;
            pitch_us_R_d3rdMom(1:length(t_us_R_now),n_now) = pitch_us_R_now;
            dev_us_L_d3rdMom(1:length(t_us_L_now),n_now) = dev_us_L_now;
            dev_us_R_d3rdMom(1:length(t_us_R_now),n_now) = dev_us_R_now;
            aoa_us_L_d3rdMom(1:length(t_us_L_now),n_now) = aoa_us_L_now;
            aoa_us_R_d3rdMom(1:length(t_us_R_now),n_now) = aoa_us_R_now;
            U_us_L_d3rdMom(1:length(t_us_L_now),n_now) = U_us_L_now;
            U_us_R_d3rdMom(1:length(t_us_R_now),n_now) = U_us_R_now;
            
            % store interp binned data separate rows
            t_wb_d3rdMom_bins(:,n_now) = t_wb_bin;
            stroke_wb_L_d3rdMom_bins(:,n_now) = stroke_wb_L_interp;
            stroke_wb_R_d3rdMom_bins(:,n_now) = stroke_wb_R_interp;
            pitch_wb_L_d3rdMom_bins(:,n_now) = pitch_wb_L_interp;
            pitch_wb_R_d3rdMom_bins(:,n_now) = pitch_wb_R_interp;
            dev_wb_L_d3rdMom_bins(:,n_now) = dev_wb_L_interp;
            dev_wb_R_d3rdMom_bins(:,n_now) = dev_wb_R_interp;
            aoa_wb_L_d3rdMom_bins(:,n_now) = aoa_wb_L_interp;
            aoa_wb_R_d3rdMom_bins(:,n_now) = aoa_wb_R_interp;
            U_wb_L_d3rdMom_bins(:,n_now) = U_wb_L_interp;
            U_wb_R_d3rdMom_bins(:,n_now) = U_wb_R_interp;
            Dstroke_wb_d3rdMom_bins(:,n_now) = Dstroke_wb_interp;
            Dpitch_wb_d3rdMom_bins(:,n_now) = Dpitch_wb_interp;
            Ddev_wb_d3rdMom_bins(:,n_now) = Ddev_wb_interp;
            Daoa_wb_d3rdMom_bins(:,n_now) = Daoa_wb_interp;
            DU_wb_d3rdMom_bins(:,n_now) = DU_wb_interp;
            
            t_ds_d3rdMom_bins(:,n_now) = t_ds_bin;
            stroke_ds_L_d3rdMom_bins(:,n_now) = stroke_ds_L_interp;
            stroke_ds_R_d3rdMom_bins(:,n_now) = stroke_ds_R_interp;
            pitch_ds_L_d3rdMom_bins(:,n_now) = pitch_ds_L_interp;
            pitch_ds_R_d3rdMom_bins(:,n_now) = pitch_ds_R_interp;
            dev_ds_L_d3rdMom_bins(:,n_now) = dev_ds_L_interp;
            dev_ds_R_d3rdMom_bins(:,n_now) = dev_ds_R_interp;
            aoa_ds_L_d3rdMom_bins(:,n_now) = aoa_ds_L_interp;
            aoa_ds_R_d3rdMom_bins(:,n_now) = aoa_ds_R_interp;
            U_ds_L_d3rdMom_bins(:,n_now) = U_ds_L_interp;
            U_ds_R_d3rdMom_bins(:,n_now) = U_ds_R_interp;
            Dstroke_ds_d3rdMom_bins(:,n_now) = Dstroke_ds_interp;
            Dpitch_ds_d3rdMom_bins(:,n_now) = Dpitch_ds_interp;
            Ddev_ds_d3rdMom_bins(:,n_now) = Ddev_ds_interp;
            Daoa_ds_d3rdMom_bins(:,n_now) = Daoa_ds_interp;
            DU_ds_d3rdMom_bins(:,n_now) = DU_ds_interp;
            
            t_us_d3rdMom_bins(:,n_now) = t_us_bin;
            stroke_us_L_d3rdMom_bins(:,n_now) = stroke_us_L_interp;
            stroke_us_R_d3rdMom_bins(:,n_now) = stroke_us_R_interp;
            pitch_us_L_d3rdMom_bins(:,n_now) = pitch_us_L_interp;
            pitch_us_R_d3rdMom_bins(:,n_now) = pitch_us_R_interp;
            dev_us_L_d3rdMom_bins(:,n_now) = dev_us_L_interp;
            dev_us_R_d3rdMom_bins(:,n_now) = dev_us_R_interp;
            aoa_us_L_d3rdMom_bins(:,n_now) = aoa_us_L_interp;
            aoa_us_R_d3rdMom_bins(:,n_now) = aoa_us_R_interp;
            U_us_L_d3rdMom_bins(:,n_now) = U_us_L_interp;
            U_us_R_d3rdMom_bins(:,n_now) = U_us_R_interp;
            Dstroke_us_d3rdMom_bins(:,n_now) = Dstroke_us_interp;
            Dpitch_us_d3rdMom_bins(:,n_now) = Dpitch_us_interp;
            Ddev_us_d3rdMom_bins(:,n_now) = Ddev_us_interp;
            Daoa_us_d3rdMom_bins(:,n_now) = Daoa_us_interp;
            DU_us_d3rdMom_bins(:,n_now) = DU_us_interp;
            
            %% store MOD data
            
            %  bodykin modifications
            velMOD_d3rdMom(n_now,1) = velMOD_now;
            
            slipMOD_d3rdMom(n_now,1) = slipMOD_now;
            pitchMOD_d3rdMom(n_now,1) = pitchMOD_now;
            rollMOD_d3rdMom(n_now,1) = rollMOD_now;

            Fsp_pitchMOD_d3rdMom(n_now,1) = Fsp_pitchMOD_now;
            Fsp_rollMOD_d3rdMom(n_now,1) = Fsp_rollMOD_now;

            %  WB modifications
            freqMOD_wb_d3rdMom(n_now,1) = freqMOD_wb_now;
            
            strokeMOD_wb_L_d3rdMom_bins(:,n_now) = strokeMOD_wb_L_now;
            strokeMOD_wb_R_d3rdMom_bins(:,n_now) = strokeMOD_wb_R_now;
            strokeMOD_ds_L_d3rdMom_bins(:,n_now) = strokeMOD_ds_L_now;
            strokeMOD_ds_R_d3rdMom_bins(:,n_now) = strokeMOD_ds_R_now;
            strokeMOD_us_L_d3rdMom_bins(:,n_now) = strokeMOD_us_L_now;
            strokeMOD_us_R_d3rdMom_bins(:,n_now) = strokeMOD_us_R_now;

            pitchMOD_wb_L_d3rdMom_bins(:,n_now) = pitchMOD_wb_L_now;
            pitchMOD_wb_R_d3rdMom_bins(:,n_now) = pitchMOD_wb_R_now;
            pitchMOD_ds_L_d3rdMom_bins(:,n_now) = pitchMOD_ds_L_now;
            pitchMOD_ds_R_d3rdMom_bins(:,n_now) = pitchMOD_ds_R_now;
            pitchMOD_us_L_d3rdMom_bins(:,n_now) = pitchMOD_us_L_now;
            pitchMOD_us_R_d3rdMom_bins(:,n_now) = pitchMOD_us_R_now;

            devMOD_wb_L_d3rdMom_bins(:,n_now) = devMOD_wb_L_now;
            devMOD_wb_R_d3rdMom_bins(:,n_now) = devMOD_wb_R_now;
            devMOD_ds_L_d3rdMom_bins(:,n_now) = devMOD_ds_L_now;
            devMOD_ds_R_d3rdMom_bins(:,n_now) = devMOD_ds_R_now;
            devMOD_us_L_d3rdMom_bins(:,n_now) = devMOD_us_L_now;
            devMOD_us_R_d3rdMom_bins(:,n_now) = devMOD_us_R_now;

            DstrokeMOD_wb_d3rdMom_bins(:,n_now) = DstrokeMOD_wb_now;
            DstrokeMOD_ds_d3rdMom_bins(:,n_now) = DstrokeMOD_ds_now;
            DstrokeMOD_us_d3rdMom_bins(:,n_now) = DstrokeMOD_us_now;

            DpitchMOD_wb_d3rdMom_bins(:,n_now) = DpitchMOD_wb_now;
            DpitchMOD_ds_d3rdMom_bins(:,n_now) = DpitchMOD_ds_now;
            DpitchMOD_us_d3rdMom_bins(:,n_now) = DpitchMOD_us_now;

            DdevMOD_wb_d3rdMom_bins(:,n_now) = DdevMOD_wb_now;
            DdevMOD_ds_d3rdMom_bins(:,n_now) = DdevMOD_ds_now;
            DdevMOD_us_d3rdMom_bins(:,n_now) = DdevMOD_us_now;
        end
end

%% mean & 95%CI
% body kin
vel_d3rdMom_meanCIstd = [nanmean(vel_d3rdMom) 1.96*nanstd(vel_d3rdMom)/sqrt(length(vel_d3rdMom)) nanstd(vel_d3rdMom)];

slip_d3rdMom_meanCIstd = [nanmean(slip_d3rdMom) 1.96*nanstd(slip_d3rdMom)/sqrt(length(slip_d3rdMom)) nanstd(slip_d3rdMom)];
pitch_d3rdMom_meanCIstd = [nanmean(pitch_d3rdMom) 1.96*nanstd(pitch_d3rdMom)/sqrt(length(pitch_d3rdMom)) nanstd(pitch_d3rdMom)];
roll_d3rdMom_meanCIstd = [nanmean(roll_d3rdMom) 1.96*nanstd(roll_d3rdMom)/sqrt(length(roll_d3rdMom)) nanstd(roll_d3rdMom)];

Fsp_pitch_d3rdMom_meanCIstd = [nanmean(Fsp_pitch_d3rdMom) 1.96*nanstd(Fsp_pitch_d3rdMom)/sqrt(length(Fsp_pitch_d3rdMom)) nanstd(Fsp_pitch_d3rdMom)];
Fsp_roll_d3rdMom_meanCIstd = [nanmean(Fsp_roll_d3rdMom) 1.96*nanstd(Fsp_roll_d3rdMom)/sqrt(length(Fsp_roll_d3rdMom)) nanstd(Fsp_roll_d3rdMom)];

% WB kin
dt_ds_d3rdMom_meanCIstd = [nanmean(dt_ds_d3rdMom) 1.96*nanstd(dt_ds_d3rdMom)/sqrt(length(dt_ds_d3rdMom)) nanstd(dt_ds_d3rdMom)];
dt_us_d3rdMom_meanCIstd = [nanmean(dt_us_d3rdMom) 1.96*nanstd(dt_us_d3rdMom)/sqrt(length(dt_us_d3rdMom)) nanstd(dt_us_d3rdMom)];
f_wb_d3rdMom_meanCIstd = [nanmean(f_wb_d3rdMom) 1.96*nanstd(f_wb_d3rdMom)/sqrt(length(f_wb_d3rdMom)) nanstd(f_wb_d3rdMom)];
Rds_d3rdMom_meanCIstd = [nanmean(Rds_d3rdMom) 1.96*nanstd(Rds_d3rdMom)/sqrt(length(Rds_d3rdMom)) nanstd(Rds_d3rdMom)];

calc_WBfunc_d3rdMom_circmeanCIstd

%% wbMOD means & 95%CI
velMOD_d3rdMom_meanCIstd = [nanmean(velMOD_d3rdMom) 1.96*nanstd(velMOD_d3rdMom)/sqrt(length(velMOD_d3rdMom)) nanstd(velMOD_d3rdMom)];

slipMOD_d3rdMom_meanCIstd = [nanmean(slipMOD_d3rdMom) 1.96*nanstd(slipMOD_d3rdMom)/sqrt(length(slipMOD_d3rdMom)) nanstd(slipMOD_d3rdMom)];
pitchMOD_d3rdMom_meanCIstd = [nanmean(pitchMOD_d3rdMom) 1.96*nanstd(pitchMOD_d3rdMom)/sqrt(length(pitchMOD_d3rdMom)) nanstd(pitchMOD_d3rdMom)];
rollMOD_d3rdMom_meanCIstd = [nanmean(rollMOD_d3rdMom) 1.96*nanstd(rollMOD_d3rdMom)/sqrt(length(rollMOD_d3rdMom)) nanstd(rollMOD_d3rdMom)];

Fsp_pitchMOD_d3rdMom_meanCIstd = [nanmean(Fsp_pitchMOD_d3rdMom) 1.96*nanstd(Fsp_pitchMOD_d3rdMom)/sqrt(length(Fsp_pitchMOD_d3rdMom)) nanstd(Fsp_pitchMOD_d3rdMom)];
Fsp_rollMOD_d3rdMom_meanCIstd = [nanmean(Fsp_rollMOD_d3rdMom) 1.96*nanstd(Fsp_rollMOD_d3rdMom)/sqrt(length(Fsp_rollMOD_d3rdMom)) nanstd(Fsp_rollMOD_d3rdMom)];

freqMOD_wb_d3rdMom_meanCIstd = [nanmean(freqMOD_wb_d3rdMom) 1.96*nanstd(freqMOD_wb_d3rdMom)/sqrt(length(freqMOD_wb_d3rdMom)) nanstd(freqMOD_wb_d3rdMom)];

calc_WBmod_d3rdMom_circmeanCIstd

%% WBfits
    t_loc = t_wb_d3rdMom_bins(:,1);
    Rds_loc = Rds_d3rdMom_meanCIstd(1);

%% fit for LEFT wing (bins)
    stroke_loc = stroke_wb_L_d3rdMom_bins_meanCIstd(:,1);
    pitch_loc = pitch_wb_L_d3rdMom_bins_meanCIstd(:,1);
    dev_loc = dev_wb_L_d3rdMom_bins_meanCIstd(:,1);
    
    strokeMOD_loc = strokeMOD_wb_L_d3rdMom_bins_meanCIstd(:,1);
    pitchMOD_loc = pitchMOD_wb_L_d3rdMom_bins_meanCIstd(:,1);
    devMOD_loc = devMOD_wb_L_d3rdMom_bins_meanCIstd(:,1);

        %% legendre polynomials
        % wingbeats
            [stroke_L_d3rdMom_fit_binmean, stroke_L_d3rdMom_fit_binmean_periodic] = WBfitting_singlevar_updowncut(n_pol_stroke,t_loc,stroke_loc,Rds_loc);
            [pitch_L_d3rdMom_fit_binmean, pitch_L_d3rdMom_fit_binmean_periodic] = WBfitting_singlevar_updowncut(n_pol_pitch,t_loc,pitch_loc,Rds_loc);
            [dev_L_d3rdMom_fit_binmean, dev_L_d3rdMom_fit_binmean_periodic] = WBfitting_singlevar_updowncut(n_pol_dev,t_loc,dev_loc,Rds_loc);

        % wingbeatMODs
            [strokeMOD_L_d3rdMom_fit_binmean, strokeMOD_L_d3rdMom_fit_binmean_periodic] = WBfitting_singlevar_updowncut(n_pol_MOD,t_loc,strokeMOD_loc,Rds_loc);
            [pitchMOD_L_d3rdMom_fit_binmean, pitchMOD_L_d3rdMom_fit_binmean_periodic] = WBfitting_singlevar_updowncut(n_pol_MOD,t_loc,pitchMOD_loc,Rds_loc);
            [devMOD_L_d3rdMom_fit_binmean, devMOD_L_d3rdMom_fit_binmean_periodic] = WBfitting_singlevar_updowncut(n_pol_MOD,t_loc,devMOD_loc,Rds_loc);

        %% fourier series
            % wingbeats
            [stroke_L_d3rdMom_fourier_fit_binmean, stroke_L_d3rdMom_fourier_gof_binmean,stroke_L_d3rdMom_fourier_coeffs_binmean] = create_fourier_series_4thN8th_order(t_loc, stroke_loc,stroke_fourier_order,plot_fourier);
            [pitch_L_d3rdMom_fourier_fit_binmean, pitch_L_d3rdMom_fourier_gof_binmean,pitch_L_d3rdMom_fourier_coeffs_binmean] = create_fourier_series_4thN8th_order(t_loc, pitch_loc,pitch_fourier_order,plot_fourier);
            [dev_L_d3rdMom_fourier_fit_binmean, dev_L_d3rdMom_fourier_gof_binmean,dev_L_d3rdMom_fourier_coeffs_binmean] = create_fourier_series_4thN8th_order(t_loc, dev_loc,dev_fourier_order,plot_fourier);

            % wingbeatMODs
            [strokeMOD_L_d3rdMom_fourier_fit_binmean, strokeMOD_L_d3rdMom_fourier_gof_binmean,strokeMOD_L_d3rdMom_fourier_coeffs_binmean] = create_fourier_series_4thN8th_order(t_loc, strokeMOD_loc,MOD_fourier_order,plot_fourier);
            [pitchMOD_L_d3rdMom_fourier_fit_binmean, pitchMOD_L_d3rdMom_fourier_gof_binmean,pitchMOD_L_d3rdMom_fourier_coeffs_binmean] = create_fourier_series_4thN8th_order(t_loc, pitchMOD_loc,MOD_fourier_order,plot_fourier);
            [devMOD_L_d3rdMom_fourier_fit_binmean, devMOD_L_d3rdMom_fourier_gof_binmean,devMOD_L_d3rdMom_fourier_coeffs_binmean] = create_fourier_series_4thN8th_order(t_loc, devMOD_loc,MOD_fourier_order,plot_fourier);
    
%% fit for Right wing (bins)
    stroke_loc = stroke_wb_R_d3rdMom_bins_meanCIstd(:,1);
    pitch_loc = pitch_wb_R_d3rdMom_bins_meanCIstd(:,1);
    dev_loc = dev_wb_R_d3rdMom_bins_meanCIstd(:,1);

    strokeMOD_loc = strokeMOD_wb_R_d3rdMom_bins_meanCIstd(:,1);
    pitchMOD_loc = pitchMOD_wb_R_d3rdMom_bins_meanCIstd(:,1);
    devMOD_loc = devMOD_wb_R_d3rdMom_bins_meanCIstd(:,1);

        %% legendre polynomials
        % wingbeats
            [stroke_R_d3rdMom_fit_binmean, stroke_R_d3rdMom_fit_binmean_periodic] = WBfitting_singlevar_updowncut(n_pol_stroke,t_loc,stroke_loc,Rds_loc);
            [pitch_R_d3rdMom_fit_binmean, pitch_R_d3rdMom_fit_binmean_periodic] = WBfitting_singlevar_updowncut(n_pol_pitch,t_loc,pitch_loc,Rds_loc);
            [dev_R_d3rdMom_fit_binmean, dev_R_d3rdMom_fit_binmean_periodic] = WBfitting_singlevar_updowncut(n_pol_dev,t_loc,dev_loc,Rds_loc);

        % wingbeatMODs
            [strokeMOD_R_d3rdMom_fit_binmean, strokeMOD_R_d3rdMom_fit_binmean_periodic] = WBfitting_singlevar_updowncut(n_pol_MOD,t_loc,strokeMOD_loc,Rds_loc);
            [pitchMOD_R_d3rdMom_fit_binmean, pitchMOD_R_d3rdMom_fit_binmean_periodic] = WBfitting_singlevar_updowncut(n_pol_MOD,t_loc,pitchMOD_loc,Rds_loc);
            [devMOD_R_d3rdMom_fit_binmean, devMOD_R_d3rdMom_fit_binmean_periodic] = WBfitting_singlevar_updowncut(n_pol_MOD,t_loc,devMOD_loc,Rds_loc);

        %% fourier series
            % wingbeats
            [stroke_R_d3rdMom_fourier_fit_binmean, stroke_R_d3rdMom_fourier_gof_binmean,stroke_R_d3rdMom_fourier_coeffs_binmean] = create_fourier_series_4thN8th_order(t_loc, stroke_loc,stroke_fourier_order,plot_fourier);
            [pitch_R_d3rdMom_fourier_fit_binmean, pitch_R_d3rdMom_fourier_gof_binmean,pitch_R_d3rdMom_fourier_coeffs_binmean] = create_fourier_series_4thN8th_order(t_loc, pitch_loc,pitch_fourier_order,plot_fourier);
            [dev_R_d3rdMom_fourier_fit_binmean, dev_R_d3rdMom_fourier_gof_binmean,dev_R_d3rdMom_fourier_coeffs_binmean] = create_fourier_series_4thN8th_order(t_loc, dev_loc,dev_fourier_order,plot_fourier);

            % wingbeatMODs
            [strokeMOD_R_d3rdMom_fourier_fit_binmean, strokeMOD_R_d3rdMom_fourier_gof_binmean,strokeMOD_R_d3rdMom_fourier_coeffs_binmean] = create_fourier_series_4thN8th_order(t_loc, strokeMOD_loc,MOD_fourier_order,plot_fourier);
            [pitchMOD_R_d3rdMom_fourier_fit_binmean, pitchMOD_R_d3rdMom_fourier_gof_binmean,pitchMOD_R_d3rdMom_fourier_coeffs_binmean] = create_fourier_series_4thN8th_order(t_loc, pitchMOD_loc,MOD_fourier_order,plot_fourier);
            [devMOD_R_d3rdMom_fourier_fit_binmean, devMOD_R_d3rdMom_fourier_gof_binmean,devMOD_R_d3rdMom_fourier_coeffs_binmean] = create_fourier_series_4thN8th_order(t_loc, devMOD_loc,MOD_fourier_order,plot_fourier);
    
%% L-R
    stroke_loc = Dstroke_wb_d3rdMom_bins_meanCIstd(:,1);
    pitch_loc = Dpitch_wb_d3rdMom_bins_meanCIstd(:,1);
    dev_loc = Ddev_wb_d3rdMom_bins_meanCIstd(:,1);

    strokeMOD_loc = DstrokeMOD_wb_d3rdMom_bins_meanCIstd(:,1);
    pitchMOD_loc = DpitchMOD_wb_d3rdMom_bins_meanCIstd(:,1);
    devMOD_loc = DdevMOD_wb_d3rdMom_bins_meanCIstd(:,1);
    
        %% legendre polynomials
            % wingbeats
            [Dstroke_d3rdMom_fit_binmean, Dstroke_d3rdMom_fit_binmean_periodic] = WBfitting_singlevar_updowncut(n_pol_stroke,t_loc,stroke_loc,Rds_loc);
            [Dpitch_d3rdMom_fit_binmean, Dpitch_d3rdMom_fit_binmean_periodic] = WBfitting_singlevar_updowncut(n_pol_pitch,t_loc,pitch_loc,Rds_loc);
            [Ddev_d3rdMom_fit_binmean, Ddev_d3rdMom_fit_binmean_periodic] = WBfitting_singlevar_updowncut(n_pol_dev,t_loc,dev_loc,Rds_loc);

        % wingbeatMODs
            [DstrokeMOD_d3rdMom_fit_binmean, DstrokeMOD_d3rdMom_fit_binmean_periodic] = WBfitting_singlevar_updowncut(n_pol_MOD,t_loc,strokeMOD_loc,Rds_loc);
            [DpitchMOD_d3rdMom_fit_binmean, DpitchMOD_d3rdMom_fit_binmean_periodic] = WBfitting_singlevar_updowncut(n_pol_MOD,t_loc,pitchMOD_loc,Rds_loc);
            [DdevMOD_d3rdMom_fit_binmean, DdevMOD_d3rdMom_fit_binmean_periodic] = WBfitting_singlevar_updowncut(n_pol_MOD,t_loc,devMOD_loc,Rds_loc);

        %% fourier series
            % wingbeats
            [Dstroke_d3rdMom_fourier_fit_binmean, Dstroke_d3rdMom_fourier_gof_binmean,Dstroke_d3rdMom_fourier_coeffs_binmean] = create_fourier_series_4thN8th_order(t_loc, stroke_loc,MOD_fourier_order,plot_fourier);
            [Dpitch_d3rdMom_fourier_fit_binmean, Dpitch_d3rdMom_fourier_gof_binmean,Dpitch_d3rdMom_fourier_coeffs_binmean] = create_fourier_series_4thN8th_order(t_loc, pitch_loc,MOD_fourier_order,plot_fourier);
            [Ddev_d3rdMom_fourier_fit_binmean, Ddev_d3rdMom_fourier_gof_binmean,Ddev_d3rdMom_fourier_coeffs_binmean] = create_fourier_series_4thN8th_order(t_loc, dev_loc,MOD_fourier_order,plot_fourier);

            % wingbeatMODs
            [DstrokeMOD_d3rdMom_fourier_fit_binmean, DstrokeMOD_d3rdMom_fourier_gof_binmean,DstrokeMOD_d3rdMom_fourier_coeffs_binmean] = create_fourier_series_4thN8th_order(t_loc, strokeMOD_loc,MOD_fourier_order,plot_fourier);
            [DpitchMOD_d3rdMom_fourier_fit_binmean, DpitchMOD_d3rdMom_fourier_gof_binmean,DpitchMOD_d3rdMom_fourier_coeffs_binmean] = create_fourier_series_4thN8th_order(t_loc, pitchMOD_loc,MOD_fourier_order,plot_fourier);
            [DdevMOD_d3rdMom_fourier_fit_binmean, DdevMOD_d3rdMom_fourier_gof_binmean,DdevMOD_d3rdMom_fourier_coeffs_binmean] = create_fourier_series_4thN8th_order(t_loc, devMOD_loc,MOD_fourier_order,plot_fourier);

%% save CLIPd wb data
n_d3rdMom = n_now   

if save_on == 1

    save(['WBmod_d3rdMom_',num2str(n_d3rdMom),'WBs.mat'],...
'n_d3rdMom',...
'seq_nr_d3rdMom',...
'wb_nr_d3rdMom',...
'ThirdMomentRatio_cut',...
'ThirdMomentRatio_plot',...
...
'n_pol_stroke',...
'n_pol_pitch',...
'n_pol_dev',...
'n_pol_MOD',...
...
'clip_side_d3rdMom',...
'clip_type_d3rdMom',...
...
'FirstMomentNormClipped_d3rdMom',...
'FirstMomentNormIntact_d3rdMom',...
'FirstMomentRatio_d3rdMom',...
...
'SecondMomentNormClipped_d3rdMom',...
'SecondMomentNormIntact_d3rdMom',...
'SecondMomentRatio_d3rdMom',...
...
'ThirdMomentNormClipped_d3rdMom',...
'ThirdMomentNormIntact_d3rdMom',...
'ThirdMomentRatio_d3rdMom',...
...
'AreaNormClipped_d3rdMom',...
'AreaNormIntact_d3rdMom',...
'AreaRatio_d3rdMom',...
...
'LengthClipped_pixels_d3rdMom',...
'LengthIntact_pixels_d3rdMom',...
'LengthRatio_d3rdMom',...
...
'stroke_R_d3rdMom_fit_binmean_periodic',...
'pitch_R_d3rdMom_fit_binmean_periodic',...
'dev_R_d3rdMom_fit_binmean_periodic',...
...
'stroke_L_d3rdMom_fit_binmean_periodic',...
'pitch_L_d3rdMom_fit_binmean_periodic',...
'dev_L_d3rdMom_fit_binmean_periodic',...
...
'strokeMOD_R_d3rdMom_fit_binmean_periodic',...
'pitchMOD_R_d3rdMom_fit_binmean_periodic',...
'devMOD_R_d3rdMom_fit_binmean_periodic',...
...
'strokeMOD_L_d3rdMom_fit_binmean_periodic',...
'pitchMOD_L_d3rdMom_fit_binmean_periodic',...
'devMOD_L_d3rdMom_fit_binmean_periodic',...
...
'stroke_fourier_order',...
'pitch_fourier_order',...
'dev_fourier_order',...
'MOD_fourier_order',...
...
'stroke_R_d3rdMom_fourier_coeffs_binmean',...
'pitch_R_d3rdMom_fourier_coeffs_binmean',...
'dev_R_d3rdMom_fourier_coeffs_binmean',...
...
'stroke_R_d3rdMom_fourier_gof_binmean',...
'pitch_R_d3rdMom_fourier_gof_binmean',...
'dev_R_d3rdMom_fourier_gof_binmean',...
...
'stroke_L_d3rdMom_fourier_coeffs_binmean',...
'pitch_L_d3rdMom_fourier_coeffs_binmean',...
'dev_L_d3rdMom_fourier_coeffs_binmean',...
...
'stroke_L_d3rdMom_fourier_gof_binmean',...
'pitch_L_d3rdMom_fourier_gof_binmean',...
'dev_L_d3rdMom_fourier_gof_binmean',...
...
'Dstroke_d3rdMom_fourier_coeffs_binmean',...
'Dpitch_d3rdMom_fourier_coeffs_binmean',...
'Ddev_d3rdMom_fourier_coeffs_binmean',...
...
'Dstroke_d3rdMom_fourier_gof_binmean',...
'Dpitch_d3rdMom_fourier_gof_binmean',...
'Ddev_d3rdMom_fourier_gof_binmean',...
...
'strokeMOD_R_d3rdMom_fourier_coeffs_binmean',...
'pitchMOD_R_d3rdMom_fourier_coeffs_binmean',...
'devMOD_R_d3rdMom_fourier_coeffs_binmean',...
...
'strokeMOD_R_d3rdMom_fourier_gof_binmean',...
'pitchMOD_R_d3rdMom_fourier_gof_binmean',...
'devMOD_R_d3rdMom_fourier_gof_binmean',...
...
'strokeMOD_L_d3rdMom_fourier_coeffs_binmean',...
'pitchMOD_L_d3rdMom_fourier_coeffs_binmean',...
'devMOD_L_d3rdMom_fourier_coeffs_binmean',...
...
'strokeMOD_L_d3rdMom_fourier_gof_binmean',...
'pitchMOD_L_d3rdMom_fourier_gof_binmean',...
'devMOD_L_d3rdMom_fourier_gof_binmean',...
...
'DstrokeMOD_d3rdMom_fourier_coeffs_binmean',...
'DpitchMOD_d3rdMom_fourier_coeffs_binmean',...
'DdevMOD_d3rdMom_fourier_coeffs_binmean',...
...
'DstrokeMOD_d3rdMom_fourier_gof_binmean',...
'DpitchMOD_d3rdMom_fourier_gof_binmean',...
'DdevMOD_d3rdMom_fourier_gof_binmean',...
...
'stroke_wb_R_d3rdMom_bins_meanCIstd',...
'stroke_ds_R_d3rdMom_bins_meanCIstd',...
'stroke_us_R_d3rdMom_bins_meanCIstd',...
...
'pitch_wb_R_d3rdMom_bins_meanCIstd',...
'pitch_ds_R_d3rdMom_bins_meanCIstd',...
'pitch_us_R_d3rdMom_bins_meanCIstd',...
...
'dev_wb_R_d3rdMom_bins_meanCIstd',...
'dev_ds_R_d3rdMom_bins_meanCIstd',...
'dev_us_R_d3rdMom_bins_meanCIstd',...
...
'strokeMOD_wb_R_d3rdMom_bins_meanCIstd',...
'strokeMOD_ds_R_d3rdMom_bins_meanCIstd',...
'strokeMOD_us_R_d3rdMom_bins_meanCIstd',...
...
'pitchMOD_wb_R_d3rdMom_bins_meanCIstd',...
'pitchMOD_ds_R_d3rdMom_bins_meanCIstd',...
'pitchMOD_us_R_d3rdMom_bins_meanCIstd',...
...
'devMOD_wb_R_d3rdMom_bins_meanCIstd',...
'devMOD_ds_R_d3rdMom_bins_meanCIstd',...
'devMOD_us_R_d3rdMom_bins_meanCIstd',...
...
'stroke_wb_L_d3rdMom_bins_meanCIstd',...
'stroke_ds_L_d3rdMom_bins_meanCIstd',...
'stroke_us_L_d3rdMom_bins_meanCIstd',...
...
'pitch_wb_L_d3rdMom_bins_meanCIstd',...
'pitch_ds_L_d3rdMom_bins_meanCIstd',...
'pitch_us_L_d3rdMom_bins_meanCIstd',...
...
'dev_wb_L_d3rdMom_bins_meanCIstd',...
'dev_ds_L_d3rdMom_bins_meanCIstd',...
'dev_us_L_d3rdMom_bins_meanCIstd',...
...
'strokeMOD_wb_L_d3rdMom_bins_meanCIstd',...
'strokeMOD_ds_L_d3rdMom_bins_meanCIstd',...
'strokeMOD_us_L_d3rdMom_bins_meanCIstd',...
...
'pitchMOD_wb_L_d3rdMom_bins_meanCIstd',...
'pitchMOD_ds_L_d3rdMom_bins_meanCIstd',...
'pitchMOD_us_L_d3rdMom_bins_meanCIstd',...
...
'devMOD_wb_L_d3rdMom_bins_meanCIstd',...
'devMOD_ds_L_d3rdMom_bins_meanCIstd',...
'devMOD_us_L_d3rdMom_bins_meanCIstd',...
...
'DstrokeMOD_wb_d3rdMom_bins_meanCIstd',...
'DstrokeMOD_ds_d3rdMom_bins_meanCIstd',...
'DstrokeMOD_us_d3rdMom_bins_meanCIstd',...
...
'DpitchMOD_wb_d3rdMom_bins_meanCIstd',...
'DpitchMOD_ds_d3rdMom_bins_meanCIstd',...
'DpitchMOD_us_d3rdMom_bins_meanCIstd',...
...
'DdevMOD_wb_d3rdMom_bins_meanCIstd',...
'DdevMOD_ds_d3rdMom_bins_meanCIstd',...
'DdevMOD_us_d3rdMom_bins_meanCIstd',...
...
'vel_d3rdMom',...
'slip_d3rdMom',...
'pitch_d3rdMom',...
'roll_d3rdMom',...
'Fsp_pitch_d3rdMom',...
'Fsp_roll_d3rdMom',...
...
'dt_ds_d3rdMom',...
'dt_us_d3rdMom',...
'f_wb_d3rdMom',...
'Rds_d3rdMom',...
...
'vel_d3rdMom_meanCIstd',...
'slip_d3rdMom_meanCIstd',...
'pitch_d3rdMom_meanCIstd',...
'roll_d3rdMom_meanCIstd',...
'Fsp_pitch_d3rdMom_meanCIstd',...
'Fsp_roll_d3rdMom_meanCIstd',...
...
'dt_ds_d3rdMom_meanCIstd',...
'dt_us_d3rdMom_meanCIstd',...
'f_wb_d3rdMom_meanCIstd',...
'Rds_d3rdMom_meanCIstd',...
...
'velMOD_d3rdMom_meanCIstd',...
'velMOD_d3rdMom',...
...
'slipMOD_d3rdMom_meanCIstd',...
'slipMOD_d3rdMom',...
...
'pitchMOD_d3rdMom_meanCIstd',...
'pitchMOD_d3rdMom',...
...
'rollMOD_d3rdMom_meanCIstd',...
'rollMOD_d3rdMom',...
...
'Fsp_pitchMOD_d3rdMom_meanCIstd',...
'Fsp_pitchMOD_d3rdMom',...
...
'Fsp_rollMOD_d3rdMom_meanCIstd',...
'Fsp_rollMOD_d3rdMom',...
...
'freqMOD_wb_d3rdMom_meanCIstd',...
'freqMOD_wb_d3rdMom',...
...
'strokeMOD_wb_L_d3rdMom_bins',...
'strokeMOD_wb_R_d3rdMom_bins',...
'strokeMOD_ds_L_d3rdMom_bins',...
'strokeMOD_ds_R_d3rdMom_bins',...
'strokeMOD_us_L_d3rdMom_bins',...
'strokeMOD_us_R_d3rdMom_bins',...
...
'pitchMOD_wb_L_d3rdMom_bins',...
'pitchMOD_wb_R_d3rdMom_bins',...
'pitchMOD_ds_L_d3rdMom_bins',...
'pitchMOD_ds_R_d3rdMom_bins',...
'pitchMOD_us_L_d3rdMom_bins',...
'pitchMOD_us_R_d3rdMom_bins',...
...
'devMOD_wb_L_d3rdMom_bins',...
'devMOD_wb_R_d3rdMom_bins',...
'devMOD_ds_L_d3rdMom_bins',...
'devMOD_ds_R_d3rdMom_bins',...
'devMOD_us_L_d3rdMom_bins',...
'devMOD_us_R_d3rdMom_bins',...
...
'DstrokeMOD_wb_d3rdMom_bins',...
'DstrokeMOD_ds_d3rdMom_bins',...
'DstrokeMOD_us_d3rdMom_bins',...
...
'DpitchMOD_wb_d3rdMom_bins',...
'DpitchMOD_ds_d3rdMom_bins',...
'DpitchMOD_us_d3rdMom_bins',...
...
'DdevMOD_wb_d3rdMom_bins',...
'DdevMOD_ds_d3rdMom_bins',...
'DdevMOD_us_d3rdMom_bins',...
...
't_wb_L_d3rdMom',...
't_wb_R_d3rdMom',...
'stroke_wb_L_d3rdMom',...
'stroke_wb_R_d3rdMom',...
'pitch_wb_L_d3rdMom',...
'pitch_wb_R_d3rdMom',...
'dev_wb_L_d3rdMom',...
'dev_wb_R_d3rdMom',...
'aoa_wb_L_d3rdMom',...
'aoa_wb_R_d3rdMom',...
'U_wb_L_d3rdMom',...
'U_wb_R_d3rdMom',...
...
't_ds_L_d3rdMom',...
't_ds_R_d3rdMom',...
'stroke_ds_L_d3rdMom',...
'stroke_ds_R_d3rdMom',...
'pitch_ds_L_d3rdMom',...
'pitch_ds_R_d3rdMom',...
'dev_ds_L_d3rdMom',...
'dev_ds_R_d3rdMom',...
'aoa_ds_L_d3rdMom',...
'aoa_ds_R_d3rdMom',...
'U_ds_L_d3rdMom',...
'U_ds_R_d3rdMom',...
...
't_us_L_d3rdMom',...
't_us_R_d3rdMom',...
'stroke_us_L_d3rdMom',...
'stroke_us_R_d3rdMom',...
'pitch_us_L_d3rdMom',...
'pitch_us_R_d3rdMom',...
'dev_us_L_d3rdMom',...
'dev_us_R_d3rdMom',...
'aoa_us_L_d3rdMom',...
'aoa_us_R_d3rdMom',...
'U_us_L_d3rdMom',...
'U_us_R_d3rdMom',...
...
't_wb_d3rdMom_bins',...
'stroke_wb_L_d3rdMom_bins',...
'stroke_wb_R_d3rdMom_bins',...
'pitch_wb_L_d3rdMom_bins',...
'pitch_wb_R_d3rdMom_bins',...
'dev_wb_L_d3rdMom_bins',...
'dev_wb_R_d3rdMom_bins',...
'aoa_wb_L_d3rdMom_bins',...
'aoa_wb_R_d3rdMom_bins',...
'U_wb_L_d3rdMom_bins',...
'U_wb_R_d3rdMom_bins',...
'Dstroke_wb_d3rdMom_bins',...
'Dpitch_wb_d3rdMom_bins',...
'Ddev_wb_d3rdMom_bins',...
'Daoa_wb_d3rdMom_bins',...
'DU_wb_d3rdMom_bins',...
...
't_ds_d3rdMom_bins',...
'stroke_ds_L_d3rdMom_bins',...
'stroke_ds_R_d3rdMom_bins',...
'pitch_ds_L_d3rdMom_bins',...
'pitch_ds_R_d3rdMom_bins',...
'dev_ds_L_d3rdMom_bins',...
'dev_ds_R_d3rdMom_bins',...
'aoa_ds_L_d3rdMom_bins',...
'aoa_ds_R_d3rdMom_bins',...
'U_ds_L_d3rdMom_bins',...
'U_ds_R_d3rdMom_bins',...
'Dstroke_ds_d3rdMom_bins',...
'Dpitch_ds_d3rdMom_bins',...
'Ddev_ds_d3rdMom_bins',...
'Daoa_ds_d3rdMom_bins',...
'DU_ds_d3rdMom_bins',...
...
't_us_d3rdMom_bins',...
'stroke_us_L_d3rdMom_bins',...
'stroke_us_R_d3rdMom_bins',...
'pitch_us_L_d3rdMom_bins',...
'pitch_us_R_d3rdMom_bins',...
'dev_us_L_d3rdMom_bins',...
'dev_us_R_d3rdMom_bins',...
'aoa_us_L_d3rdMom_bins',...
'aoa_us_R_d3rdMom_bins',...
'U_us_L_d3rdMom_bins',...
'U_us_R_d3rdMom_bins',...
'Dstroke_us_d3rdMom_bins',...
'Dpitch_us_d3rdMom_bins',...
'Ddev_us_d3rdMom_bins',...
'Daoa_us_d3rdMom_bins',...
'DU_us_d3rdMom_bins');

end

