% calc wb MOD CLIP S2S3funcClipped

n_now=0;

%% variables

% bodyMODs
velMOD_S2S3funcClipped = [];

slipMOD_S2S3funcClipped = [];
pitchMOD_S2S3funcClipped = [];
rollMOD_S2S3funcClipped = [];

Fsp_pitchMOD_S2S3funcClipped = [];
Fsp_rollMOD_S2S3funcClipped = [];

% wbMOD
freqMOD_wb_S2S3funcClipped = [];

strokeMOD_wb_L_S2S3funcClipped_bins = [];
strokeMOD_wb_R_S2S3funcClipped_bins = [];
strokeMOD_ds_L_S2S3funcClipped_bins = [];
strokeMOD_ds_R_S2S3funcClipped_bins = [];
strokeMOD_us_L_S2S3funcClipped_bins = [];
strokeMOD_us_R_S2S3funcClipped_bins = [];

pitchMOD_wb_L_S2S3funcClipped_bins = [];
pitchMOD_wb_R_S2S3funcClipped_bins = [];
pitchMOD_ds_L_S2S3funcClipped_bins = [];
pitchMOD_ds_R_S2S3funcClipped_bins = [];
pitchMOD_us_L_S2S3funcClipped_bins = [];
pitchMOD_us_R_S2S3funcClipped_bins = [];

devMOD_wb_L_S2S3funcClipped_bins = [];
devMOD_wb_R_S2S3funcClipped_bins = [];
devMOD_ds_L_S2S3funcClipped_bins = [];
devMOD_ds_R_S2S3funcClipped_bins = [];
devMOD_us_L_S2S3funcClipped_bins = [];
devMOD_us_R_S2S3funcClipped_bins = [];

DstrokeMOD_wb_S2S3funcClipped_bins = [];
DstrokeMOD_ds_S2S3funcClipped_bins = [];
DstrokeMOD_us_S2S3funcClipped_bins = [];

DpitchMOD_wb_S2S3funcClipped_bins = [];
DpitchMOD_ds_S2S3funcClipped_bins = [];
DpitchMOD_us_S2S3funcClipped_bins = [];

DdevMOD_wb_S2S3funcClipped_bins = [];
DdevMOD_ds_S2S3funcClipped_bins = [];
DdevMOD_us_S2S3funcClipped_bins = [];

% seq&wb
seq_nr_S2S3funcClipped = [];
wb_nr_S2S3funcClipped = [];

% clip data
clip_side_S2S3funcClipped = [];
clip_type_S2S3funcClipped = [];

FirstMomentNormClipped_S2S3funcClipped = [];
FirstMomentNormIntact_S2S3funcClipped = [];
FirstMomentRatio_S2S3funcClipped = [];

SecondMomentNormClipped_S2S3funcClipped = [];
SecondMomentNormIntact_S2S3funcClipped = [];
SecondMomentRatio_S2S3funcClipped = [];

ThirdMomentNormClipped_S2S3funcClipped = [];
ThirdMomentNormIntact_S2S3funcClipped = [];
ThirdMomentRatio_S2S3funcClipped = [];

AreaNormClipped_S2S3funcClipped = [];
AreaNormIntact_S2S3funcClipped = [];
AreaRatio_S2S3funcClipped = [];

LengthClipped_pixels_S2S3funcClipped = [];
LengthIntact_pixels_S2S3funcClipped = [];
LengthRatio_S2S3funcClipped = [];

% body kin
vel_S2S3funcClipped = [];

slip_S2S3funcClipped = [];
pitch_S2S3funcClipped = [];
roll_S2S3funcClipped = [];

Fsp_pitch_S2S3funcClipped = [];
Fsp_roll_S2S3funcClipped = [];

% wingbeat kin
dt_wb_S2S3funcClipped = [];
dt_ds_S2S3funcClipped = [];
dt_us_S2S3funcClipped = [];
f_wb_S2S3funcClipped = [];
Rds_S2S3funcClipped = [];

t_wb_L_S2S3funcClipped = [];
t_wb_R_S2S3funcClipped = [];
stroke_wb_L_S2S3funcClipped = [];
stroke_wb_R_S2S3funcClipped = [];
pitch_wb_L_S2S3funcClipped = [];
pitch_wb_R_S2S3funcClipped = [];
dev_wb_L_S2S3funcClipped = [];
dev_wb_R_S2S3funcClipped = [];
aoa_wb_L_S2S3funcClipped = [];
aoa_wb_R_S2S3funcClipped = [];
U_wb_L_S2S3funcClipped = [];
U_wb_R_S2S3funcClipped = [];
Dstroke_wb_S2S3funcClipped = [];
Dpitch_wb_S2S3funcClipped = [];
Ddev_wb_S2S3funcClipped = [];
Daoa_wb_S2S3funcClipped = [];
DU_wb_S2S3funcClipped = [];

t_ds_L_S2S3funcClipped = [];
t_ds_R_S2S3funcClipped = [];
stroke_ds_L_S2S3funcClipped = [];
stroke_ds_R_S2S3funcClipped = [];
pitch_ds_L_S2S3funcClipped = [];
pitch_ds_R_S2S3funcClipped = [];
dev_ds_L_S2S3funcClipped = [];
dev_ds_R_S2S3funcClipped = [];
aoa_ds_L_S2S3funcClipped = [];
aoa_ds_R_S2S3funcClipped = [];
U_ds_L_S2S3funcClipped = [];
U_ds_R_S2S3funcClipped = [];
Dstroke_ds_S2S3funcClipped = [];
Dpitch_ds_S2S3funcClipped = [];
Ddev_ds_S2S3funcClipped = [];
Daoa_ds_S2S3funcClipped = [];
DU_ds_S2S3funcClipped = [];

t_us_L_S2S3funcClipped = [];
t_us_R_S2S3funcClipped = [];
stroke_us_L_S2S3funcClipped = [];
stroke_us_R_S2S3funcClipped = [];
pitch_us_L_S2S3funcClipped = [];
pitch_us_R_S2S3funcClipped = [];
dev_us_L_S2S3funcClipped = [];
dev_us_R_S2S3funcClipped = [];
aoa_us_L_S2S3funcClipped = [];
aoa_us_R_S2S3funcClipped = [];
U_us_L_S2S3funcClipped = [];
U_us_R_S2S3funcClipped = [];
Dstroke_us_S2S3funcClipped = [];
Dpitch_us_S2S3funcClipped = [];
Ddev_us_S2S3funcClipped = [];
Daoa_us_S2S3funcClipped = [];
DU_us_S2S3funcClipped = [];

t_wb_S2S3funcClipped_bins = [];
stroke_wb_L_S2S3funcClipped_bins = [];
stroke_wb_R_S2S3funcClipped_bins = [];
pitch_wb_L_S2S3funcClipped_bins = [];
pitch_wb_R_S2S3funcClipped_bins = [];
dev_wb_L_S2S3funcClipped_bins = [];
dev_wb_R_S2S3funcClipped_bins = [];
aoa_wb_L_S2S3funcClipped_bins = [];
aoa_wb_R_S2S3funcClipped_bins = [];
U_wb_L_S2S3funcClipped_bins = [];
U_wb_R_S2S3funcClipped_bins = [];
Dstroke_wb_S2S3funcClipped_bins = [];
Dpitch_wb_S2S3funcClipped_bins = [];
Ddev_wb_S2S3funcClipped_bins = [];
Daoa_wb_S2S3funcClipped_bins = [];
DU_wb_S2S3funcClipped_bins = [];

t_ds_S2S3funcClipped_bins = [];
stroke_ds_L_S2S3funcClipped_bins = [];
stroke_ds_R_S2S3funcClipped_bins = [];
pitch_ds_L_S2S3funcClipped_bins = [];
pitch_ds_R_S2S3funcClipped_bins = [];
dev_ds_L_S2S3funcClipped_bins = [];
dev_ds_R_S2S3funcClipped_bins = [];
aoa_ds_L_S2S3funcClipped_bins = [];
aoa_ds_R_S2S3funcClipped_bins = [];
U_ds_L_S2S3funcClipped_bins = [];
U_ds_R_S2S3funcClipped_bins = [];
Dstroke_ds_S2S3funcClipped_bins = [];
Dpitch_ds_S2S3funcClipped_bins = [];
Ddev_ds_S2S3funcClipped_bins = [];
Daoa_ds_S2S3funcClipped_bins = [];
DU_ds_S2S3funcClipped_bins = [];

t_us_S2S3funcClipped_bins = [];
stroke_us_L_S2S3funcClipped_bins = [];
stroke_us_R_S2S3funcClipped_bins = [];
pitch_us_L_S2S3funcClipped_bins = [];
pitch_us_R_S2S3funcClipped_bins = [];
dev_us_L_S2S3funcClipped_bins = [];
dev_us_R_S2S3funcClipped_bins = [];
aoa_us_L_S2S3funcClipped_bins = [];
aoa_us_R_S2S3funcClipped_bins = [];
U_us_L_S2S3funcClipped_bins = [];
U_us_R_S2S3funcClipped_bins = [];
Dstroke_us_S2S3funcClipped_bins = [];
Dpitch_us_S2S3funcClipped_bins = [];
Ddev_us_S2S3funcClipped_bins = [];
Daoa_us_S2S3funcClipped_bins = [];
DU_us_S2S3funcClipped_bins = [];

for wb = 1:size(wb_nr,1)
    counter = size(wb_nr,1) -wb
        
%         if steady_nr_mean_wb(wb) == 1 && abs(S2S3funcClipped(wb)-S2S3funcClipped_NONclipped) > abs(S2S3funcClipped_cut)
        if steady_nr_mean_wb(wb) == 1 && (S2S3funcClipped_NONclipped-S2S3funcClipped(wb)) > (S2S3funcClipped_cut)
            
            % current wb
            seq_nr_now = seq_nr(wb);
            wb_nr_now = wb_nr(wb);
            
            % clip data
            clip_side_now = clip_side(wb);
            clip_type_now = clip_type(wb);
            
            S2S3funcIntact_now = S2S3funcIntact(wb);
            S2S3funcClipped_now = S2S3funcClipped(wb);

            FirstMomentNormClipped_now = FirstMomentNormClipped(wb);
            FirstMomentNormIntact_now = FirstMomentNormIntact(wb);
            FirstMomentRatio_now = FirstMomentRatio(wb);

            SecondMomentNormClipped_now = SecondMomentNormClipped(wb);
            SecondMomentNormIntact_now = SecondMomentNormIntact(wb);
            SecondMomentRatio_now = SecondMomentRatio(wb);

            ThirdMomentNormClipped_now = ThirdMomentNormClipped(wb);
            ThirdMomentNormIntact_now = ThirdMomentNormIntact(wb);
            ThirdMomentRatio_now = ThirdMomentRatio(wb);

            AreaNormClipped_now = AreaNormClipped(wb);
            AreaNormIntact_now = AreaNormIntact(wb);
            AreaRatio_now = AreaRatio(wb);

            LengthClipped_pixels_now = LengthClipped_pixels(wb);
            LengthIntact_pixels_now = LengthIntact_pixels(wb);
            LengthRatio_now = LengthRatio(wb);

            % body kin
            vel_now = V_mean_wb(wb);
            
            slip_now = slip_mean_wb(wb);
            pitch_now = pitch_mean_wb(wb);
            roll_now = roll_mean_wb(wb);
            
            Fsp_pitch_now = Fsp_pitch_mean_wb(wb);
            Fsp_roll_now = Fsp_roll_mean_wb(wb);
            
            % wingbeat kin
            dt_ds_now = ([dt_ds_L(wb),dt_ds_R(wb)]);
            dt_us_now = ([dt_us_L(wb),dt_us_R(wb)]);
            f_wb_now = ([f_wb_L(wb),f_wb_R(wb)]);
            Rds_now = dt_ds_now ./ (dt_ds_now + dt_us_now);
            
            stroke_wb_L_now = stroke_wb_L(:,wb);
            stroke_wb_R_now = stroke_wb_R(:,wb);
            stroke_ds_L_now = stroke_ds_L(:,wb);
            stroke_ds_R_now = stroke_ds_R(:,wb);
            stroke_us_L_now = stroke_us_L(:,wb);
            stroke_us_R_now = stroke_us_R(:,wb);
            
            pitch_wb_L_now = pitch_wb_L(:,wb);
            pitch_wb_R_now = pitch_wb_R(:,wb);
            pitch_ds_L_now = pitch_ds_L(:,wb);
            pitch_ds_R_now = pitch_ds_R(:,wb);
            pitch_us_L_now = pitch_us_L(:,wb);
            pitch_us_R_now = pitch_us_R(:,wb);
            
            dev_wb_L_now = dev_wb_L(:,wb);
            dev_wb_R_now = dev_wb_R(:,wb);
            dev_ds_L_now = dev_ds_L(:,wb);
            dev_ds_R_now = dev_ds_R(:,wb);
            dev_us_L_now = dev_us_L(:,wb);
            dev_us_R_now = dev_us_R(:,wb);
            
            U_wb_L_now = U_wb_L(:,wb);
            U_wb_R_now = U_wb_R(:,wb);
            U_ds_L_now = U_ds_L(:,wb);
            U_ds_R_now = U_ds_R(:,wb);
            U_us_L_now = U_us_L(:,wb);
            U_us_R_now = U_us_R(:,wb);
            
            aoa_wb_L_now = aoa_wb_L(:,wb);
            aoa_wb_R_now = aoa_wb_R(:,wb);
            aoa_ds_L_now = aoa_ds_L(:,wb);
            aoa_ds_R_now = aoa_ds_R(:,wb);
            aoa_us_L_now = aoa_us_L(:,wb);
            aoa_us_R_now = aoa_us_R(:,wb);
            
            t_wb_L_now = t_wb_L(:,wb);
            t_wb_R_now = t_wb_R(:,wb);
            t_ds_L_now = t_ds_L(:,wb);
            t_ds_R_now = t_ds_R(:,wb);
            t_us_L_now = t_us_L(:,wb);
            t_us_R_now = t_us_R(:,wb);

            % interpolated data
            stroke_wb_L_interp = stroke_wb_L_bins(:,wb);
            stroke_wb_R_interp = stroke_wb_R_bins(:,wb);
            stroke_ds_L_interp = stroke_ds_L_bins(:,wb);
            stroke_ds_R_interp = stroke_ds_R_bins(:,wb);
            stroke_us_L_interp = stroke_us_L_bins(:,wb);
            stroke_us_R_interp = stroke_us_R_bins(:,wb);
            
            pitch_wb_L_interp = pitch_wb_L_bins(:,wb);
            pitch_wb_R_interp = pitch_wb_R_bins(:,wb);
            pitch_ds_L_interp = pitch_ds_L_bins(:,wb);
            pitch_ds_R_interp = pitch_ds_R_bins(:,wb);
            pitch_us_L_interp = pitch_us_L_bins(:,wb);
            pitch_us_R_interp = pitch_us_R_bins(:,wb);
            
            dev_wb_L_interp = dev_wb_L_bins(:,wb);
            dev_wb_R_interp = dev_wb_R_bins(:,wb);
            dev_ds_L_interp = dev_ds_L_bins(:,wb);
            dev_ds_R_interp = dev_ds_R_bins(:,wb);
            dev_us_L_interp = dev_us_L_bins(:,wb);
            dev_us_R_interp = dev_us_R_bins(:,wb);
            
            U_wb_L_interp = U_wb_L_bins(:,wb);
            U_wb_R_interp = U_wb_R_bins(:,wb);
            U_ds_L_interp = U_ds_L_bins(:,wb);
            U_ds_R_interp = U_ds_R_bins(:,wb);
            U_us_L_interp = U_us_L_bins(:,wb);
            U_us_R_interp = U_us_R_bins(:,wb);
            
            aoa_wb_L_interp = aoa_wb_L_bins(:,wb);
            aoa_wb_R_interp = aoa_wb_R_bins(:,wb);
            aoa_ds_L_interp = aoa_ds_L_bins(:,wb);
            aoa_ds_R_interp = aoa_ds_R_bins(:,wb);
            aoa_us_L_interp = aoa_us_L_bins(:,wb);
            aoa_us_R_interp = aoa_us_R_bins(:,wb);

            Dstroke_wb_interp = Dstroke_wb_bins(:,wb);
            Dstroke_ds_interp = Dstroke_ds_bins(:,wb);
            Dstroke_us_interp = Dstroke_us_bins(:,wb);
            
            Dpitch_wb_interp = Dpitch_wb_bins(:,wb);
            Dpitch_ds_interp = Dpitch_ds_bins(:,wb);
            Dpitch_us_interp = Dpitch_us_bins(:,wb);
            
            Ddev_wb_interp = Ddev_wb_bins(:,wb);
            Ddev_ds_interp = Ddev_ds_bins(:,wb);
            Ddev_us_interp = Ddev_us_bins(:,wb);
            
            DU_wb_interp = DU_wb_bins(:,wb);
            DU_ds_interp = DU_ds_bins(:,wb);
            DU_us_interp = DU_us_bins(:,wb);
            
            Daoa_wb_interp = Daoa_wb_bins(:,wb);
            Daoa_ds_interp = Daoa_ds_bins(:,wb);
            Daoa_us_interp = Daoa_us_bins(:,wb);
            
            
            %% calc bodykin modifications
            velMOD_now   = (nanmean(vel_now) - vel_steady)          / (S2S3funcClipped_now-S2S3funcClipped_NONclipped);

            slipMOD_now  =  nanmean(slip_now)                       / (S2S3funcClipped_now-S2S3funcClipped_NONclipped);
            pitchMOD_now = (nanmean(pitch_now) - pitch_body_steady) / (S2S3funcClipped_now-S2S3funcClipped_NONclipped);
            rollMOD_now  =  nanmean(roll_now)                       / (S2S3funcClipped_now-S2S3funcClipped_NONclipped);

            Fsp_pitchMOD_now = nanmean(Fsp_pitch_now)               / (S2S3funcClipped_now-S2S3funcClipped_NONclipped);
            Fsp_rollMOD_now  = nanmean(Fsp_roll_now)                / (S2S3funcClipped_now-S2S3funcClipped_NONclipped);

            %% calc wingbeat modifications
            freqMOD_wb_now =     (nanmean(f_wb_now)  - f_wb_steady)      / (S2S3funcClipped_now-S2S3funcClipped_NONclipped);
            
            strokeMOD_wb_L_now = (stroke_wb_L_interp - stroke_wb_steady) / (S2S3funcClipped_now-S2S3funcClipped_NONclipped);
            strokeMOD_wb_R_now = (stroke_wb_R_interp - stroke_wb_steady) / (S2S3funcClipped_now-S2S3funcClipped_NONclipped);
            strokeMOD_ds_L_now = (stroke_ds_L_interp - stroke_ds_steady) / (S2S3funcClipped_now-S2S3funcClipped_NONclipped);
            strokeMOD_ds_R_now = (stroke_ds_R_interp - stroke_ds_steady) / (S2S3funcClipped_now-S2S3funcClipped_NONclipped);
            strokeMOD_us_L_now = (stroke_us_L_interp - stroke_us_steady) / (S2S3funcClipped_now-S2S3funcClipped_NONclipped);
            strokeMOD_us_R_now = (stroke_us_R_interp - stroke_us_steady) / (S2S3funcClipped_now-S2S3funcClipped_NONclipped);
            
            pitchMOD_wb_L_now = (pitch_wb_L_interp - pitch_wb_steady) / (S2S3funcClipped_now-S2S3funcClipped_NONclipped);
            pitchMOD_wb_R_now = (pitch_wb_R_interp - pitch_wb_steady) / (S2S3funcClipped_now-S2S3funcClipped_NONclipped);
            pitchMOD_ds_L_now = (pitch_ds_L_interp - pitch_ds_steady) / (S2S3funcClipped_now-S2S3funcClipped_NONclipped);
            pitchMOD_ds_R_now = (pitch_ds_R_interp - pitch_ds_steady) / (S2S3funcClipped_now-S2S3funcClipped_NONclipped);
            pitchMOD_us_L_now = (pitch_us_L_interp - pitch_us_steady) / (S2S3funcClipped_now-S2S3funcClipped_NONclipped);
            pitchMOD_us_R_now = (pitch_us_R_interp - pitch_us_steady) / (S2S3funcClipped_now-S2S3funcClipped_NONclipped);
            
            devMOD_wb_L_now = (dev_wb_L_interp - dev_wb_steady) / (S2S3funcClipped_now-S2S3funcClipped_NONclipped);
            devMOD_wb_R_now = (dev_wb_R_interp - dev_wb_steady) / (S2S3funcClipped_now-S2S3funcClipped_NONclipped);
            devMOD_ds_L_now = (dev_ds_L_interp - dev_ds_steady) / (S2S3funcClipped_now-S2S3funcClipped_NONclipped);
            devMOD_ds_R_now = (dev_ds_R_interp - dev_ds_steady) / (S2S3funcClipped_now-S2S3funcClipped_NONclipped);
            devMOD_us_L_now = (dev_us_L_interp - dev_us_steady) / (S2S3funcClipped_now-S2S3funcClipped_NONclipped);
            devMOD_us_R_now = (dev_us_R_interp - dev_us_steady) / (S2S3funcClipped_now-S2S3funcClipped_NONclipped);
            
            DstrokeMOD_wb_now = Dstroke_wb_interp / (S2S3funcClipped_now-S2S3funcClipped_NONclipped);
            DstrokeMOD_ds_now = Dstroke_ds_interp / (S2S3funcClipped_now-S2S3funcClipped_NONclipped);
            DstrokeMOD_us_now = Dstroke_us_interp / (S2S3funcClipped_now-S2S3funcClipped_NONclipped);

            DpitchMOD_wb_now = Dpitch_wb_interp / (S2S3funcClipped_now-S2S3funcClipped_NONclipped);
            DpitchMOD_ds_now = Dpitch_ds_interp / (S2S3funcClipped_now-S2S3funcClipped_NONclipped);
            DpitchMOD_us_now = Dpitch_us_interp / (S2S3funcClipped_now-S2S3funcClipped_NONclipped);

            DdevMOD_wb_now = Ddev_wb_interp / (S2S3funcClipped_now-S2S3funcClipped_NONclipped);
            DdevMOD_ds_now = Ddev_ds_interp / (S2S3funcClipped_now-S2S3funcClipped_NONclipped);
            DdevMOD_us_now = Ddev_us_interp / (S2S3funcClipped_now-S2S3funcClipped_NONclipped);
            
            %% store data
            n_now=n_now+1;

            seq_nr_S2S3funcClipped(n_now,1) = seq_nr_now;
            wb_nr_S2S3funcClipped(n_now,1) = wb_nr_now;

            % clip data
            clip_side_S2S3funcClipped(n_now,1) = clip_side_now;
            clip_type_S2S3funcClipped(n_now,1) = clip_type_now;

            S2S3funcIntact_S2S3funcClipped(n_now,1) = S2S3funcIntact_now;
            S2S3funcClipped_S2S3funcClipped(n_now,1) = S2S3funcClipped_now;

            FirstMomentNormClipped_S2S3funcClipped(n_now,1) = FirstMomentNormClipped_now;
            FirstMomentNormIntact_S2S3funcClipped(n_now,1) = FirstMomentNormIntact_now;
            FirstMomentRatio_S2S3funcClipped(n_now,1) = FirstMomentRatio_now;

            SecondMomentNormClipped_S2S3funcClipped(n_now,1) = SecondMomentNormClipped_now;
            SecondMomentNormIntact_S2S3funcClipped(n_now,1) = SecondMomentNormIntact_now;
            SecondMomentRatio_S2S3funcClipped(n_now,1) = SecondMomentRatio_now;

            ThirdMomentNormClipped_S2S3funcClipped(n_now,1) = ThirdMomentNormClipped_now;
            ThirdMomentNormIntact_S2S3funcClipped(n_now,1) = ThirdMomentNormIntact_now;
            ThirdMomentRatio_S2S3funcClipped(n_now,1) = ThirdMomentRatio_now;

            AreaNormClipped_S2S3funcClipped(n_now,1) = AreaNormClipped_now;
            AreaNormIntact_S2S3funcClipped(n_now,1) = AreaNormIntact_now;
            AreaRatio_S2S3funcClipped(n_now,1) = AreaRatio_now;

            LengthClipped_pixels_S2S3funcClipped(n_now,1) = LengthClipped_pixels_now;
            LengthIntact_pixels_S2S3funcClipped(n_now,1) = LengthIntact_pixels_now;
            LengthRatio_S2S3funcClipped(n_now,1) = LengthRatio_now;

            % body kin
            vel_S2S3funcClipped(n_now,1) = vel_now;

            slip_S2S3funcClipped(n_now,1) = slip_now;
            pitch_S2S3funcClipped(n_now,1) = pitch_now;
            roll_S2S3funcClipped(n_now,1) = roll_now;

            Fsp_pitch_S2S3funcClipped(n_now,1) = Fsp_pitch_now;
            Fsp_roll_S2S3funcClipped(n_now,1) = Fsp_roll_now;

            % wingbeat kin
            dt_ds_S2S3funcClipped(n_now,1) = nanmean(dt_ds_now);
            dt_us_S2S3funcClipped(n_now,1) = nanmean(dt_us_now);
            f_wb_S2S3funcClipped(n_now,1) = nanmean(f_wb_now);
            Rds_S2S3funcClipped(n_now,1) = nanmean(Rds_now);

            t_wb_L_S2S3funcClipped(1:length(t_wb_L_now),n_now) = t_wb_L_now;
            t_wb_R_S2S3funcClipped(1:length(t_wb_R_now),n_now) = t_wb_R_now;
            stroke_wb_L_S2S3funcClipped(1:length(t_wb_L_now),n_now) = stroke_wb_L_now;
            stroke_wb_R_S2S3funcClipped(1:length(t_wb_R_now),n_now) = stroke_wb_R_now;
            pitch_wb_L_S2S3funcClipped(1:length(t_wb_L_now),n_now) = pitch_wb_L_now;
            pitch_wb_R_S2S3funcClipped(1:length(t_wb_R_now),n_now) = pitch_wb_R_now;
            dev_wb_L_S2S3funcClipped(1:length(t_wb_L_now),n_now) = dev_wb_L_now;
            dev_wb_R_S2S3funcClipped(1:length(t_wb_R_now),n_now) = dev_wb_R_now;
            aoa_wb_L_S2S3funcClipped(1:length(t_wb_L_now),n_now) = aoa_wb_L_now;
            aoa_wb_R_S2S3funcClipped(1:length(t_wb_R_now),n_now) = aoa_wb_R_now;
            U_wb_L_S2S3funcClipped(1:length(t_wb_L_now),n_now) = U_wb_L_now;
            U_wb_R_S2S3funcClipped(1:length(t_wb_R_now),n_now) = U_wb_R_now;
            
            t_ds_L_S2S3funcClipped(1:length(t_ds_L_now),n_now) = t_ds_L_now;
            t_ds_R_S2S3funcClipped(1:length(t_ds_R_now),n_now) = t_ds_R_now;
            stroke_ds_L_S2S3funcClipped(1:length(t_ds_L_now),n_now) = stroke_ds_L_now;
            stroke_ds_R_S2S3funcClipped(1:length(t_ds_R_now),n_now) = stroke_ds_R_now;
            pitch_ds_L_S2S3funcClipped(1:length(t_ds_L_now),n_now) = pitch_ds_L_now;
            pitch_ds_R_S2S3funcClipped(1:length(t_ds_R_now),n_now) = pitch_ds_R_now;
            dev_ds_L_S2S3funcClipped(1:length(t_ds_L_now),n_now) = dev_ds_L_now;
            dev_ds_R_S2S3funcClipped(1:length(t_ds_R_now),n_now) = dev_ds_R_now;
            aoa_ds_L_S2S3funcClipped(1:length(t_ds_L_now),n_now) = aoa_ds_L_now;
            aoa_ds_R_S2S3funcClipped(1:length(t_ds_R_now),n_now) = aoa_ds_R_now;
            U_ds_L_S2S3funcClipped(1:length(t_ds_L_now),n_now) = U_ds_L_now;
            U_ds_R_S2S3funcClipped(1:length(t_ds_R_now),n_now) = U_ds_R_now;
            
            t_us_L_S2S3funcClipped(1:length(t_us_L_now),n_now) = t_us_L_now;
            t_us_R_S2S3funcClipped(1:length(t_us_R_now),n_now) = t_us_R_now;
            stroke_us_L_S2S3funcClipped(1:length(t_us_L_now),n_now) = stroke_us_L_now;
            stroke_us_R_S2S3funcClipped(1:length(t_us_R_now),n_now) = stroke_us_R_now;
            pitch_us_L_S2S3funcClipped(1:length(t_us_L_now),n_now) = pitch_us_L_now;
            pitch_us_R_S2S3funcClipped(1:length(t_us_R_now),n_now) = pitch_us_R_now;
            dev_us_L_S2S3funcClipped(1:length(t_us_L_now),n_now) = dev_us_L_now;
            dev_us_R_S2S3funcClipped(1:length(t_us_R_now),n_now) = dev_us_R_now;
            aoa_us_L_S2S3funcClipped(1:length(t_us_L_now),n_now) = aoa_us_L_now;
            aoa_us_R_S2S3funcClipped(1:length(t_us_R_now),n_now) = aoa_us_R_now;
            U_us_L_S2S3funcClipped(1:length(t_us_L_now),n_now) = U_us_L_now;
            U_us_R_S2S3funcClipped(1:length(t_us_R_now),n_now) = U_us_R_now;
            
            % store interp binned data separate rows
            t_wb_S2S3funcClipped_bins(:,n_now) = t_wb_bin;
            stroke_wb_L_S2S3funcClipped_bins(:,n_now) = stroke_wb_L_interp;
            stroke_wb_R_S2S3funcClipped_bins(:,n_now) = stroke_wb_R_interp;
            pitch_wb_L_S2S3funcClipped_bins(:,n_now) = pitch_wb_L_interp;
            pitch_wb_R_S2S3funcClipped_bins(:,n_now) = pitch_wb_R_interp;
            dev_wb_L_S2S3funcClipped_bins(:,n_now) = dev_wb_L_interp;
            dev_wb_R_S2S3funcClipped_bins(:,n_now) = dev_wb_R_interp;
            aoa_wb_L_S2S3funcClipped_bins(:,n_now) = aoa_wb_L_interp;
            aoa_wb_R_S2S3funcClipped_bins(:,n_now) = aoa_wb_R_interp;
            U_wb_L_S2S3funcClipped_bins(:,n_now) = U_wb_L_interp;
            U_wb_R_S2S3funcClipped_bins(:,n_now) = U_wb_R_interp;
            Dstroke_wb_S2S3funcClipped_bins(:,n_now) = Dstroke_wb_interp;
            Dpitch_wb_S2S3funcClipped_bins(:,n_now) = Dpitch_wb_interp;
            Ddev_wb_S2S3funcClipped_bins(:,n_now) = Ddev_wb_interp;
            Daoa_wb_S2S3funcClipped_bins(:,n_now) = Daoa_wb_interp;
            DU_wb_S2S3funcClipped_bins(:,n_now) = DU_wb_interp;
            
            t_ds_S2S3funcClipped_bins(:,n_now) = t_ds_bin;
            stroke_ds_L_S2S3funcClipped_bins(:,n_now) = stroke_ds_L_interp;
            stroke_ds_R_S2S3funcClipped_bins(:,n_now) = stroke_ds_R_interp;
            pitch_ds_L_S2S3funcClipped_bins(:,n_now) = pitch_ds_L_interp;
            pitch_ds_R_S2S3funcClipped_bins(:,n_now) = pitch_ds_R_interp;
            dev_ds_L_S2S3funcClipped_bins(:,n_now) = dev_ds_L_interp;
            dev_ds_R_S2S3funcClipped_bins(:,n_now) = dev_ds_R_interp;
            aoa_ds_L_S2S3funcClipped_bins(:,n_now) = aoa_ds_L_interp;
            aoa_ds_R_S2S3funcClipped_bins(:,n_now) = aoa_ds_R_interp;
            U_ds_L_S2S3funcClipped_bins(:,n_now) = U_ds_L_interp;
            U_ds_R_S2S3funcClipped_bins(:,n_now) = U_ds_R_interp;
            Dstroke_ds_S2S3funcClipped_bins(:,n_now) = Dstroke_ds_interp;
            Dpitch_ds_S2S3funcClipped_bins(:,n_now) = Dpitch_ds_interp;
            Ddev_ds_S2S3funcClipped_bins(:,n_now) = Ddev_ds_interp;
            Daoa_ds_S2S3funcClipped_bins(:,n_now) = Daoa_ds_interp;
            DU_ds_S2S3funcClipped_bins(:,n_now) = DU_ds_interp;
            
            t_us_S2S3funcClipped_bins(:,n_now) = t_us_bin;
            stroke_us_L_S2S3funcClipped_bins(:,n_now) = stroke_us_L_interp;
            stroke_us_R_S2S3funcClipped_bins(:,n_now) = stroke_us_R_interp;
            pitch_us_L_S2S3funcClipped_bins(:,n_now) = pitch_us_L_interp;
            pitch_us_R_S2S3funcClipped_bins(:,n_now) = pitch_us_R_interp;
            dev_us_L_S2S3funcClipped_bins(:,n_now) = dev_us_L_interp;
            dev_us_R_S2S3funcClipped_bins(:,n_now) = dev_us_R_interp;
            aoa_us_L_S2S3funcClipped_bins(:,n_now) = aoa_us_L_interp;
            aoa_us_R_S2S3funcClipped_bins(:,n_now) = aoa_us_R_interp;
            U_us_L_S2S3funcClipped_bins(:,n_now) = U_us_L_interp;
            U_us_R_S2S3funcClipped_bins(:,n_now) = U_us_R_interp;
            Dstroke_us_S2S3funcClipped_bins(:,n_now) = Dstroke_us_interp;
            Dpitch_us_S2S3funcClipped_bins(:,n_now) = Dpitch_us_interp;
            Ddev_us_S2S3funcClipped_bins(:,n_now) = Ddev_us_interp;
            Daoa_us_S2S3funcClipped_bins(:,n_now) = Daoa_us_interp;
            DU_us_S2S3funcClipped_bins(:,n_now) = DU_us_interp;
            
            %% store MOD data
            
            %  bodykin modifications
            velMOD_S2S3funcClipped(n_now,1) = velMOD_now;
            
            slipMOD_S2S3funcClipped(n_now,1) = slipMOD_now;
            pitchMOD_S2S3funcClipped(n_now,1) = pitchMOD_now;
            rollMOD_S2S3funcClipped(n_now,1) = rollMOD_now;

            Fsp_pitchMOD_S2S3funcClipped(n_now,1) = Fsp_pitchMOD_now;
            Fsp_rollMOD_S2S3funcClipped(n_now,1) = Fsp_rollMOD_now;

            %  WB modifications
            freqMOD_wb_S2S3funcClipped(n_now,1) = freqMOD_wb_now;
            
            strokeMOD_wb_L_S2S3funcClipped_bins(:,n_now) = strokeMOD_wb_L_now;
            strokeMOD_wb_R_S2S3funcClipped_bins(:,n_now) = strokeMOD_wb_R_now;
            strokeMOD_ds_L_S2S3funcClipped_bins(:,n_now) = strokeMOD_ds_L_now;
            strokeMOD_ds_R_S2S3funcClipped_bins(:,n_now) = strokeMOD_ds_R_now;
            strokeMOD_us_L_S2S3funcClipped_bins(:,n_now) = strokeMOD_us_L_now;
            strokeMOD_us_R_S2S3funcClipped_bins(:,n_now) = strokeMOD_us_R_now;

            pitchMOD_wb_L_S2S3funcClipped_bins(:,n_now) = pitchMOD_wb_L_now;
            pitchMOD_wb_R_S2S3funcClipped_bins(:,n_now) = pitchMOD_wb_R_now;
            pitchMOD_ds_L_S2S3funcClipped_bins(:,n_now) = pitchMOD_ds_L_now;
            pitchMOD_ds_R_S2S3funcClipped_bins(:,n_now) = pitchMOD_ds_R_now;
            pitchMOD_us_L_S2S3funcClipped_bins(:,n_now) = pitchMOD_us_L_now;
            pitchMOD_us_R_S2S3funcClipped_bins(:,n_now) = pitchMOD_us_R_now;

            devMOD_wb_L_S2S3funcClipped_bins(:,n_now) = devMOD_wb_L_now;
            devMOD_wb_R_S2S3funcClipped_bins(:,n_now) = devMOD_wb_R_now;
            devMOD_ds_L_S2S3funcClipped_bins(:,n_now) = devMOD_ds_L_now;
            devMOD_ds_R_S2S3funcClipped_bins(:,n_now) = devMOD_ds_R_now;
            devMOD_us_L_S2S3funcClipped_bins(:,n_now) = devMOD_us_L_now;
            devMOD_us_R_S2S3funcClipped_bins(:,n_now) = devMOD_us_R_now;

            DstrokeMOD_wb_S2S3funcClipped_bins(:,n_now) = DstrokeMOD_wb_now;
            DstrokeMOD_ds_S2S3funcClipped_bins(:,n_now) = DstrokeMOD_ds_now;
            DstrokeMOD_us_S2S3funcClipped_bins(:,n_now) = DstrokeMOD_us_now;

            DpitchMOD_wb_S2S3funcClipped_bins(:,n_now) = DpitchMOD_wb_now;
            DpitchMOD_ds_S2S3funcClipped_bins(:,n_now) = DpitchMOD_ds_now;
            DpitchMOD_us_S2S3funcClipped_bins(:,n_now) = DpitchMOD_us_now;

            DdevMOD_wb_S2S3funcClipped_bins(:,n_now) = DdevMOD_wb_now;
            DdevMOD_ds_S2S3funcClipped_bins(:,n_now) = DdevMOD_ds_now;
            DdevMOD_us_S2S3funcClipped_bins(:,n_now) = DdevMOD_us_now;
        end
end

%% mean & 95%CI
% body kin
vel_S2S3funcClipped_meanCIstd = [nanmean(vel_S2S3funcClipped) 1.96*nanstd(vel_S2S3funcClipped)/sqrt(length(vel_S2S3funcClipped)) nanstd(vel_S2S3funcClipped)];

slip_S2S3funcClipped_meanCIstd = [nanmean(slip_S2S3funcClipped) 1.96*nanstd(slip_S2S3funcClipped)/sqrt(length(slip_S2S3funcClipped)) nanstd(slip_S2S3funcClipped)];
pitch_S2S3funcClipped_meanCIstd = [nanmean(pitch_S2S3funcClipped) 1.96*nanstd(pitch_S2S3funcClipped)/sqrt(length(pitch_S2S3funcClipped)) nanstd(pitch_S2S3funcClipped)];
roll_S2S3funcClipped_meanCIstd = [nanmean(roll_S2S3funcClipped) 1.96*nanstd(roll_S2S3funcClipped)/sqrt(length(roll_S2S3funcClipped)) nanstd(roll_S2S3funcClipped)];

Fsp_pitch_S2S3funcClipped_meanCIstd = [nanmean(Fsp_pitch_S2S3funcClipped) 1.96*nanstd(Fsp_pitch_S2S3funcClipped)/sqrt(length(Fsp_pitch_S2S3funcClipped)) nanstd(Fsp_pitch_S2S3funcClipped)];
Fsp_roll_S2S3funcClipped_meanCIstd = [nanmean(Fsp_roll_S2S3funcClipped) 1.96*nanstd(Fsp_roll_S2S3funcClipped)/sqrt(length(Fsp_roll_S2S3funcClipped)) nanstd(Fsp_roll_S2S3funcClipped)];

% WB kin
dt_ds_S2S3funcClipped_meanCIstd = [nanmean(dt_ds_S2S3funcClipped) 1.96*nanstd(dt_ds_S2S3funcClipped)/sqrt(length(dt_ds_S2S3funcClipped)) nanstd(dt_ds_S2S3funcClipped)];
dt_us_S2S3funcClipped_meanCIstd = [nanmean(dt_us_S2S3funcClipped) 1.96*nanstd(dt_us_S2S3funcClipped)/sqrt(length(dt_us_S2S3funcClipped)) nanstd(dt_us_S2S3funcClipped)];
f_wb_S2S3funcClipped_meanCIstd = [nanmean(f_wb_S2S3funcClipped) 1.96*nanstd(f_wb_S2S3funcClipped)/sqrt(length(f_wb_S2S3funcClipped)) nanstd(f_wb_S2S3funcClipped)];
Rds_S2S3funcClipped_meanCIstd = [nanmean(Rds_S2S3funcClipped) 1.96*nanstd(Rds_S2S3funcClipped)/sqrt(length(Rds_S2S3funcClipped)) nanstd(Rds_S2S3funcClipped)];

% calc_WBfunc_S2S3funcClipped_circmeanCIstd
calc_WBfunc_S2S3funcClipped_NOcircmeanCIstd

%% wbMOD means & 95%CI
velMOD_S2S3funcClipped_meanCIstd = [nanmean(velMOD_S2S3funcClipped) 1.96*nanstd(velMOD_S2S3funcClipped)/sqrt(length(velMOD_S2S3funcClipped)) nanstd(velMOD_S2S3funcClipped)];

slipMOD_S2S3funcClipped_meanCIstd = [nanmean(slipMOD_S2S3funcClipped) 1.96*nanstd(slipMOD_S2S3funcClipped)/sqrt(length(slipMOD_S2S3funcClipped)) nanstd(slipMOD_S2S3funcClipped)];
pitchMOD_S2S3funcClipped_meanCIstd = [nanmean(pitchMOD_S2S3funcClipped) 1.96*nanstd(pitchMOD_S2S3funcClipped)/sqrt(length(pitchMOD_S2S3funcClipped)) nanstd(pitchMOD_S2S3funcClipped)];
rollMOD_S2S3funcClipped_meanCIstd = [nanmean(rollMOD_S2S3funcClipped) 1.96*nanstd(rollMOD_S2S3funcClipped)/sqrt(length(rollMOD_S2S3funcClipped)) nanstd(rollMOD_S2S3funcClipped)];

Fsp_pitchMOD_S2S3funcClipped_meanCIstd = [nanmean(Fsp_pitchMOD_S2S3funcClipped) 1.96*nanstd(Fsp_pitchMOD_S2S3funcClipped)/sqrt(length(Fsp_pitchMOD_S2S3funcClipped)) nanstd(Fsp_pitchMOD_S2S3funcClipped)];
Fsp_rollMOD_S2S3funcClipped_meanCIstd = [nanmean(Fsp_rollMOD_S2S3funcClipped) 1.96*nanstd(Fsp_rollMOD_S2S3funcClipped)/sqrt(length(Fsp_rollMOD_S2S3funcClipped)) nanstd(Fsp_rollMOD_S2S3funcClipped)];

freqMOD_wb_S2S3funcClipped_meanCIstd = [nanmean(freqMOD_wb_S2S3funcClipped) 1.96*nanstd(freqMOD_wb_S2S3funcClipped)/sqrt(length(freqMOD_wb_S2S3funcClipped)) nanstd(freqMOD_wb_S2S3funcClipped)];

% calc_WBmod_S2S3funcClipped_circmeanCIstd
calc_WBmod_S2S3funcClipped_NOcircmeanCIstd

%% WBfits
%% fit for LEFT wing (bins)
    t_loc = t_wb_S2S3funcClipped_bins(:,1);
    Rds_loc = Rds_S2S3funcClipped_meanCIstd(1);

    stroke_loc = stroke_wb_L_S2S3funcClipped_bins_meanCIstd(:,1);
    pitch_loc = pitch_wb_L_S2S3funcClipped_bins_meanCIstd(:,1);
    dev_loc = dev_wb_L_S2S3funcClipped_bins_meanCIstd(:,1);
    
    strokeMOD_loc = strokeMOD_wb_L_S2S3funcClipped_bins_meanCIstd(:,1);
    pitchMOD_loc = pitchMOD_wb_L_S2S3funcClipped_bins_meanCIstd(:,1);
    devMOD_loc = devMOD_wb_L_S2S3funcClipped_bins_meanCIstd(:,1);

        %% legendre polynomials
        % wingbeats
            [stroke_L_S2S3funcClipped_fit_binmean, stroke_L_S2S3funcClipped_fit_binmean_periodic] = WBfitting_singlevar_updowncut(n_pol_stroke,t_loc,stroke_loc,Rds_loc);
            [pitch_L_S2S3funcClipped_fit_binmean, pitch_L_S2S3funcClipped_fit_binmean_periodic] = WBfitting_singlevar_updowncut(n_pol_pitch,t_loc,pitch_loc,Rds_loc);
            [dev_L_S2S3funcClipped_fit_binmean, dev_L_S2S3funcClipped_fit_binmean_periodic] = WBfitting_singlevar_updowncut(n_pol_dev,t_loc,dev_loc,Rds_loc);

        % wingbeatMODs
            [strokeMOD_L_S2S3funcClipped_fit_binmean, strokeMOD_L_S2S3funcClipped_fit_binmean_periodic] = WBfitting_singlevar_updowncut(n_pol_MOD,t_loc,strokeMOD_loc,Rds_loc);
            [pitchMOD_L_S2S3funcClipped_fit_binmean, pitchMOD_L_S2S3funcClipped_fit_binmean_periodic] = WBfitting_singlevar_updowncut(n_pol_MOD,t_loc,pitchMOD_loc,Rds_loc);
            [devMOD_L_S2S3funcClipped_fit_binmean, devMOD_L_S2S3funcClipped_fit_binmean_periodic] = WBfitting_singlevar_updowncut(n_pol_MOD,t_loc,devMOD_loc,Rds_loc);

        %% fourier series
            % ALL data (NO circmean)
            t_loc = t_wb_S2S3funcClipped_bins(:);
            
            stroke_loc = stroke_wb_L_S2S3funcClipped_bins(:);
            pitch_loc = pitch_wb_L_S2S3funcClipped_bins(:);
            dev_loc = dev_wb_L_S2S3funcClipped_bins(:);

            strokeMOD_loc = strokeMOD_wb_L_S2S3funcClipped_bins(:);
            pitchMOD_loc = pitchMOD_wb_L_S2S3funcClipped_bins(:);
            devMOD_loc = devMOD_wb_L_S2S3funcClipped_bins(:);

            % wingbeats
            [stroke_L_S2S3funcClipped_fourier_fit_binmean, stroke_L_S2S3funcClipped_fourier_gof_binmean,stroke_L_S2S3funcClipped_fourier_coeffs_binmean] = create_fourier_series_4thN8th_order(t_loc, stroke_loc,stroke_fourier_order,plot_fourier);
            [pitch_L_S2S3funcClipped_fourier_fit_binmean, pitch_L_S2S3funcClipped_fourier_gof_binmean,pitch_L_S2S3funcClipped_fourier_coeffs_binmean] = create_fourier_series_4thN8th_order(t_loc, pitch_loc,pitch_fourier_order,plot_fourier);
            [dev_L_S2S3funcClipped_fourier_fit_binmean, dev_L_S2S3funcClipped_fourier_gof_binmean,dev_L_S2S3funcClipped_fourier_coeffs_binmean] = create_fourier_series_4thN8th_order(t_loc, dev_loc,dev_fourier_order,plot_fourier);

            % wingbeatMODs
            [strokeMOD_L_S2S3funcClipped_fourier_fit_binmean, strokeMOD_L_S2S3funcClipped_fourier_gof_binmean,strokeMOD_L_S2S3funcClipped_fourier_coeffs_binmean] = create_fourier_series_4thN8th_order(t_loc, strokeMOD_loc,MOD_fourier_order,plot_fourier);
            [pitchMOD_L_S2S3funcClipped_fourier_fit_binmean, pitchMOD_L_S2S3funcClipped_fourier_gof_binmean,pitchMOD_L_S2S3funcClipped_fourier_coeffs_binmean] = create_fourier_series_4thN8th_order(t_loc, pitchMOD_loc,MOD_fourier_order,plot_fourier);
            [devMOD_L_S2S3funcClipped_fourier_fit_binmean, devMOD_L_S2S3funcClipped_fourier_gof_binmean,devMOD_L_S2S3funcClipped_fourier_coeffs_binmean] = create_fourier_series_4thN8th_order(t_loc, devMOD_loc,MOD_fourier_order,plot_fourier);
            
%% fit for Right wing (bins)
    t_loc = t_wb_S2S3funcClipped_bins(:,1);
    Rds_loc = Rds_S2S3funcClipped_meanCIstd(1);

    stroke_loc = stroke_wb_R_S2S3funcClipped_bins_meanCIstd(:,1);
    pitch_loc = pitch_wb_R_S2S3funcClipped_bins_meanCIstd(:,1);
    dev_loc = dev_wb_R_S2S3funcClipped_bins_meanCIstd(:,1);

    strokeMOD_loc = strokeMOD_wb_R_S2S3funcClipped_bins_meanCIstd(:,1);
    pitchMOD_loc = pitchMOD_wb_R_S2S3funcClipped_bins_meanCIstd(:,1);
    devMOD_loc = devMOD_wb_R_S2S3funcClipped_bins_meanCIstd(:,1);

        %% legendre polynomials
        % wingbeats
            [stroke_R_S2S3funcClipped_fit_binmean, stroke_R_S2S3funcClipped_fit_binmean_periodic] = WBfitting_singlevar_updowncut(n_pol_stroke,t_loc,stroke_loc,Rds_loc);
            [pitch_R_S2S3funcClipped_fit_binmean, pitch_R_S2S3funcClipped_fit_binmean_periodic] = WBfitting_singlevar_updowncut(n_pol_pitch,t_loc,pitch_loc,Rds_loc);
            [dev_R_S2S3funcClipped_fit_binmean, dev_R_S2S3funcClipped_fit_binmean_periodic] = WBfitting_singlevar_updowncut(n_pol_dev,t_loc,dev_loc,Rds_loc);

        % wingbeatMODs
            [strokeMOD_R_S2S3funcClipped_fit_binmean, strokeMOD_R_S2S3funcClipped_fit_binmean_periodic] = WBfitting_singlevar_updowncut(n_pol_MOD,t_loc,strokeMOD_loc,Rds_loc);
            [pitchMOD_R_S2S3funcClipped_fit_binmean, pitchMOD_R_S2S3funcClipped_fit_binmean_periodic] = WBfitting_singlevar_updowncut(n_pol_MOD,t_loc,pitchMOD_loc,Rds_loc);
            [devMOD_R_S2S3funcClipped_fit_binmean, devMOD_R_S2S3funcClipped_fit_binmean_periodic] = WBfitting_singlevar_updowncut(n_pol_MOD,t_loc,devMOD_loc,Rds_loc);

        %% fourier series
            % ALL data (NO circmean)
            t_loc = t_wb_S2S3funcClipped_bins(:);
            
            stroke_loc = stroke_wb_R_S2S3funcClipped_bins(:);
            pitch_loc = pitch_wb_R_S2S3funcClipped_bins(:);
            dev_loc = dev_wb_R_S2S3funcClipped_bins(:);

            strokeMOD_loc = strokeMOD_wb_R_S2S3funcClipped_bins(:);
            pitchMOD_loc = pitchMOD_wb_R_S2S3funcClipped_bins(:);
            devMOD_loc = devMOD_wb_R_S2S3funcClipped_bins(:);

            % wingbeats
            [stroke_R_S2S3funcClipped_fourier_fit_binmean, stroke_R_S2S3funcClipped_fourier_gof_binmean,stroke_R_S2S3funcClipped_fourier_coeffs_binmean] = create_fourier_series_4thN8th_order(t_loc, stroke_loc,stroke_fourier_order,plot_fourier);
            [pitch_R_S2S3funcClipped_fourier_fit_binmean, pitch_R_S2S3funcClipped_fourier_gof_binmean,pitch_R_S2S3funcClipped_fourier_coeffs_binmean] = create_fourier_series_4thN8th_order(t_loc, pitch_loc,pitch_fourier_order,plot_fourier);
            [dev_R_S2S3funcClipped_fourier_fit_binmean, dev_R_S2S3funcClipped_fourier_gof_binmean,dev_R_S2S3funcClipped_fourier_coeffs_binmean] = create_fourier_series_4thN8th_order(t_loc, dev_loc,dev_fourier_order,plot_fourier);

            % wingbeatMODs
            [strokeMOD_R_S2S3funcClipped_fourier_fit_binmean, strokeMOD_R_S2S3funcClipped_fourier_gof_binmean,strokeMOD_R_S2S3funcClipped_fourier_coeffs_binmean] = create_fourier_series_4thN8th_order(t_loc, strokeMOD_loc,MOD_fourier_order,plot_fourier);
            [pitchMOD_R_S2S3funcClipped_fourier_fit_binmean, pitchMOD_R_S2S3funcClipped_fourier_gof_binmean,pitchMOD_R_S2S3funcClipped_fourier_coeffs_binmean] = create_fourier_series_4thN8th_order(t_loc, pitchMOD_loc,MOD_fourier_order,plot_fourier);
            [devMOD_R_S2S3funcClipped_fourier_fit_binmean, devMOD_R_S2S3funcClipped_fourier_gof_binmean,devMOD_R_S2S3funcClipped_fourier_coeffs_binmean] = create_fourier_series_4thN8th_order(t_loc, devMOD_loc,MOD_fourier_order,plot_fourier);
    
%% L-R
    t_loc = t_wb_S2S3funcClipped_bins(:,1);
    Rds_loc = Rds_S2S3funcClipped_meanCIstd(1);

    stroke_loc = Dstroke_wb_S2S3funcClipped_bins_meanCIstd(:,1);
    pitch_loc = Dpitch_wb_S2S3funcClipped_bins_meanCIstd(:,1);
    dev_loc = Ddev_wb_S2S3funcClipped_bins_meanCIstd(:,1);

    strokeMOD_loc = DstrokeMOD_wb_S2S3funcClipped_bins_meanCIstd(:,1);
    pitchMOD_loc = DpitchMOD_wb_S2S3funcClipped_bins_meanCIstd(:,1);
    devMOD_loc = DdevMOD_wb_S2S3funcClipped_bins_meanCIstd(:,1);
    
        %% legendre polynomials
            % wingbeats
            [Dstroke_S2S3funcClipped_fit_binmean, Dstroke_S2S3funcClipped_fit_binmean_periodic] = WBfitting_singlevar_updowncut(n_pol_stroke,t_loc,stroke_loc,Rds_loc);
            [Dpitch_S2S3funcClipped_fit_binmean, Dpitch_S2S3funcClipped_fit_binmean_periodic] = WBfitting_singlevar_updowncut(n_pol_pitch,t_loc,pitch_loc,Rds_loc);
            [Ddev_S2S3funcClipped_fit_binmean, Ddev_S2S3funcClipped_fit_binmean_periodic] = WBfitting_singlevar_updowncut(n_pol_dev,t_loc,dev_loc,Rds_loc);

        % wingbeatMODs
            [DstrokeMOD_S2S3funcClipped_fit_binmean, DstrokeMOD_S2S3funcClipped_fit_binmean_periodic] = WBfitting_singlevar_updowncut(n_pol_MOD,t_loc,strokeMOD_loc,Rds_loc);
            [DpitchMOD_S2S3funcClipped_fit_binmean, DpitchMOD_S2S3funcClipped_fit_binmean_periodic] = WBfitting_singlevar_updowncut(n_pol_MOD,t_loc,pitchMOD_loc,Rds_loc);
            [DdevMOD_S2S3funcClipped_fit_binmean, DdevMOD_S2S3funcClipped_fit_binmean_periodic] = WBfitting_singlevar_updowncut(n_pol_MOD,t_loc,devMOD_loc,Rds_loc);

        %% fourier series
            % ALL data (NO circmean)
            t_loc = t_wb_S2S3funcClipped_bins(:);
            
            stroke_loc = Dstroke_wb_S2S3funcClipped_bins(:);
            pitch_loc = Dpitch_wb_S2S3funcClipped_bins(:);
            dev_loc = Ddev_wb_S2S3funcClipped_bins(:);

            strokeMOD_loc = DstrokeMOD_wb_S2S3funcClipped_bins(:);
            pitchMOD_loc = DpitchMOD_wb_S2S3funcClipped_bins(:);
            devMOD_loc = DdevMOD_wb_S2S3funcClipped_bins(:);

            % wingbeats
            [Dstroke_S2S3funcClipped_fourier_fit_binmean, Dstroke_S2S3funcClipped_fourier_gof_binmean,Dstroke_S2S3funcClipped_fourier_coeffs_binmean] = create_fourier_series_4thN8th_order(t_loc, stroke_loc,MOD_fourier_order,plot_fourier);
            [Dpitch_S2S3funcClipped_fourier_fit_binmean, Dpitch_S2S3funcClipped_fourier_gof_binmean,Dpitch_S2S3funcClipped_fourier_coeffs_binmean] = create_fourier_series_4thN8th_order(t_loc, pitch_loc,MOD_fourier_order,plot_fourier);
            [Ddev_S2S3funcClipped_fourier_fit_binmean, Ddev_S2S3funcClipped_fourier_gof_binmean,Ddev_S2S3funcClipped_fourier_coeffs_binmean] = create_fourier_series_4thN8th_order(t_loc, dev_loc,MOD_fourier_order,plot_fourier);

            % wingbeatMODs
            [DstrokeMOD_S2S3funcClipped_fourier_fit_binmean, DstrokeMOD_S2S3funcClipped_fourier_gof_binmean,DstrokeMOD_S2S3funcClipped_fourier_coeffs_binmean] = create_fourier_series_4thN8th_order(t_loc, strokeMOD_loc,MOD_fourier_order,plot_fourier);
            [DpitchMOD_S2S3funcClipped_fourier_fit_binmean, DpitchMOD_S2S3funcClipped_fourier_gof_binmean,DpitchMOD_S2S3funcClipped_fourier_coeffs_binmean] = create_fourier_series_4thN8th_order(t_loc, pitchMOD_loc,MOD_fourier_order,plot_fourier);
            [DdevMOD_S2S3funcClipped_fourier_fit_binmean, DdevMOD_S2S3funcClipped_fourier_gof_binmean,DdevMOD_S2S3funcClipped_fourier_coeffs_binmean] = create_fourier_series_4thN8th_order(t_loc, devMOD_loc,MOD_fourier_order,plot_fourier);

%% save CLIPd wb data
n_S2S3funcClipped = n_now   

if save_on == 1

    save(['WBmod_S2S3ForceFuncClipped_',num2str(n_S2S3funcClipped),'WBs.mat'],...
'n_S2S3funcClipped',...
'seq_nr_S2S3funcClipped',...
'wb_nr_S2S3funcClipped',...
'S2S3funcClipped_cut',...
'S2S3funcClipped_plot',...
'S2norm_plot',...
'S3norm_plot',...
...
'n_pol_stroke',...
'n_pol_pitch',...
'n_pol_dev',...
'n_pol_MOD',...
...
'clip_side_S2S3funcClipped',...
'clip_type_S2S3funcClipped',...
...
'S2S3funcIntact_S2S3funcClipped',...
'S2S3funcClipped_S2S3funcClipped',...
...
'FirstMomentNormClipped_S2S3funcClipped',...
'FirstMomentNormIntact_S2S3funcClipped',...
'FirstMomentRatio_S2S3funcClipped',...
...
'SecondMomentNormClipped_S2S3funcClipped',...
'SecondMomentNormIntact_S2S3funcClipped',...
'SecondMomentRatio_S2S3funcClipped',...
...
'ThirdMomentNormClipped_S2S3funcClipped',...
'ThirdMomentNormIntact_S2S3funcClipped',...
'ThirdMomentRatio_S2S3funcClipped',...
...
'AreaNormClipped_S2S3funcClipped',...
'AreaNormIntact_S2S3funcClipped',...
'AreaRatio_S2S3funcClipped',...
...
'LengthClipped_pixels_S2S3funcClipped',...
'LengthIntact_pixels_S2S3funcClipped',...
'LengthRatio_S2S3funcClipped',...
...
'stroke_R_S2S3funcClipped_fit_binmean_periodic',...
'pitch_R_S2S3funcClipped_fit_binmean_periodic',...
'dev_R_S2S3funcClipped_fit_binmean_periodic',...
...
'stroke_L_S2S3funcClipped_fit_binmean_periodic',...
'pitch_L_S2S3funcClipped_fit_binmean_periodic',...
'dev_L_S2S3funcClipped_fit_binmean_periodic',...
...
'strokeMOD_R_S2S3funcClipped_fit_binmean_periodic',...
'pitchMOD_R_S2S3funcClipped_fit_binmean_periodic',...
'devMOD_R_S2S3funcClipped_fit_binmean_periodic',...
...
'strokeMOD_L_S2S3funcClipped_fit_binmean_periodic',...
'pitchMOD_L_S2S3funcClipped_fit_binmean_periodic',...
'devMOD_L_S2S3funcClipped_fit_binmean_periodic',...
...
'stroke_fourier_order',...
'pitch_fourier_order',...
'dev_fourier_order',...
'MOD_fourier_order',...
...
'stroke_R_S2S3funcClipped_fourier_coeffs_binmean',...
'pitch_R_S2S3funcClipped_fourier_coeffs_binmean',...
'dev_R_S2S3funcClipped_fourier_coeffs_binmean',...
...
'stroke_R_S2S3funcClipped_fourier_gof_binmean',...
'pitch_R_S2S3funcClipped_fourier_gof_binmean',...
'dev_R_S2S3funcClipped_fourier_gof_binmean',...
...
'stroke_L_S2S3funcClipped_fourier_coeffs_binmean',...
'pitch_L_S2S3funcClipped_fourier_coeffs_binmean',...
'dev_L_S2S3funcClipped_fourier_coeffs_binmean',...
...
'stroke_L_S2S3funcClipped_fourier_gof_binmean',...
'pitch_L_S2S3funcClipped_fourier_gof_binmean',...
'dev_L_S2S3funcClipped_fourier_gof_binmean',...
...
'Dstroke_S2S3funcClipped_fourier_coeffs_binmean',...
'Dpitch_S2S3funcClipped_fourier_coeffs_binmean',...
'Ddev_S2S3funcClipped_fourier_coeffs_binmean',...
...
'Dstroke_S2S3funcClipped_fourier_gof_binmean',...
'Dpitch_S2S3funcClipped_fourier_gof_binmean',...
'Ddev_S2S3funcClipped_fourier_gof_binmean',...
...
'strokeMOD_R_S2S3funcClipped_fourier_coeffs_binmean',...
'pitchMOD_R_S2S3funcClipped_fourier_coeffs_binmean',...
'devMOD_R_S2S3funcClipped_fourier_coeffs_binmean',...
...
'strokeMOD_R_S2S3funcClipped_fourier_gof_binmean',...
'pitchMOD_R_S2S3funcClipped_fourier_gof_binmean',...
'devMOD_R_S2S3funcClipped_fourier_gof_binmean',...
...
'strokeMOD_L_S2S3funcClipped_fourier_coeffs_binmean',...
'pitchMOD_L_S2S3funcClipped_fourier_coeffs_binmean',...
'devMOD_L_S2S3funcClipped_fourier_coeffs_binmean',...
...
'strokeMOD_L_S2S3funcClipped_fourier_gof_binmean',...
'pitchMOD_L_S2S3funcClipped_fourier_gof_binmean',...
'devMOD_L_S2S3funcClipped_fourier_gof_binmean',...
...
'DstrokeMOD_S2S3funcClipped_fourier_coeffs_binmean',...
'DpitchMOD_S2S3funcClipped_fourier_coeffs_binmean',...
'DdevMOD_S2S3funcClipped_fourier_coeffs_binmean',...
...
'DstrokeMOD_S2S3funcClipped_fourier_gof_binmean',...
'DpitchMOD_S2S3funcClipped_fourier_gof_binmean',...
'DdevMOD_S2S3funcClipped_fourier_gof_binmean',...
...
'stroke_wb_R_S2S3funcClipped_bins_meanCIstd',...
'stroke_ds_R_S2S3funcClipped_bins_meanCIstd',...
'stroke_us_R_S2S3funcClipped_bins_meanCIstd',...
...
'pitch_wb_R_S2S3funcClipped_bins_meanCIstd',...
'pitch_ds_R_S2S3funcClipped_bins_meanCIstd',...
'pitch_us_R_S2S3funcClipped_bins_meanCIstd',...
...
'dev_wb_R_S2S3funcClipped_bins_meanCIstd',...
'dev_ds_R_S2S3funcClipped_bins_meanCIstd',...
'dev_us_R_S2S3funcClipped_bins_meanCIstd',...
...
'strokeMOD_wb_R_S2S3funcClipped_bins_meanCIstd',...
'strokeMOD_ds_R_S2S3funcClipped_bins_meanCIstd',...
'strokeMOD_us_R_S2S3funcClipped_bins_meanCIstd',...
...
'pitchMOD_wb_R_S2S3funcClipped_bins_meanCIstd',...
'pitchMOD_ds_R_S2S3funcClipped_bins_meanCIstd',...
'pitchMOD_us_R_S2S3funcClipped_bins_meanCIstd',...
...
'devMOD_wb_R_S2S3funcClipped_bins_meanCIstd',...
'devMOD_ds_R_S2S3funcClipped_bins_meanCIstd',...
'devMOD_us_R_S2S3funcClipped_bins_meanCIstd',...
...
'stroke_wb_L_S2S3funcClipped_bins_meanCIstd',...
'stroke_ds_L_S2S3funcClipped_bins_meanCIstd',...
'stroke_us_L_S2S3funcClipped_bins_meanCIstd',...
...
'pitch_wb_L_S2S3funcClipped_bins_meanCIstd',...
'pitch_ds_L_S2S3funcClipped_bins_meanCIstd',...
'pitch_us_L_S2S3funcClipped_bins_meanCIstd',...
...
'dev_wb_L_S2S3funcClipped_bins_meanCIstd',...
'dev_ds_L_S2S3funcClipped_bins_meanCIstd',...
'dev_us_L_S2S3funcClipped_bins_meanCIstd',...
...
'strokeMOD_wb_L_S2S3funcClipped_bins_meanCIstd',...
'strokeMOD_ds_L_S2S3funcClipped_bins_meanCIstd',...
'strokeMOD_us_L_S2S3funcClipped_bins_meanCIstd',...
...
'pitchMOD_wb_L_S2S3funcClipped_bins_meanCIstd',...
'pitchMOD_ds_L_S2S3funcClipped_bins_meanCIstd',...
'pitchMOD_us_L_S2S3funcClipped_bins_meanCIstd',...
...
'devMOD_wb_L_S2S3funcClipped_bins_meanCIstd',...
'devMOD_ds_L_S2S3funcClipped_bins_meanCIstd',...
'devMOD_us_L_S2S3funcClipped_bins_meanCIstd',...
...
'DstrokeMOD_wb_S2S3funcClipped_bins_meanCIstd',...
'DstrokeMOD_ds_S2S3funcClipped_bins_meanCIstd',...
'DstrokeMOD_us_S2S3funcClipped_bins_meanCIstd',...
...
'DpitchMOD_wb_S2S3funcClipped_bins_meanCIstd',...
'DpitchMOD_ds_S2S3funcClipped_bins_meanCIstd',...
'DpitchMOD_us_S2S3funcClipped_bins_meanCIstd',...
...
'DdevMOD_wb_S2S3funcClipped_bins_meanCIstd',...
'DdevMOD_ds_S2S3funcClipped_bins_meanCIstd',...
'DdevMOD_us_S2S3funcClipped_bins_meanCIstd',...
...
'vel_S2S3funcClipped',...
'slip_S2S3funcClipped',...
'pitch_S2S3funcClipped',...
'roll_S2S3funcClipped',...
'Fsp_pitch_S2S3funcClipped',...
'Fsp_roll_S2S3funcClipped',...
...
'dt_ds_S2S3funcClipped',...
'dt_us_S2S3funcClipped',...
'f_wb_S2S3funcClipped',...
'Rds_S2S3funcClipped',...
...
'vel_S2S3funcClipped_meanCIstd',...
'slip_S2S3funcClipped_meanCIstd',...
'pitch_S2S3funcClipped_meanCIstd',...
'roll_S2S3funcClipped_meanCIstd',...
'Fsp_pitch_S2S3funcClipped_meanCIstd',...
'Fsp_roll_S2S3funcClipped_meanCIstd',...
...
'dt_ds_S2S3funcClipped_meanCIstd',...
'dt_us_S2S3funcClipped_meanCIstd',...
'f_wb_S2S3funcClipped_meanCIstd',...
'Rds_S2S3funcClipped_meanCIstd',...
...
'velMOD_S2S3funcClipped_meanCIstd',...
'velMOD_S2S3funcClipped',...
...
'slipMOD_S2S3funcClipped_meanCIstd',...
'slipMOD_S2S3funcClipped',...
...
'pitchMOD_S2S3funcClipped_meanCIstd',...
'pitchMOD_S2S3funcClipped',...
...
'rollMOD_S2S3funcClipped_meanCIstd',...
'rollMOD_S2S3funcClipped',...
...
'Fsp_pitchMOD_S2S3funcClipped_meanCIstd',...
'Fsp_pitchMOD_S2S3funcClipped',...
...
'Fsp_rollMOD_S2S3funcClipped_meanCIstd',...
'Fsp_rollMOD_S2S3funcClipped',...
...
'freqMOD_wb_S2S3funcClipped_meanCIstd',...
'freqMOD_wb_S2S3funcClipped',...
...
'strokeMOD_wb_L_S2S3funcClipped_bins',...
'strokeMOD_wb_R_S2S3funcClipped_bins',...
'strokeMOD_ds_L_S2S3funcClipped_bins',...
'strokeMOD_ds_R_S2S3funcClipped_bins',...
'strokeMOD_us_L_S2S3funcClipped_bins',...
'strokeMOD_us_R_S2S3funcClipped_bins',...
...
'pitchMOD_wb_L_S2S3funcClipped_bins',...
'pitchMOD_wb_R_S2S3funcClipped_bins',...
'pitchMOD_ds_L_S2S3funcClipped_bins',...
'pitchMOD_ds_R_S2S3funcClipped_bins',...
'pitchMOD_us_L_S2S3funcClipped_bins',...
'pitchMOD_us_R_S2S3funcClipped_bins',...
...
'devMOD_wb_L_S2S3funcClipped_bins',...
'devMOD_wb_R_S2S3funcClipped_bins',...
'devMOD_ds_L_S2S3funcClipped_bins',...
'devMOD_ds_R_S2S3funcClipped_bins',...
'devMOD_us_L_S2S3funcClipped_bins',...
'devMOD_us_R_S2S3funcClipped_bins',...
...
'DstrokeMOD_wb_S2S3funcClipped_bins',...
'DstrokeMOD_ds_S2S3funcClipped_bins',...
'DstrokeMOD_us_S2S3funcClipped_bins',...
...
'DpitchMOD_wb_S2S3funcClipped_bins',...
'DpitchMOD_ds_S2S3funcClipped_bins',...
'DpitchMOD_us_S2S3funcClipped_bins',...
...
'DdevMOD_wb_S2S3funcClipped_bins',...
'DdevMOD_ds_S2S3funcClipped_bins',...
'DdevMOD_us_S2S3funcClipped_bins',...
...
't_wb_L_S2S3funcClipped',...
't_wb_R_S2S3funcClipped',...
'stroke_wb_L_S2S3funcClipped',...
'stroke_wb_R_S2S3funcClipped',...
'pitch_wb_L_S2S3funcClipped',...
'pitch_wb_R_S2S3funcClipped',...
'dev_wb_L_S2S3funcClipped',...
'dev_wb_R_S2S3funcClipped',...
'aoa_wb_L_S2S3funcClipped',...
'aoa_wb_R_S2S3funcClipped',...
'U_wb_L_S2S3funcClipped',...
'U_wb_R_S2S3funcClipped',...
...
't_ds_L_S2S3funcClipped',...
't_ds_R_S2S3funcClipped',...
'stroke_ds_L_S2S3funcClipped',...
'stroke_ds_R_S2S3funcClipped',...
'pitch_ds_L_S2S3funcClipped',...
'pitch_ds_R_S2S3funcClipped',...
'dev_ds_L_S2S3funcClipped',...
'dev_ds_R_S2S3funcClipped',...
'aoa_ds_L_S2S3funcClipped',...
'aoa_ds_R_S2S3funcClipped',...
'U_ds_L_S2S3funcClipped',...
'U_ds_R_S2S3funcClipped',...
...
't_us_L_S2S3funcClipped',...
't_us_R_S2S3funcClipped',...
'stroke_us_L_S2S3funcClipped',...
'stroke_us_R_S2S3funcClipped',...
'pitch_us_L_S2S3funcClipped',...
'pitch_us_R_S2S3funcClipped',...
'dev_us_L_S2S3funcClipped',...
'dev_us_R_S2S3funcClipped',...
'aoa_us_L_S2S3funcClipped',...
'aoa_us_R_S2S3funcClipped',...
'U_us_L_S2S3funcClipped',...
'U_us_R_S2S3funcClipped',...
...
't_wb_S2S3funcClipped_bins',...
'stroke_wb_L_S2S3funcClipped_bins',...
'stroke_wb_R_S2S3funcClipped_bins',...
'pitch_wb_L_S2S3funcClipped_bins',...
'pitch_wb_R_S2S3funcClipped_bins',...
'dev_wb_L_S2S3funcClipped_bins',...
'dev_wb_R_S2S3funcClipped_bins',...
'aoa_wb_L_S2S3funcClipped_bins',...
'aoa_wb_R_S2S3funcClipped_bins',...
'U_wb_L_S2S3funcClipped_bins',...
'U_wb_R_S2S3funcClipped_bins',...
'Dstroke_wb_S2S3funcClipped_bins',...
'Dpitch_wb_S2S3funcClipped_bins',...
'Ddev_wb_S2S3funcClipped_bins',...
'Daoa_wb_S2S3funcClipped_bins',...
'DU_wb_S2S3funcClipped_bins',...
...
't_ds_S2S3funcClipped_bins',...
'stroke_ds_L_S2S3funcClipped_bins',...
'stroke_ds_R_S2S3funcClipped_bins',...
'pitch_ds_L_S2S3funcClipped_bins',...
'pitch_ds_R_S2S3funcClipped_bins',...
'dev_ds_L_S2S3funcClipped_bins',...
'dev_ds_R_S2S3funcClipped_bins',...
'aoa_ds_L_S2S3funcClipped_bins',...
'aoa_ds_R_S2S3funcClipped_bins',...
'U_ds_L_S2S3funcClipped_bins',...
'U_ds_R_S2S3funcClipped_bins',...
'Dstroke_ds_S2S3funcClipped_bins',...
'Dpitch_ds_S2S3funcClipped_bins',...
'Ddev_ds_S2S3funcClipped_bins',...
'Daoa_ds_S2S3funcClipped_bins',...
'DU_ds_S2S3funcClipped_bins',...
...
't_us_S2S3funcClipped_bins',...
'stroke_us_L_S2S3funcClipped_bins',...
'stroke_us_R_S2S3funcClipped_bins',...
'pitch_us_L_S2S3funcClipped_bins',...
'pitch_us_R_S2S3funcClipped_bins',...
'dev_us_L_S2S3funcClipped_bins',...
'dev_us_R_S2S3funcClipped_bins',...
'aoa_us_L_S2S3funcClipped_bins',...
'aoa_us_R_S2S3funcClipped_bins',...
'U_us_L_S2S3funcClipped_bins',...
'U_us_R_S2S3funcClipped_bins',...
'Dstroke_us_S2S3funcClipped_bins',...
'Dpitch_us_S2S3funcClipped_bins',...
'Ddev_us_S2S3funcClipped_bins',...
'Daoa_us_S2S3funcClipped_bins',...
'DU_us_S2S3funcClipped_bins');

end

