% calc wb MOD M_axis2DOWN

n_now=0;

%% variables
% wbMOD
freqMOD_wb_TorqueAxis2DOWN = [];

strokeMOD_wb_L_TorqueAxis2DOWN_bins = [];
strokeMOD_wb_R_TorqueAxis2DOWN_bins = [];
strokeMOD_ds_L_TorqueAxis2DOWN_bins = [];
strokeMOD_ds_R_TorqueAxis2DOWN_bins = [];
strokeMOD_us_L_TorqueAxis2DOWN_bins = [];
strokeMOD_us_R_TorqueAxis2DOWN_bins = [];

pitchMOD_wb_L_TorqueAxis2DOWN_bins = [];
pitchMOD_wb_R_TorqueAxis2DOWN_bins = [];
pitchMOD_ds_L_TorqueAxis2DOWN_bins = [];
pitchMOD_ds_R_TorqueAxis2DOWN_bins = [];
pitchMOD_us_L_TorqueAxis2DOWN_bins = [];
pitchMOD_us_R_TorqueAxis2DOWN_bins = [];

devMOD_wb_L_TorqueAxis2DOWN_bins = [];
devMOD_wb_R_TorqueAxis2DOWN_bins = [];
devMOD_ds_L_TorqueAxis2DOWN_bins = [];
devMOD_ds_R_TorqueAxis2DOWN_bins = [];
devMOD_us_L_TorqueAxis2DOWN_bins = [];
devMOD_us_R_TorqueAxis2DOWN_bins = [];

DstrokeMOD_wb_TorqueAxis2DOWN_bins = [];
DstrokeMOD_ds_TorqueAxis2DOWN_bins = [];
DstrokeMOD_us_TorqueAxis2DOWN_bins = [];

DpitchMOD_wb_TorqueAxis2DOWN_bins = [];
DpitchMOD_ds_TorqueAxis2DOWN_bins = [];
DpitchMOD_us_TorqueAxis2DOWN_bins = [];

DdevMOD_wb_TorqueAxis2DOWN_bins = [];
DdevMOD_ds_TorqueAxis2DOWN_bins = [];
DdevMOD_us_TorqueAxis2DOWN_bins = [];

% seq&wb
seq_nr_TorqueAxis2DOWN = [];
wb_nr_TorqueAxis2DOWN = [];

% body kin
V_TorqueAxis2DOWN = [];
pitch_global_TorqueAxis2DOWN = [];
F_TorqueAxis2DOWN = [];

Mroll_accel_TorqueAxis2DOWN = [];
Mpitch_accel_TorqueAxis2DOWN = [];
Myaw_accel_TorqueAxis2DOWN = [];
M_axis2normal_accel_TorqueAxis2DOWN = [];
M_axis2_accel_TorqueAxis2DOWN = [];

Mroll_damp_TorqueAxis2DOWN = [];
Mpitch_damp_TorqueAxis2DOWN = [];
Myaw_damp_TorqueAxis2DOWN = [];
M_axis2normal_damp_TorqueAxis2DOWN = [];
M_axis2_damp_TorqueAxis2DOWN = [];

Mroll_TorqueAxis2DOWN = [];
Mpitch_TorqueAxis2DOWN = [];
Myaw_TorqueAxis2DOWN = [];
M_axis2normal_TorqueAxis2DOWN = [];
M_axis2_TorqueAxis2DOWN = [];

rollaccel_TorqueAxis2DOWN = [];
pitchaccel_TorqueAxis2DOWN = [];
yawaccel_TorqueAxis2DOWN = [];
rotRaccel_TorqueAxis2DOWN = [];

rollvel_TorqueAxis2DOWN = [];
pitchvel_TorqueAxis2DOWN = [];
yawvel_TorqueAxis2DOWN = [];
rotRvel_TorqueAxis2DOWN = [];

% wingbeat kin
dt_wb_TorqueAxis2DOWN = [];
dt_ds_TorqueAxis2DOWN = [];
dt_us_TorqueAxis2DOWN = [];
f_wb_TorqueAxis2DOWN = [];
Rds_TorqueAxis2DOWN = [];

t_wb_L_TorqueAxis2DOWN = [];
t_wb_R_TorqueAxis2DOWN = [];
stroke_wb_L_TorqueAxis2DOWN = [];
stroke_wb_R_TorqueAxis2DOWN = [];
pitch_wb_L_TorqueAxis2DOWN = [];
pitch_wb_R_TorqueAxis2DOWN = [];
dev_wb_L_TorqueAxis2DOWN = [];
dev_wb_R_TorqueAxis2DOWN = [];
aoa_wb_L_TorqueAxis2DOWN = [];
aoa_wb_R_TorqueAxis2DOWN = [];
U_wb_L_TorqueAxis2DOWN = [];
U_wb_R_TorqueAxis2DOWN = [];
Dstroke_wb_TorqueAxis2DOWN = [];
Dpitch_wb_TorqueAxis2DOWN = [];
Ddev_wb_TorqueAxis2DOWN = [];
Daoa_wb_TorqueAxis2DOWN = [];
DU_wb_TorqueAxis2DOWN = [];

t_ds_L_TorqueAxis2DOWN = [];
t_ds_R_TorqueAxis2DOWN = [];
stroke_ds_L_TorqueAxis2DOWN = [];
stroke_ds_R_TorqueAxis2DOWN = [];
pitch_ds_L_TorqueAxis2DOWN = [];
pitch_ds_R_TorqueAxis2DOWN = [];
dev_ds_L_TorqueAxis2DOWN = [];
dev_ds_R_TorqueAxis2DOWN = [];
aoa_ds_L_TorqueAxis2DOWN = [];
aoa_ds_R_TorqueAxis2DOWN = [];
U_ds_L_TorqueAxis2DOWN = [];
U_ds_R_TorqueAxis2DOWN = [];
Dstroke_ds_TorqueAxis2DOWN = [];
Dpitch_ds_TorqueAxis2DOWN = [];
Ddev_ds_TorqueAxis2DOWN = [];
Daoa_ds_TorqueAxis2DOWN = [];
DU_ds_TorqueAxis2DOWN = [];

t_us_L_TorqueAxis2DOWN = [];
t_us_R_TorqueAxis2DOWN = [];
stroke_us_L_TorqueAxis2DOWN = [];
stroke_us_R_TorqueAxis2DOWN = [];
pitch_us_L_TorqueAxis2DOWN = [];
pitch_us_R_TorqueAxis2DOWN = [];
dev_us_L_TorqueAxis2DOWN = [];
dev_us_R_TorqueAxis2DOWN = [];
aoa_us_L_TorqueAxis2DOWN = [];
aoa_us_R_TorqueAxis2DOWN = [];
U_us_L_TorqueAxis2DOWN = [];
U_us_R_TorqueAxis2DOWN = [];
Dstroke_us_TorqueAxis2DOWN = [];
Dpitch_us_TorqueAxis2DOWN = [];
Ddev_us_TorqueAxis2DOWN = [];
Daoa_us_TorqueAxis2DOWN = [];
DU_us_TorqueAxis2DOWN = [];

t_wb_TorqueAxis2DOWN_bins = [];
stroke_wb_L_TorqueAxis2DOWN_bins = [];
stroke_wb_R_TorqueAxis2DOWN_bins = [];
pitch_wb_L_TorqueAxis2DOWN_bins = [];
pitch_wb_R_TorqueAxis2DOWN_bins = [];
dev_wb_L_TorqueAxis2DOWN_bins = [];
dev_wb_R_TorqueAxis2DOWN_bins = [];
aoa_wb_L_TorqueAxis2DOWN_bins = [];
aoa_wb_R_TorqueAxis2DOWN_bins = [];
U_wb_L_TorqueAxis2DOWN_bins = [];
U_wb_R_TorqueAxis2DOWN_bins = [];
Dstroke_wb_TorqueAxis2DOWN_bins = [];
Dpitch_wb_TorqueAxis2DOWN_bins = [];
Ddev_wb_TorqueAxis2DOWN_bins = [];
Daoa_wb_TorqueAxis2DOWN_bins = [];
DU_wb_TorqueAxis2DOWN_bins = [];

t_ds_TorqueAxis2DOWN_bins = [];
stroke_ds_L_TorqueAxis2DOWN_bins = [];
stroke_ds_R_TorqueAxis2DOWN_bins = [];
pitch_ds_L_TorqueAxis2DOWN_bins = [];
pitch_ds_R_TorqueAxis2DOWN_bins = [];
dev_ds_L_TorqueAxis2DOWN_bins = [];
dev_ds_R_TorqueAxis2DOWN_bins = [];
aoa_ds_L_TorqueAxis2DOWN_bins = [];
aoa_ds_R_TorqueAxis2DOWN_bins = [];
U_ds_L_TorqueAxis2DOWN_bins = [];
U_ds_R_TorqueAxis2DOWN_bins = [];
Dstroke_ds_TorqueAxis2DOWN_bins = [];
Dpitch_ds_TorqueAxis2DOWN_bins = [];
Ddev_ds_TorqueAxis2DOWN_bins = [];
Daoa_ds_TorqueAxis2DOWN_bins = [];
DU_ds_TorqueAxis2DOWN_bins = [];

t_us_TorqueAxis2DOWN_bins = [];
stroke_us_L_TorqueAxis2DOWN_bins = [];
stroke_us_R_TorqueAxis2DOWN_bins = [];
pitch_us_L_TorqueAxis2DOWN_bins = [];
pitch_us_R_TorqueAxis2DOWN_bins = [];
dev_us_L_TorqueAxis2DOWN_bins = [];
dev_us_R_TorqueAxis2DOWN_bins = [];
aoa_us_L_TorqueAxis2DOWN_bins = [];
aoa_us_R_TorqueAxis2DOWN_bins = [];
U_us_L_TorqueAxis2DOWN_bins = [];
U_us_R_TorqueAxis2DOWN_bins = [];
Dstroke_us_TorqueAxis2DOWN_bins = [];
Dpitch_us_TorqueAxis2DOWN_bins = [];
Ddev_us_TorqueAxis2DOWN_bins = [];
Daoa_us_TorqueAxis2DOWN_bins = [];
DU_us_TorqueAxis2DOWN_bins = [];

for wb = 1:size(wb_nr,1)
    counter = size(wb_nr,1) -wb
        
        if M_axis2_mean_wb(wb) < -M_axis2_limit_mod
            
            % current wb
            seq_nr_now = seq_nr(wb);
            wb_nr_now = wb_nr(wb);

            % body kin
            V_now = V_mean_wb(wb);
            pitch_global_now = pitch_global_mean_wb(wb);
            F_mean_wb_now = F_mean_wb(wb);

            Mroll_mean_wb_accel_now = Mroll_mean_wb_accel(wb);
            Mpitch_mean_wb_accel_now = Mpitch_mean_wb_accel(wb);
            Myaw_mean_wb_accel_now = Myaw_mean_wb_accel(wb);
            M_axis2normal_mean_wb_accel_now = M_axis2normal_mean_wb_accel(wb);
            M_axis2_mean_wb_accel_now = M_axis2_mean_wb_accel(wb);

            Mroll_mean_wb_damp_now = Mroll_mean_wb_damp(wb);
            Mpitch_mean_wb_damp_now = Mpitch_mean_wb_damp(wb);
            Myaw_mean_wb_damp_now = Myaw_mean_wb_damp(wb);
            M_axis2normal_mean_wb_damp_now = M_axis2normal_mean_wb_damp(wb);
            M_axis2_mean_wb_damp_now = M_axis2_mean_wb_damp(wb);

            Mroll_mean_wb_now = Mroll_mean_wb(wb);
            Mpitch_mean_wb_now = Mpitch_mean_wb(wb);
            Myaw_mean_wb_now = Myaw_mean_wb(wb);
            M_axis2normal_mean_wb_now = M_axis2normal_mean_wb(wb);
            M_axis2_mean_wb_now = M_axis2_mean_wb(wb);

            rollaccel_mean_wb_now = roll_dot_dot_mean_wb(wb);
            pitchaccel_mean_wb_now = pitch_dot_dot_mean_wb(wb);
            yawaccel_mean_wb_now = yaw_dot_dot_mean_wb(wb);
            rotRaccel_mean_wb_now = rot_dot_dot_R_mean_wb(wb);

            rollvel_mean_wb_now = roll_dot_mean_wb(wb);
            pitchvel_mean_wb_now = pitch_dot_mean_wb(wb);
            yawvel_mean_wb_now = yaw_dot_mean_wb(wb);
            rotRvel_mean_wb_now = rot_dot_R_mean_wb(wb);

            % wingbeat kin
            dt_ds_now = ([dt_ds_L(wb),dt_ds_R(wb)]);
            dt_us_now = ([dt_us_L(wb),dt_us_R(wb)]);
            f_wb_now = ([f_wb_L(wb),f_wb_R(wb)]);
            Rds_now = dt_ds_now ./ (dt_ds_now + dt_us_now);
            
            stroke_wb_L_now = stroke_wb_L(:,wb);
            stroke_wb_R_now = stroke_wb_R(:,wb);
            stroke_ds_L_now = stroke_ds_L(:,wb);
            stroke_ds_R_now = stroke_ds_R(:,wb);
            stroke_us_L_now = stroke_us_L(:,wb);
            stroke_us_R_now = stroke_us_R(:,wb);
            
            pitch_wb_L_now = pitch_wb_L(:,wb);
            pitch_wb_R_now = pitch_wb_R(:,wb);
            pitch_ds_L_now = pitch_ds_L(:,wb);
            pitch_ds_R_now = pitch_ds_R(:,wb);
            pitch_us_L_now = pitch_us_L(:,wb);
            pitch_us_R_now = pitch_us_R(:,wb);
            
            dev_wb_L_now = dev_wb_L(:,wb);
            dev_wb_R_now = dev_wb_R(:,wb);
            dev_ds_L_now = dev_ds_L(:,wb);
            dev_ds_R_now = dev_ds_R(:,wb);
            dev_us_L_now = dev_us_L(:,wb);
            dev_us_R_now = dev_us_R(:,wb);
            
            U_wb_L_now = U_wb_L(:,wb);
            U_wb_R_now = U_wb_R(:,wb);
            U_ds_L_now = U_ds_L(:,wb);
            U_ds_R_now = U_ds_R(:,wb);
            U_us_L_now = U_us_L(:,wb);
            U_us_R_now = U_us_R(:,wb);
            
            aoa_wb_L_now = aoa_wb_L(:,wb);
            aoa_wb_R_now = aoa_wb_R(:,wb);
            aoa_ds_L_now = aoa_ds_L(:,wb);
            aoa_ds_R_now = aoa_ds_R(:,wb);
            aoa_us_L_now = aoa_us_L(:,wb);
            aoa_us_R_now = aoa_us_R(:,wb);
            
            t_wb_L_now = t_wb_L(:,wb);
            t_wb_R_now = t_wb_R(:,wb);
            t_ds_L_now = t_ds_L(:,wb);
            t_ds_R_now = t_ds_R(:,wb);
            t_us_L_now = t_us_L(:,wb);
            t_us_R_now = t_us_R(:,wb);

            % interpolated data
            stroke_wb_L_interp = stroke_wb_L_bins(:,wb);
            stroke_wb_R_interp = stroke_wb_R_bins(:,wb);
            stroke_ds_L_interp = stroke_ds_L_bins(:,wb);
            stroke_ds_R_interp = stroke_ds_R_bins(:,wb);
            stroke_us_L_interp = stroke_us_L_bins(:,wb);
            stroke_us_R_interp = stroke_us_R_bins(:,wb);
            
            pitch_wb_L_interp = pitch_wb_L_bins(:,wb);
            pitch_wb_R_interp = pitch_wb_R_bins(:,wb);
            pitch_ds_L_interp = pitch_ds_L_bins(:,wb);
            pitch_ds_R_interp = pitch_ds_R_bins(:,wb);
            pitch_us_L_interp = pitch_us_L_bins(:,wb);
            pitch_us_R_interp = pitch_us_R_bins(:,wb);
            
            dev_wb_L_interp = dev_wb_L_bins(:,wb);
            dev_wb_R_interp = dev_wb_R_bins(:,wb);
            dev_ds_L_interp = dev_ds_L_bins(:,wb);
            dev_ds_R_interp = dev_ds_R_bins(:,wb);
            dev_us_L_interp = dev_us_L_bins(:,wb);
            dev_us_R_interp = dev_us_R_bins(:,wb);
            
            U_wb_L_interp = U_wb_L_bins(:,wb);
            U_wb_R_interp = U_wb_R_bins(:,wb);
            U_ds_L_interp = U_ds_L_bins(:,wb);
            U_ds_R_interp = U_ds_R_bins(:,wb);
            U_us_L_interp = U_us_L_bins(:,wb);
            U_us_R_interp = U_us_R_bins(:,wb);
            
            aoa_wb_L_interp = aoa_wb_L_bins(:,wb);
            aoa_wb_R_interp = aoa_wb_R_bins(:,wb);
            aoa_ds_L_interp = aoa_ds_L_bins(:,wb);
            aoa_ds_R_interp = aoa_ds_R_bins(:,wb);
            aoa_us_L_interp = aoa_us_L_bins(:,wb);
            aoa_us_R_interp = aoa_us_R_bins(:,wb);

            Dstroke_wb_interp = Dstroke_wb_bins(:,wb);
            Dstroke_ds_interp = Dstroke_ds_bins(:,wb);
            Dstroke_us_interp = Dstroke_us_bins(:,wb);
            
            Dpitch_wb_interp = Dpitch_wb_bins(:,wb);
            Dpitch_ds_interp = Dpitch_ds_bins(:,wb);
            Dpitch_us_interp = Dpitch_us_bins(:,wb);
            
            Ddev_wb_interp = Ddev_wb_bins(:,wb);
            Ddev_ds_interp = Ddev_ds_bins(:,wb);
            Ddev_us_interp = Ddev_us_bins(:,wb);
            
            DU_wb_interp = DU_wb_bins(:,wb);
            DU_ds_interp = DU_ds_bins(:,wb);
            DU_us_interp = DU_us_bins(:,wb);
            
            Daoa_wb_interp = Daoa_wb_bins(:,wb);
            Daoa_ds_interp = Daoa_ds_bins(:,wb);
            Daoa_us_interp = Daoa_us_bins(:,wb);
            
            % calc wingbeat modifications
            freqMOD_wb_now = (nanmean(f_wb_now) - f_wb_steady) / M_axis2_mean_wb_now * M_axis2_norm;
            
            strokeMOD_wb_L_now = (stroke_wb_L_interp - stroke_wb_steady) / M_axis2_mean_wb_now * M_axis2_norm;
            strokeMOD_wb_R_now = (stroke_wb_R_interp - stroke_wb_steady) / M_axis2_mean_wb_now * M_axis2_norm;
            strokeMOD_ds_L_now = (stroke_ds_L_interp - stroke_ds_steady) / M_axis2_mean_wb_now * M_axis2_norm;
            strokeMOD_ds_R_now = (stroke_ds_R_interp - stroke_ds_steady) / M_axis2_mean_wb_now * M_axis2_norm;
            strokeMOD_us_L_now = (stroke_us_L_interp - stroke_us_steady) / M_axis2_mean_wb_now * M_axis2_norm;
            strokeMOD_us_R_now = (stroke_us_R_interp - stroke_us_steady) / M_axis2_mean_wb_now * M_axis2_norm;
            
            pitchMOD_wb_L_now = (pitch_wb_L_interp - pitch_wb_steady) / M_axis2_mean_wb_now * M_axis2_norm;
            pitchMOD_wb_R_now = (pitch_wb_R_interp - pitch_wb_steady) / M_axis2_mean_wb_now * M_axis2_norm;
            pitchMOD_ds_L_now = (pitch_ds_L_interp - pitch_ds_steady) / M_axis2_mean_wb_now * M_axis2_norm;
            pitchMOD_ds_R_now = (pitch_ds_R_interp - pitch_ds_steady) / M_axis2_mean_wb_now * M_axis2_norm;
            pitchMOD_us_L_now = (pitch_us_L_interp - pitch_us_steady) / M_axis2_mean_wb_now * M_axis2_norm;
            pitchMOD_us_R_now = (pitch_us_R_interp - pitch_us_steady) / M_axis2_mean_wb_now * M_axis2_norm;
            
            devMOD_wb_L_now = (dev_wb_L_interp - dev_wb_steady) / M_axis2_mean_wb_now * M_axis2_norm;
            devMOD_wb_R_now = (dev_wb_R_interp - dev_wb_steady) / M_axis2_mean_wb_now * M_axis2_norm;
            devMOD_ds_L_now = (dev_ds_L_interp - dev_ds_steady) / M_axis2_mean_wb_now * M_axis2_norm;
            devMOD_ds_R_now = (dev_ds_R_interp - dev_ds_steady) / M_axis2_mean_wb_now * M_axis2_norm;
            devMOD_us_L_now = (dev_us_L_interp - dev_us_steady) / M_axis2_mean_wb_now * M_axis2_norm;
            devMOD_us_R_now = (dev_us_R_interp - dev_us_steady) / M_axis2_mean_wb_now * M_axis2_norm;
            
            DstrokeMOD_wb_now = Dstroke_wb_interp / M_axis2_mean_wb_now * M_axis2_norm;
            DstrokeMOD_ds_now = Dstroke_ds_interp / M_axis2_mean_wb_now * M_axis2_norm;
            DstrokeMOD_us_now = Dstroke_us_interp / M_axis2_mean_wb_now * M_axis2_norm;

            DpitchMOD_wb_now = Dpitch_wb_interp / M_axis2_mean_wb_now * M_axis2_norm;
            DpitchMOD_ds_now = Dpitch_ds_interp / M_axis2_mean_wb_now * M_axis2_norm;
            DpitchMOD_us_now = Dpitch_us_interp / M_axis2_mean_wb_now * M_axis2_norm;

            DdevMOD_wb_now = Ddev_wb_interp / M_axis2_mean_wb_now * M_axis2_norm;
            DdevMOD_ds_now = Ddev_ds_interp / M_axis2_mean_wb_now * M_axis2_norm;
            DdevMOD_us_now = Ddev_us_interp / M_axis2_mean_wb_now * M_axis2_norm;

            %% store data
            n_now=n_now+1;

            seq_nr_TorqueAxis2DOWN(n_now,1) = seq_nr_now;
            wb_nr_TorqueAxis2DOWN(n_now,1) = wb_nr_now;
            
            % body kin
            V_TorqueAxis2DOWN(n_now,1) = V_now;
            pitch_global_TorqueAxis2DOWN(n_now,1) = pitch_global_now;
            F_TorqueAxis2DOWN(n_now,1) = F_mean_wb_now;

            Mroll_accel_TorqueAxis2DOWN(n_now,1) = Mroll_mean_wb_accel_now;
            Mpitch_accel_TorqueAxis2DOWN(n_now,1) = Mpitch_mean_wb_accel_now;
            Myaw_accel_TorqueAxis2DOWN(n_now,1) = Myaw_mean_wb_accel_now;
            M_axis2normal_accel_TorqueAxis2DOWN(n_now,1) = M_axis2normal_mean_wb_accel_now;
            M_axis2_accel_TorqueAxis2DOWN(n_now,1) = M_axis2_mean_wb_accel_now;

            Mroll_damp_TorqueAxis2DOWN(n_now,1) = Mroll_mean_wb_damp_now;
            Mpitch_damp_TorqueAxis2DOWN(n_now,1) = Mpitch_mean_wb_damp_now;
            Myaw_damp_TorqueAxis2DOWN(n_now,1) = Myaw_mean_wb_damp_now;
            M_axis2normal_damp_TorqueAxis2DOWN(n_now,1) = M_axis2normal_mean_wb_damp_now;
            M_axis2_damp_TorqueAxis2DOWN(n_now,1) = M_axis2_mean_wb_damp_now;

            Mroll_TorqueAxis2DOWN(n_now,1) = Mroll_mean_wb_now;
            Mpitch_TorqueAxis2DOWN(n_now,1) = Mpitch_mean_wb_now;
            Myaw_TorqueAxis2DOWN(n_now,1) = Myaw_mean_wb_now;
            M_axis2normal_TorqueAxis2DOWN(n_now,1) = M_axis2normal_mean_wb_now;
            M_axis2_TorqueAxis2DOWN(n_now,1) = M_axis2_mean_wb_now;

            rollaccel_TorqueAxis2DOWN(n_now,1) = rollaccel_mean_wb_now;
            pitchaccel_TorqueAxis2DOWN(n_now,1) = pitchaccel_mean_wb_now;
            yawaccel_TorqueAxis2DOWN(n_now,1) = yawaccel_mean_wb_now;
            rotRaccel_TorqueAxis2DOWN(n_now,1) = rotRaccel_mean_wb_now;

            rollvel_TorqueAxis2DOWN(n_now,1) = rollvel_mean_wb_now;
            pitchvel_TorqueAxis2DOWN(n_now,1) = pitchvel_mean_wb_now;
            yawvel_TorqueAxis2DOWN(n_now,1) = yawvel_mean_wb_now;
            rotRvel_TorqueAxis2DOWN(n_now,1) = rotRvel_mean_wb_now;
            
            % wingbeat kin
            dt_ds_TorqueAxis2DOWN(n_now,1) = nanmean(dt_ds_now);
            dt_us_TorqueAxis2DOWN(n_now,1) = nanmean(dt_us_now);
            f_wb_TorqueAxis2DOWN(n_now,1) = nanmean(f_wb_now);
            Rds_TorqueAxis2DOWN(n_now,1) = nanmean(Rds_now);

            t_wb_L_TorqueAxis2DOWN(1:length(t_wb_L_now),n_now) = t_wb_L_now;
            t_wb_R_TorqueAxis2DOWN(1:length(t_wb_R_now),n_now) = t_wb_R_now;
            stroke_wb_L_TorqueAxis2DOWN(1:length(t_wb_L_now),n_now) = stroke_wb_L_now;
            stroke_wb_R_TorqueAxis2DOWN(1:length(t_wb_R_now),n_now) = stroke_wb_R_now;
            pitch_wb_L_TorqueAxis2DOWN(1:length(t_wb_L_now),n_now) = pitch_wb_L_now;
            pitch_wb_R_TorqueAxis2DOWN(1:length(t_wb_R_now),n_now) = pitch_wb_R_now;
            dev_wb_L_TorqueAxis2DOWN(1:length(t_wb_L_now),n_now) = dev_wb_L_now;
            dev_wb_R_TorqueAxis2DOWN(1:length(t_wb_R_now),n_now) = dev_wb_R_now;
            aoa_wb_L_TorqueAxis2DOWN(1:length(t_wb_L_now),n_now) = aoa_wb_L_now;
            aoa_wb_R_TorqueAxis2DOWN(1:length(t_wb_R_now),n_now) = aoa_wb_R_now;
            U_wb_L_TorqueAxis2DOWN(1:length(t_wb_L_now),n_now) = U_wb_L_now;
            U_wb_R_TorqueAxis2DOWN(1:length(t_wb_R_now),n_now) = U_wb_R_now;
            
            t_ds_L_TorqueAxis2DOWN(1:length(t_ds_L_now),n_now) = t_ds_L_now;
            t_ds_R_TorqueAxis2DOWN(1:length(t_ds_R_now),n_now) = t_ds_R_now;
            stroke_ds_L_TorqueAxis2DOWN(1:length(t_ds_L_now),n_now) = stroke_ds_L_now;
            stroke_ds_R_TorqueAxis2DOWN(1:length(t_ds_R_now),n_now) = stroke_ds_R_now;
            pitch_ds_L_TorqueAxis2DOWN(1:length(t_ds_L_now),n_now) = pitch_ds_L_now;
            pitch_ds_R_TorqueAxis2DOWN(1:length(t_ds_R_now),n_now) = pitch_ds_R_now;
            dev_ds_L_TorqueAxis2DOWN(1:length(t_ds_L_now),n_now) = dev_ds_L_now;
            dev_ds_R_TorqueAxis2DOWN(1:length(t_ds_R_now),n_now) = dev_ds_R_now;
            aoa_ds_L_TorqueAxis2DOWN(1:length(t_ds_L_now),n_now) = aoa_ds_L_now;
            aoa_ds_R_TorqueAxis2DOWN(1:length(t_ds_R_now),n_now) = aoa_ds_R_now;
            U_ds_L_TorqueAxis2DOWN(1:length(t_ds_L_now),n_now) = U_ds_L_now;
            U_ds_R_TorqueAxis2DOWN(1:length(t_ds_R_now),n_now) = U_ds_R_now;
            
            t_us_L_TorqueAxis2DOWN(1:length(t_us_L_now),n_now) = t_us_L_now;
            t_us_R_TorqueAxis2DOWN(1:length(t_us_R_now),n_now) = t_us_R_now;
            stroke_us_L_TorqueAxis2DOWN(1:length(t_us_L_now),n_now) = stroke_us_L_now;
            stroke_us_R_TorqueAxis2DOWN(1:length(t_us_R_now),n_now) = stroke_us_R_now;
            pitch_us_L_TorqueAxis2DOWN(1:length(t_us_L_now),n_now) = pitch_us_L_now;
            pitch_us_R_TorqueAxis2DOWN(1:length(t_us_R_now),n_now) = pitch_us_R_now;
            dev_us_L_TorqueAxis2DOWN(1:length(t_us_L_now),n_now) = dev_us_L_now;
            dev_us_R_TorqueAxis2DOWN(1:length(t_us_R_now),n_now) = dev_us_R_now;
            aoa_us_L_TorqueAxis2DOWN(1:length(t_us_L_now),n_now) = aoa_us_L_now;
            aoa_us_R_TorqueAxis2DOWN(1:length(t_us_R_now),n_now) = aoa_us_R_now;
            U_us_L_TorqueAxis2DOWN(1:length(t_us_L_now),n_now) = U_us_L_now;
            U_us_R_TorqueAxis2DOWN(1:length(t_us_R_now),n_now) = U_us_R_now;
            
            % store interp binned data separate rows
            t_wb_TorqueAxis2DOWN_bins(:,n_now) = t_wb_bin;
            stroke_wb_L_TorqueAxis2DOWN_bins(:,n_now) = stroke_wb_L_interp;
            stroke_wb_R_TorqueAxis2DOWN_bins(:,n_now) = stroke_wb_R_interp;
            pitch_wb_L_TorqueAxis2DOWN_bins(:,n_now) = pitch_wb_L_interp;
            pitch_wb_R_TorqueAxis2DOWN_bins(:,n_now) = pitch_wb_R_interp;
            dev_wb_L_TorqueAxis2DOWN_bins(:,n_now) = dev_wb_L_interp;
            dev_wb_R_TorqueAxis2DOWN_bins(:,n_now) = dev_wb_R_interp;
            aoa_wb_L_TorqueAxis2DOWN_bins(:,n_now) = aoa_wb_L_interp;
            aoa_wb_R_TorqueAxis2DOWN_bins(:,n_now) = aoa_wb_R_interp;
            U_wb_L_TorqueAxis2DOWN_bins(:,n_now) = U_wb_L_interp;
            U_wb_R_TorqueAxis2DOWN_bins(:,n_now) = U_wb_R_interp;
            Dstroke_wb_TorqueAxis2DOWN_bins(:,n_now) = Dstroke_wb_interp;
            Dpitch_wb_TorqueAxis2DOWN_bins(:,n_now) = Dpitch_wb_interp;
            Ddev_wb_TorqueAxis2DOWN_bins(:,n_now) = Ddev_wb_interp;
            Daoa_wb_TorqueAxis2DOWN_bins(:,n_now) = Daoa_wb_interp;
            DU_wb_TorqueAxis2DOWN_bins(:,n_now) = DU_wb_interp;
            
            t_ds_TorqueAxis2DOWN_bins(:,n_now) = t_ds_bin;
            stroke_ds_L_TorqueAxis2DOWN_bins(:,n_now) = stroke_ds_L_interp;
            stroke_ds_R_TorqueAxis2DOWN_bins(:,n_now) = stroke_ds_R_interp;
            pitch_ds_L_TorqueAxis2DOWN_bins(:,n_now) = pitch_ds_L_interp;
            pitch_ds_R_TorqueAxis2DOWN_bins(:,n_now) = pitch_ds_R_interp;
            dev_ds_L_TorqueAxis2DOWN_bins(:,n_now) = dev_ds_L_interp;
            dev_ds_R_TorqueAxis2DOWN_bins(:,n_now) = dev_ds_R_interp;
            aoa_ds_L_TorqueAxis2DOWN_bins(:,n_now) = aoa_ds_L_interp;
            aoa_ds_R_TorqueAxis2DOWN_bins(:,n_now) = aoa_ds_R_interp;
            U_ds_L_TorqueAxis2DOWN_bins(:,n_now) = U_ds_L_interp;
            U_ds_R_TorqueAxis2DOWN_bins(:,n_now) = U_ds_R_interp;
            Dstroke_ds_TorqueAxis2DOWN_bins(:,n_now) = Dstroke_ds_interp;
            Dpitch_ds_TorqueAxis2DOWN_bins(:,n_now) = Dpitch_ds_interp;
            Ddev_ds_TorqueAxis2DOWN_bins(:,n_now) = Ddev_ds_interp;
            Daoa_ds_TorqueAxis2DOWN_bins(:,n_now) = Daoa_ds_interp;
            DU_ds_TorqueAxis2DOWN_bins(:,n_now) = DU_ds_interp;
            
            t_us_TorqueAxis2DOWN_bins(:,n_now) = t_us_bin;
            stroke_us_L_TorqueAxis2DOWN_bins(:,n_now) = stroke_us_L_interp;
            stroke_us_R_TorqueAxis2DOWN_bins(:,n_now) = stroke_us_R_interp;
            pitch_us_L_TorqueAxis2DOWN_bins(:,n_now) = pitch_us_L_interp;
            pitch_us_R_TorqueAxis2DOWN_bins(:,n_now) = pitch_us_R_interp;
            dev_us_L_TorqueAxis2DOWN_bins(:,n_now) = dev_us_L_interp;
            dev_us_R_TorqueAxis2DOWN_bins(:,n_now) = dev_us_R_interp;
            aoa_us_L_TorqueAxis2DOWN_bins(:,n_now) = aoa_us_L_interp;
            aoa_us_R_TorqueAxis2DOWN_bins(:,n_now) = aoa_us_R_interp;
            U_us_L_TorqueAxis2DOWN_bins(:,n_now) = U_us_L_interp;
            U_us_R_TorqueAxis2DOWN_bins(:,n_now) = U_us_R_interp;
            Dstroke_us_TorqueAxis2DOWN_bins(:,n_now) = Dstroke_us_interp;
            Dpitch_us_TorqueAxis2DOWN_bins(:,n_now) = Dpitch_us_interp;
            Ddev_us_TorqueAxis2DOWN_bins(:,n_now) = Ddev_us_interp;
            Daoa_us_TorqueAxis2DOWN_bins(:,n_now) = Daoa_us_interp;
            DU_us_TorqueAxis2DOWN_bins(:,n_now) = DU_us_interp;
            
            freqMOD_wb_TorqueAxis2DOWN(n_now,1) = freqMOD_wb_now;
            
            strokeMOD_wb_L_TorqueAxis2DOWN_bins(:,n_now) = strokeMOD_wb_L_now;
            strokeMOD_wb_R_TorqueAxis2DOWN_bins(:,n_now) = strokeMOD_wb_R_now;
            strokeMOD_ds_L_TorqueAxis2DOWN_bins(:,n_now) = strokeMOD_ds_L_now;
            strokeMOD_ds_R_TorqueAxis2DOWN_bins(:,n_now) = strokeMOD_ds_R_now;
            strokeMOD_us_L_TorqueAxis2DOWN_bins(:,n_now) = strokeMOD_us_L_now;
            strokeMOD_us_R_TorqueAxis2DOWN_bins(:,n_now) = strokeMOD_us_R_now;

            pitchMOD_wb_L_TorqueAxis2DOWN_bins(:,n_now) = pitchMOD_wb_L_now;
            pitchMOD_wb_R_TorqueAxis2DOWN_bins(:,n_now) = pitchMOD_wb_R_now;
            pitchMOD_ds_L_TorqueAxis2DOWN_bins(:,n_now) = pitchMOD_ds_L_now;
            pitchMOD_ds_R_TorqueAxis2DOWN_bins(:,n_now) = pitchMOD_ds_R_now;
            pitchMOD_us_L_TorqueAxis2DOWN_bins(:,n_now) = pitchMOD_us_L_now;
            pitchMOD_us_R_TorqueAxis2DOWN_bins(:,n_now) = pitchMOD_us_R_now;

            devMOD_wb_L_TorqueAxis2DOWN_bins(:,n_now) = devMOD_wb_L_now;
            devMOD_wb_R_TorqueAxis2DOWN_bins(:,n_now) = devMOD_wb_R_now;
            devMOD_ds_L_TorqueAxis2DOWN_bins(:,n_now) = devMOD_ds_L_now;
            devMOD_ds_R_TorqueAxis2DOWN_bins(:,n_now) = devMOD_ds_R_now;
            devMOD_us_L_TorqueAxis2DOWN_bins(:,n_now) = devMOD_us_L_now;
            devMOD_us_R_TorqueAxis2DOWN_bins(:,n_now) = devMOD_us_R_now;
            
            DstrokeMOD_wb_TorqueAxis2DOWN_bins(:,n_now) = DstrokeMOD_wb_now;
            DstrokeMOD_ds_TorqueAxis2DOWN_bins(:,n_now) = DstrokeMOD_ds_now;
            DstrokeMOD_us_TorqueAxis2DOWN_bins(:,n_now) = DstrokeMOD_us_now;
            
            DpitchMOD_wb_TorqueAxis2DOWN_bins(:,n_now) = DpitchMOD_wb_now;
            DpitchMOD_ds_TorqueAxis2DOWN_bins(:,n_now) = DpitchMOD_ds_now;
            DpitchMOD_us_TorqueAxis2DOWN_bins(:,n_now) = DpitchMOD_us_now;
            
            DdevMOD_wb_TorqueAxis2DOWN_bins(:,n_now) = DdevMOD_wb_now;
            DdevMOD_ds_TorqueAxis2DOWN_bins(:,n_now) = DdevMOD_ds_now;
            DdevMOD_us_TorqueAxis2DOWN_bins(:,n_now) = DdevMOD_us_now;
        end
end

% mean & 95%CI
V_TorqueAxis2DOWN_meanCIstd = [nanmean(V_TorqueAxis2DOWN) 1.96*nanstd(V_TorqueAxis2DOWN)/sqrt(length(V_TorqueAxis2DOWN)) nanstd(V_TorqueAxis2DOWN)];
pitch_global_TorqueAxis2DOWN_meanCIstd = [nanmean(pitch_global_TorqueAxis2DOWN) 1.96*nanstd(pitch_global_TorqueAxis2DOWN)/sqrt(length(pitch_global_TorqueAxis2DOWN)) nanstd(pitch_global_TorqueAxis2DOWN)];

dt_ds_TorqueAxis2DOWN_meanCIstd = [nanmean(dt_ds_TorqueAxis2DOWN) 1.96*nanstd(dt_ds_TorqueAxis2DOWN)/sqrt(length(dt_ds_TorqueAxis2DOWN)) nanstd(dt_ds_TorqueAxis2DOWN)];
dt_us_TorqueAxis2DOWN_meanCIstd = [nanmean(dt_us_TorqueAxis2DOWN) 1.96*nanstd(dt_us_TorqueAxis2DOWN)/sqrt(length(dt_us_TorqueAxis2DOWN)) nanstd(dt_us_TorqueAxis2DOWN)];
f_wb_TorqueAxis2DOWN_meanCIstd = [nanmean(f_wb_TorqueAxis2DOWN) 1.96*nanstd(f_wb_TorqueAxis2DOWN)/sqrt(length(f_wb_TorqueAxis2DOWN)) nanstd(f_wb_TorqueAxis2DOWN)];
Rds_TorqueAxis2DOWN_meanCIstd = [nanmean(Rds_TorqueAxis2DOWN) 1.96*nanstd(Rds_TorqueAxis2DOWN)/sqrt(length(Rds_TorqueAxis2DOWN)) nanstd(Rds_TorqueAxis2DOWN)];

calc_WBfunc_TorqueAxis2DOWN_circmeanCIstd

% wbMOD means & 95%CI
freqMOD_wb_TorqueAxis2DOWN_meanCIstd = [nanmean(freqMOD_wb_TorqueAxis2DOWN) 1.96*nanstd(freqMOD_wb_TorqueAxis2DOWN)/sqrt(length(freqMOD_wb_TorqueAxis2DOWN)) nanstd(freqMOD_wb_TorqueAxis2DOWN)];
calc_WBmod_TorqueAxis2DOWN_circmeanCIstd

%% WBfits
    t_loc = t_wb_TorqueAxis2DOWN_bins(:,1);
    Rds_loc = Rds_TorqueAxis2DOWN_meanCIstd(1);

    plotting = 0;
%         plotting = 1;

%% fit for LEFT wing (bins)
    stroke_loc = stroke_wb_L_TorqueAxis2DOWN_bins_meanCIstd(:,1);
    pitch_loc = pitch_wb_L_TorqueAxis2DOWN_bins_meanCIstd(:,1);
    dev_loc = dev_wb_L_TorqueAxis2DOWN_bins_meanCIstd(:,1);
    
    strokeMOD_loc = strokeMOD_wb_L_TorqueAxis2DOWN_bins_meanCIstd(:,1);
    pitchMOD_loc = pitchMOD_wb_L_TorqueAxis2DOWN_bins_meanCIstd(:,1);
    devMOD_loc = devMOD_wb_L_TorqueAxis2DOWN_bins_meanCIstd(:,1);

        %% legendre polynomials
        % wingbeats
            [stroke_L_TorqueAxis2DOWN_fit_binmean, stroke_L_TorqueAxis2DOWN_fit_binmean_periodic] = WBfitting_singlevar_updowncut(n_pol_stroke,t_loc,stroke_loc,Rds_loc);
            [pitch_L_TorqueAxis2DOWN_fit_binmean, pitch_L_TorqueAxis2DOWN_fit_binmean_periodic] = WBfitting_singlevar_updowncut(n_pol_pitch,t_loc,pitch_loc,Rds_loc);
            [dev_L_TorqueAxis2DOWN_fit_binmean, dev_L_TorqueAxis2DOWN_fit_binmean_periodic] = WBfitting_singlevar_updowncut(n_pol_dev,t_loc,dev_loc,Rds_loc);

        % wingbeatMODs
            [strokeMOD_L_TorqueAxis2DOWN_fit_binmean, strokeMOD_L_TorqueAxis2DOWN_fit_binmean_periodic] = WBfitting_singlevar_updowncut(n_pol_MOD,t_loc,strokeMOD_loc,Rds_loc);
            [pitchMOD_L_TorqueAxis2DOWN_fit_binmean, pitchMOD_L_TorqueAxis2DOWN_fit_binmean_periodic] = WBfitting_singlevar_updowncut(n_pol_MOD,t_loc,pitchMOD_loc,Rds_loc);
            [devMOD_L_TorqueAxis2DOWN_fit_binmean, devMOD_L_TorqueAxis2DOWN_fit_binmean_periodic] = WBfitting_singlevar_updowncut(n_pol_MOD,t_loc,devMOD_loc,Rds_loc);

        %% fourier series
            % wingbeats
            [stroke_L_TorqueAxis2DOWN_fourier_fit_binmean, stroke_L_TorqueAxis2DOWN_fourier_gof_binmean,stroke_L_TorqueAxis2DOWN_fourier_coeffs_binmean] = create_fourier_series_4thN8th_order(t_loc, stroke_loc,stroke_fourier_order,plotting);
            [pitch_L_TorqueAxis2DOWN_fourier_fit_binmean, pitch_L_TorqueAxis2DOWN_fourier_gof_binmean,pitch_L_TorqueAxis2DOWN_fourier_coeffs_binmean] = create_fourier_series_4thN8th_order(t_loc, pitch_loc,pitch_fourier_order,plotting);
            [dev_L_TorqueAxis2DOWN_fourier_fit_binmean, dev_L_TorqueAxis2DOWN_fourier_gof_binmean,dev_L_TorqueAxis2DOWN_fourier_coeffs_binmean] = create_fourier_series_4thN8th_order(t_loc, dev_loc,dev_fourier_order,plotting);

            % wingbeatMODs
            [strokeMOD_L_TorqueAxis2DOWN_fourier_fit_binmean, strokeMOD_L_TorqueAxis2DOWN_fourier_gof_binmean,strokeMOD_L_TorqueAxis2DOWN_fourier_coeffs_binmean] = create_fourier_series_4thN8th_order(t_loc, strokeMOD_loc,MOD_fourier_order,plotting);
            [pitchMOD_L_TorqueAxis2DOWN_fourier_fit_binmean, pitchMOD_L_TorqueAxis2DOWN_fourier_gof_binmean,pitchMOD_L_TorqueAxis2DOWN_fourier_coeffs_binmean] = create_fourier_series_4thN8th_order(t_loc, pitchMOD_loc,MOD_fourier_order,plotting);
            [devMOD_L_TorqueAxis2DOWN_fourier_fit_binmean, devMOD_L_TorqueAxis2DOWN_fourier_gof_binmean,devMOD_L_TorqueAxis2DOWN_fourier_coeffs_binmean] = create_fourier_series_4thN8th_order(t_loc, devMOD_loc,MOD_fourier_order,plotting);
    
%% fit for Right wing (bins)
    stroke_loc = stroke_wb_R_TorqueAxis2DOWN_bins_meanCIstd(:,1);
    pitch_loc = pitch_wb_R_TorqueAxis2DOWN_bins_meanCIstd(:,1);
    dev_loc = dev_wb_R_TorqueAxis2DOWN_bins_meanCIstd(:,1);

    strokeMOD_loc = strokeMOD_wb_R_TorqueAxis2DOWN_bins_meanCIstd(:,1);
    pitchMOD_loc = pitchMOD_wb_R_TorqueAxis2DOWN_bins_meanCIstd(:,1);
    devMOD_loc = devMOD_wb_R_TorqueAxis2DOWN_bins_meanCIstd(:,1);

        %% legendre polynomials
        % wingbeats
            [stroke_R_TorqueAxis2DOWN_fit_binmean, stroke_R_TorqueAxis2DOWN_fit_binmean_periodic] = WBfitting_singlevar_updowncut(n_pol_stroke,t_loc,stroke_loc,Rds_loc);
            [pitch_R_TorqueAxis2DOWN_fit_binmean, pitch_R_TorqueAxis2DOWN_fit_binmean_periodic] = WBfitting_singlevar_updowncut(n_pol_pitch,t_loc,pitch_loc,Rds_loc);
            [dev_R_TorqueAxis2DOWN_fit_binmean, dev_R_TorqueAxis2DOWN_fit_binmean_periodic] = WBfitting_singlevar_updowncut(n_pol_dev,t_loc,dev_loc,Rds_loc);

        % wingbeatMODs
            [strokeMOD_R_TorqueAxis2DOWN_fit_binmean, strokeMOD_R_TorqueAxis2DOWN_fit_binmean_periodic] = WBfitting_singlevar_updowncut(n_pol_MOD,t_loc,strokeMOD_loc,Rds_loc);
            [pitchMOD_R_TorqueAxis2DOWN_fit_binmean, pitchMOD_R_TorqueAxis2DOWN_fit_binmean_periodic] = WBfitting_singlevar_updowncut(n_pol_MOD,t_loc,pitchMOD_loc,Rds_loc);
            [devMOD_R_TorqueAxis2DOWN_fit_binmean, devMOD_R_TorqueAxis2DOWN_fit_binmean_periodic] = WBfitting_singlevar_updowncut(n_pol_MOD,t_loc,devMOD_loc,Rds_loc);

        %% fourier series
            % wingbeats
            [stroke_R_TorqueAxis2DOWN_fourier_fit_binmean, stroke_R_TorqueAxis2DOWN_fourier_gof_binmean,stroke_R_TorqueAxis2DOWN_fourier_coeffs_binmean] = create_fourier_series_4thN8th_order(t_loc, stroke_loc,stroke_fourier_order,plotting);
            [pitch_R_TorqueAxis2DOWN_fourier_fit_binmean, pitch_R_TorqueAxis2DOWN_fourier_gof_binmean,pitch_R_TorqueAxis2DOWN_fourier_coeffs_binmean] = create_fourier_series_4thN8th_order(t_loc, pitch_loc,pitch_fourier_order,plotting);
            [dev_R_TorqueAxis2DOWN_fourier_fit_binmean, dev_R_TorqueAxis2DOWN_fourier_gof_binmean,dev_R_TorqueAxis2DOWN_fourier_coeffs_binmean] = create_fourier_series_4thN8th_order(t_loc, dev_loc,dev_fourier_order,plotting);

            % wingbeatMODs
            [strokeMOD_R_TorqueAxis2DOWN_fourier_fit_binmean, strokeMOD_R_TorqueAxis2DOWN_fourier_gof_binmean,strokeMOD_R_TorqueAxis2DOWN_fourier_coeffs_binmean] = create_fourier_series_4thN8th_order(t_loc, strokeMOD_loc,MOD_fourier_order,plotting);
            [pitchMOD_R_TorqueAxis2DOWN_fourier_fit_binmean, pitchMOD_R_TorqueAxis2DOWN_fourier_gof_binmean,pitchMOD_R_TorqueAxis2DOWN_fourier_coeffs_binmean] = create_fourier_series_4thN8th_order(t_loc, pitchMOD_loc,MOD_fourier_order,plotting);
            [devMOD_R_TorqueAxis2DOWN_fourier_fit_binmean, devMOD_R_TorqueAxis2DOWN_fourier_gof_binmean,devMOD_R_TorqueAxis2DOWN_fourier_coeffs_binmean] = create_fourier_series_4thN8th_order(t_loc, devMOD_loc,MOD_fourier_order,plotting);
    
%% L-R
    stroke_loc = Dstroke_wb_TorqueAxis2DOWN_bins_meanCIstd(:,1);
    pitch_loc = Dpitch_wb_TorqueAxis2DOWN_bins_meanCIstd(:,1);
    dev_loc = Ddev_wb_TorqueAxis2DOWN_bins_meanCIstd(:,1);

    strokeMOD_loc = DstrokeMOD_wb_TorqueAxis2DOWN_bins_meanCIstd(:,1);
    pitchMOD_loc = DpitchMOD_wb_TorqueAxis2DOWN_bins_meanCIstd(:,1);
    devMOD_loc = DdevMOD_wb_TorqueAxis2DOWN_bins_meanCIstd(:,1);
    
        %% legendre polynomials
            % wingbeats
            [Dstroke_TorqueAxis2DOWN_fit_binmean, Dstroke_TorqueAxis2DOWN_fit_binmean_periodic] = WBfitting_singlevar_updowncut(n_pol_stroke,t_loc,stroke_loc,Rds_loc);
            [Dpitch_TorqueAxis2DOWN_fit_binmean, Dpitch_TorqueAxis2DOWN_fit_binmean_periodic] = WBfitting_singlevar_updowncut(n_pol_pitch,t_loc,pitch_loc,Rds_loc);
            [Ddev_TorqueAxis2DOWN_fit_binmean, Ddev_TorqueAxis2DOWN_fit_binmean_periodic] = WBfitting_singlevar_updowncut(n_pol_dev,t_loc,dev_loc,Rds_loc);

        % wingbeatMODs
            [DstrokeMOD_TorqueAxis2DOWN_fit_binmean, DstrokeMOD_TorqueAxis2DOWN_fit_binmean_periodic] = WBfitting_singlevar_updowncut(n_pol_MOD,t_loc,strokeMOD_loc,Rds_loc);
            [DpitchMOD_TorqueAxis2DOWN_fit_binmean, DpitchMOD_TorqueAxis2DOWN_fit_binmean_periodic] = WBfitting_singlevar_updowncut(n_pol_MOD,t_loc,pitchMOD_loc,Rds_loc);
            [DdevMOD_TorqueAxis2DOWN_fit_binmean, DdevMOD_TorqueAxis2DOWN_fit_binmean_periodic] = WBfitting_singlevar_updowncut(n_pol_MOD,t_loc,devMOD_loc,Rds_loc);

        %% fourier series
            % wingbeats
            [Dstroke_TorqueAxis2DOWN_fourier_fit_binmean, Dstroke_TorqueAxis2DOWN_fourier_gof_binmean,Dstroke_TorqueAxis2DOWN_fourier_coeffs_binmean] = create_fourier_series_4thN8th_order(t_loc, stroke_loc,stroke_fourier_order,plotting);
            [Dpitch_TorqueAxis2DOWN_fourier_fit_binmean, Dpitch_TorqueAxis2DOWN_fourier_gof_binmean,Dpitch_TorqueAxis2DOWN_fourier_coeffs_binmean] = create_fourier_series_4thN8th_order(t_loc, pitch_loc,pitch_fourier_order,plotting);
            [Ddev_TorqueAxis2DOWN_fourier_fit_binmean, Ddev_TorqueAxis2DOWN_fourier_gof_binmean,Ddev_TorqueAxis2DOWN_fourier_coeffs_binmean] = create_fourier_series_4thN8th_order(t_loc, dev_loc,dev_fourier_order,plotting);

            % wingbeatMODs
            [DstrokeMOD_TorqueAxis2DOWN_fourier_fit_binmean, DstrokeMOD_TorqueAxis2DOWN_fourier_gof_binmean,DstrokeMOD_TorqueAxis2DOWN_fourier_coeffs_binmean] = create_fourier_series_4thN8th_order(t_loc, strokeMOD_loc,MOD_fourier_order,plotting);
            [DpitchMOD_TorqueAxis2DOWN_fourier_fit_binmean, DpitchMOD_TorqueAxis2DOWN_fourier_gof_binmean,DpitchMOD_TorqueAxis2DOWN_fourier_coeffs_binmean] = create_fourier_series_4thN8th_order(t_loc, pitchMOD_loc,MOD_fourier_order,plotting);
            [DdevMOD_TorqueAxis2DOWN_fourier_fit_binmean, DdevMOD_TorqueAxis2DOWN_fourier_gof_binmean,DdevMOD_TorqueAxis2DOWN_fourier_coeffs_binmean] = create_fourier_series_4thN8th_order(t_loc, devMOD_loc,MOD_fourier_order,plotting);
    
%% save TorqueAxis2DOWN wb data
n_TorqueAxis2DOWN = n_now   

if save_on == 1

save(['WBmod_torquebased_TorqueAxis2DOWN_',num2str(n_TorqueAxis2DOWN),'WBs.mat'],...
'n_TorqueAxis2DOWN',...
'seq_nr_TorqueAxis2DOWN',...
'wb_nr_TorqueAxis2DOWN',...
...
'limit_mod',...
'Mroll_limit_mod',...
'Mpitch_limit_mod',...
'Myaw_limit_mod',...
'M_axis2normal_limit_mod',...
'M_axis2_limit_mod',...
'Fenhance_limit_mod',...
...
'norm',...
'Mroll_norm',...
'Mpitch_norm',...
'Myaw_norm',...
'M_axis2normal_norm',...
'M_axis2_norm',...
'Fenhance_norm',...
...
'n_pol_stroke',...
'n_pol_pitch',...
'n_pol_dev',...
'n_pol_MOD',...
...
'stroke_R_TorqueAxis2DOWN_fit_binmean_periodic',...
'pitch_R_TorqueAxis2DOWN_fit_binmean_periodic',...
'dev_R_TorqueAxis2DOWN_fit_binmean_periodic',...
...
'stroke_L_TorqueAxis2DOWN_fit_binmean_periodic',...
'pitch_L_TorqueAxis2DOWN_fit_binmean_periodic',...
'dev_L_TorqueAxis2DOWN_fit_binmean_periodic',...
...
'strokeMOD_R_TorqueAxis2DOWN_fit_binmean_periodic',...
'pitchMOD_R_TorqueAxis2DOWN_fit_binmean_periodic',...
'devMOD_R_TorqueAxis2DOWN_fit_binmean_periodic',...
...
'strokeMOD_L_TorqueAxis2DOWN_fit_binmean_periodic',...
'pitchMOD_L_TorqueAxis2DOWN_fit_binmean_periodic',...
'devMOD_L_TorqueAxis2DOWN_fit_binmean_periodic',...
...
...
'stroke_fourier_order',...
'pitch_fourier_order',...
'dev_fourier_order',...
'MOD_fourier_order',...
...
'stroke_R_TorqueAxis2DOWN_fourier_coeffs_binmean',...
'pitch_R_TorqueAxis2DOWN_fourier_coeffs_binmean',...
'dev_R_TorqueAxis2DOWN_fourier_coeffs_binmean',...
...
'stroke_R_TorqueAxis2DOWN_fourier_gof_binmean',...
'pitch_R_TorqueAxis2DOWN_fourier_gof_binmean',...
'dev_R_TorqueAxis2DOWN_fourier_gof_binmean',...
...
'stroke_L_TorqueAxis2DOWN_fourier_coeffs_binmean',...
'pitch_L_TorqueAxis2DOWN_fourier_coeffs_binmean',...
'dev_L_TorqueAxis2DOWN_fourier_coeffs_binmean',...
...
'stroke_L_TorqueAxis2DOWN_fourier_gof_binmean',...
'pitch_L_TorqueAxis2DOWN_fourier_gof_binmean',...
'dev_L_TorqueAxis2DOWN_fourier_gof_binmean',...
...
'Dstroke_TorqueAxis2DOWN_fourier_coeffs_binmean',...
'Dpitch_TorqueAxis2DOWN_fourier_coeffs_binmean',...
'Ddev_TorqueAxis2DOWN_fourier_coeffs_binmean',...
...
'Dstroke_TorqueAxis2DOWN_fourier_gof_binmean',...
'Dpitch_TorqueAxis2DOWN_fourier_gof_binmean',...
'Ddev_TorqueAxis2DOWN_fourier_gof_binmean',...
...
'strokeMOD_R_TorqueAxis2DOWN_fourier_coeffs_binmean',...
'pitchMOD_R_TorqueAxis2DOWN_fourier_coeffs_binmean',...
'devMOD_R_TorqueAxis2DOWN_fourier_coeffs_binmean',...
...
'strokeMOD_R_TorqueAxis2DOWN_fourier_gof_binmean',...
'pitchMOD_R_TorqueAxis2DOWN_fourier_gof_binmean',...
'devMOD_R_TorqueAxis2DOWN_fourier_gof_binmean',...
...
'strokeMOD_L_TorqueAxis2DOWN_fourier_coeffs_binmean',...
'pitchMOD_L_TorqueAxis2DOWN_fourier_coeffs_binmean',...
'devMOD_L_TorqueAxis2DOWN_fourier_coeffs_binmean',...
...
'strokeMOD_L_TorqueAxis2DOWN_fourier_gof_binmean',...
'pitchMOD_L_TorqueAxis2DOWN_fourier_gof_binmean',...
'devMOD_L_TorqueAxis2DOWN_fourier_gof_binmean',...
...
'DstrokeMOD_TorqueAxis2DOWN_fourier_coeffs_binmean',...
'DpitchMOD_TorqueAxis2DOWN_fourier_coeffs_binmean',...
'DdevMOD_TorqueAxis2DOWN_fourier_coeffs_binmean',...
...
'DstrokeMOD_TorqueAxis2DOWN_fourier_gof_binmean',...
'DpitchMOD_TorqueAxis2DOWN_fourier_gof_binmean',...
'DdevMOD_TorqueAxis2DOWN_fourier_gof_binmean',...
...
'stroke_wb_R_TorqueAxis2DOWN_bins_meanCIstd',...
'stroke_ds_R_TorqueAxis2DOWN_bins_meanCIstd',...
'stroke_us_R_TorqueAxis2DOWN_bins_meanCIstd',...
...
'pitch_wb_R_TorqueAxis2DOWN_bins_meanCIstd',...
'pitch_ds_R_TorqueAxis2DOWN_bins_meanCIstd',...
'pitch_us_R_TorqueAxis2DOWN_bins_meanCIstd',...
...
'dev_wb_R_TorqueAxis2DOWN_bins_meanCIstd',...
'dev_ds_R_TorqueAxis2DOWN_bins_meanCIstd',...
'dev_us_R_TorqueAxis2DOWN_bins_meanCIstd',...
...
'strokeMOD_wb_R_TorqueAxis2DOWN_bins_meanCIstd',...
'strokeMOD_ds_R_TorqueAxis2DOWN_bins_meanCIstd',...
'strokeMOD_us_R_TorqueAxis2DOWN_bins_meanCIstd',...
...
'pitchMOD_wb_R_TorqueAxis2DOWN_bins_meanCIstd',...
'pitchMOD_ds_R_TorqueAxis2DOWN_bins_meanCIstd',...
'pitchMOD_us_R_TorqueAxis2DOWN_bins_meanCIstd',...
...
'devMOD_wb_R_TorqueAxis2DOWN_bins_meanCIstd',...
'devMOD_ds_R_TorqueAxis2DOWN_bins_meanCIstd',...
'devMOD_us_R_TorqueAxis2DOWN_bins_meanCIstd',...
...
'stroke_wb_L_TorqueAxis2DOWN_bins_meanCIstd',...
'stroke_ds_L_TorqueAxis2DOWN_bins_meanCIstd',...
'stroke_us_L_TorqueAxis2DOWN_bins_meanCIstd',...
...
'pitch_wb_L_TorqueAxis2DOWN_bins_meanCIstd',...
'pitch_ds_L_TorqueAxis2DOWN_bins_meanCIstd',...
'pitch_us_L_TorqueAxis2DOWN_bins_meanCIstd',...
...
'dev_wb_L_TorqueAxis2DOWN_bins_meanCIstd',...
'dev_ds_L_TorqueAxis2DOWN_bins_meanCIstd',...
'dev_us_L_TorqueAxis2DOWN_bins_meanCIstd',...
...
'strokeMOD_wb_L_TorqueAxis2DOWN_bins_meanCIstd',...
'strokeMOD_ds_L_TorqueAxis2DOWN_bins_meanCIstd',...
'strokeMOD_us_L_TorqueAxis2DOWN_bins_meanCIstd',...
...
'pitchMOD_wb_L_TorqueAxis2DOWN_bins_meanCIstd',...
'pitchMOD_ds_L_TorqueAxis2DOWN_bins_meanCIstd',...
'pitchMOD_us_L_TorqueAxis2DOWN_bins_meanCIstd',...
...
'devMOD_wb_L_TorqueAxis2DOWN_bins_meanCIstd',...
'devMOD_ds_L_TorqueAxis2DOWN_bins_meanCIstd',...
'devMOD_us_L_TorqueAxis2DOWN_bins_meanCIstd',...
...
'DstrokeMOD_wb_TorqueAxis2DOWN_bins_meanCIstd',...
'DstrokeMOD_ds_TorqueAxis2DOWN_bins_meanCIstd',...
'DstrokeMOD_us_TorqueAxis2DOWN_bins_meanCIstd',...
...
'DpitchMOD_wb_TorqueAxis2DOWN_bins_meanCIstd',...
'DpitchMOD_ds_TorqueAxis2DOWN_bins_meanCIstd',...
'DpitchMOD_us_TorqueAxis2DOWN_bins_meanCIstd',...
...
'DdevMOD_wb_TorqueAxis2DOWN_bins_meanCIstd',...
'DdevMOD_ds_TorqueAxis2DOWN_bins_meanCIstd',...
'DdevMOD_us_TorqueAxis2DOWN_bins_meanCIstd',...
...
'V_TorqueAxis2DOWN',...
'pitch_global_TorqueAxis2DOWN',...
'dt_ds_TorqueAxis2DOWN',...
'dt_us_TorqueAxis2DOWN',...
'f_wb_TorqueAxis2DOWN',...
'Rds_TorqueAxis2DOWN',...
...
'V_TorqueAxis2DOWN_meanCIstd',...
'pitch_global_TorqueAxis2DOWN_meanCIstd',...
'F_TorqueAxis2DOWN',...
...
'Mroll_accel_TorqueAxis2DOWN',...
'Mpitch_accel_TorqueAxis2DOWN',...
'Myaw_accel_TorqueAxis2DOWN',...
'M_axis2normal_accel_TorqueAxis2DOWN',...
'M_axis2_accel_TorqueAxis2DOWN',...
...
'Mroll_damp_TorqueAxis2DOWN',...
'Mpitch_damp_TorqueAxis2DOWN',...
'Myaw_damp_TorqueAxis2DOWN',...
'M_axis2normal_damp_TorqueAxis2DOWN',...
'M_axis2_damp_TorqueAxis2DOWN',...
...
'Mroll_TorqueAxis2DOWN',...
'Mpitch_TorqueAxis2DOWN',...
'Myaw_TorqueAxis2DOWN',...
'M_axis2normal_TorqueAxis2DOWN',...
'M_axis2_TorqueAxis2DOWN',...
...
'rollaccel_TorqueAxis2DOWN',...
'pitchaccel_TorqueAxis2DOWN',...
'yawaccel_TorqueAxis2DOWN',...
'rotRaccel_TorqueAxis2DOWN',...
...
'rollvel_TorqueAxis2DOWN',...
'pitchvel_TorqueAxis2DOWN',...
'yawvel_TorqueAxis2DOWN',...
'rotRvel_TorqueAxis2DOWN',...
...
'dt_ds_TorqueAxis2DOWN_meanCIstd',...
'dt_us_TorqueAxis2DOWN_meanCIstd',...
'f_wb_TorqueAxis2DOWN_meanCIstd',...
'Rds_TorqueAxis2DOWN_meanCIstd',...
...
'freqMOD_wb_TorqueAxis2DOWN_meanCIstd',...
'freqMOD_wb_TorqueAxis2DOWN',...
...
'strokeMOD_wb_R_TorqueAxis2DOWN_bins',...
'strokeMOD_wb_L_TorqueAxis2DOWN_bins',...
'strokeMOD_ds_R_TorqueAxis2DOWN_bins',...
'strokeMOD_ds_L_TorqueAxis2DOWN_bins',...
'strokeMOD_us_R_TorqueAxis2DOWN_bins',...
'strokeMOD_us_L_TorqueAxis2DOWN_bins',...
...
'pitchMOD_wb_R_TorqueAxis2DOWN_bins',...
'pitchMOD_wb_L_TorqueAxis2DOWN_bins',...
'pitchMOD_ds_R_TorqueAxis2DOWN_bins',...
'pitchMOD_ds_L_TorqueAxis2DOWN_bins',...
'pitchMOD_us_R_TorqueAxis2DOWN_bins',...
'pitchMOD_us_L_TorqueAxis2DOWN_bins',...
...
'devMOD_wb_R_TorqueAxis2DOWN_bins',...
'devMOD_wb_L_TorqueAxis2DOWN_bins',...
'devMOD_ds_R_TorqueAxis2DOWN_bins',...
'devMOD_ds_L_TorqueAxis2DOWN_bins',...
'devMOD_us_R_TorqueAxis2DOWN_bins',...
'devMOD_us_L_TorqueAxis2DOWN_bins',...
...
'DstrokeMOD_wb_TorqueAxis2DOWN_bins',...
'DstrokeMOD_ds_TorqueAxis2DOWN_bins',...
'DstrokeMOD_us_TorqueAxis2DOWN_bins',...
...
'DpitchMOD_wb_TorqueAxis2DOWN_bins',...
'DpitchMOD_ds_TorqueAxis2DOWN_bins',...
'DpitchMOD_us_TorqueAxis2DOWN_bins',...
...
'DdevMOD_wb_TorqueAxis2DOWN_bins',...
'DdevMOD_ds_TorqueAxis2DOWN_bins',...
'DdevMOD_us_TorqueAxis2DOWN_bins',...
...
't_wb_R_TorqueAxis2DOWN',...
't_wb_L_TorqueAxis2DOWN',...
'stroke_wb_R_TorqueAxis2DOWN',...
'stroke_wb_L_TorqueAxis2DOWN',...
'pitch_wb_R_TorqueAxis2DOWN',...
'pitch_wb_L_TorqueAxis2DOWN',...
'dev_wb_R_TorqueAxis2DOWN',...
'dev_wb_L_TorqueAxis2DOWN',...
'aoa_wb_R_TorqueAxis2DOWN',...
'aoa_wb_L_TorqueAxis2DOWN',...
'U_wb_R_TorqueAxis2DOWN',...
'U_wb_L_TorqueAxis2DOWN',...
...
't_ds_R_TorqueAxis2DOWN',...
't_ds_L_TorqueAxis2DOWN',...
'stroke_ds_R_TorqueAxis2DOWN',...
'stroke_ds_L_TorqueAxis2DOWN',...
'pitch_ds_R_TorqueAxis2DOWN',...
'pitch_ds_L_TorqueAxis2DOWN',...
'dev_ds_R_TorqueAxis2DOWN',...
'dev_ds_L_TorqueAxis2DOWN',...
'aoa_ds_R_TorqueAxis2DOWN',...
'aoa_ds_L_TorqueAxis2DOWN',...
'U_ds_R_TorqueAxis2DOWN',...
'U_ds_L_TorqueAxis2DOWN',...
...
't_us_R_TorqueAxis2DOWN',...
't_us_L_TorqueAxis2DOWN',...
'stroke_us_R_TorqueAxis2DOWN',...
'stroke_us_L_TorqueAxis2DOWN',...
'pitch_us_R_TorqueAxis2DOWN',...
'pitch_us_L_TorqueAxis2DOWN',...
'dev_us_R_TorqueAxis2DOWN',...
'dev_us_L_TorqueAxis2DOWN',...
'aoa_us_R_TorqueAxis2DOWN',...
'aoa_us_L_TorqueAxis2DOWN',...
'U_us_R_TorqueAxis2DOWN',...
'U_us_L_TorqueAxis2DOWN',...
...
't_wb_TorqueAxis2DOWN_bins',...
'stroke_wb_R_TorqueAxis2DOWN_bins',...
'stroke_wb_L_TorqueAxis2DOWN_bins',...
'pitch_wb_R_TorqueAxis2DOWN_bins',...
'pitch_wb_L_TorqueAxis2DOWN_bins',...
'dev_wb_R_TorqueAxis2DOWN_bins',...
'dev_wb_L_TorqueAxis2DOWN_bins',...
'aoa_wb_R_TorqueAxis2DOWN_bins',...
'aoa_wb_L_TorqueAxis2DOWN_bins',...
'U_wb_R_TorqueAxis2DOWN_bins',...
'U_wb_L_TorqueAxis2DOWN_bins',...
'Dstroke_wb_TorqueAxis2DOWN_bins',...
'Dpitch_wb_TorqueAxis2DOWN_bins',...
'Ddev_wb_TorqueAxis2DOWN_bins',...
'Daoa_wb_TorqueAxis2DOWN_bins',...
'DU_wb_TorqueAxis2DOWN_bins',...
...
't_ds_TorqueAxis2DOWN_bins',...
'stroke_ds_R_TorqueAxis2DOWN_bins',...
'stroke_ds_L_TorqueAxis2DOWN_bins',...
'pitch_ds_R_TorqueAxis2DOWN_bins',...
'pitch_ds_L_TorqueAxis2DOWN_bins',...
'dev_ds_R_TorqueAxis2DOWN_bins',...
'dev_ds_L_TorqueAxis2DOWN_bins',...
'aoa_ds_R_TorqueAxis2DOWN_bins',...
'aoa_ds_L_TorqueAxis2DOWN_bins',...
'U_ds_R_TorqueAxis2DOWN_bins',...
'U_ds_L_TorqueAxis2DOWN_bins',...
'Dstroke_ds_TorqueAxis2DOWN_bins',...
'Dpitch_ds_TorqueAxis2DOWN_bins',...
'Ddev_ds_TorqueAxis2DOWN_bins',...
'Daoa_ds_TorqueAxis2DOWN_bins',...
'DU_ds_TorqueAxis2DOWN_bins',...
...
't_us_TorqueAxis2DOWN_bins',...
'stroke_us_R_TorqueAxis2DOWN_bins',...
'stroke_us_L_TorqueAxis2DOWN_bins',...
'pitch_us_R_TorqueAxis2DOWN_bins',...
'pitch_us_L_TorqueAxis2DOWN_bins',...
'dev_us_R_TorqueAxis2DOWN_bins',...
'dev_us_L_TorqueAxis2DOWN_bins',...
'aoa_us_R_TorqueAxis2DOWN_bins',...
'aoa_us_L_TorqueAxis2DOWN_bins',...
'U_us_R_TorqueAxis2DOWN_bins',...
'U_us_L_TorqueAxis2DOWN_bins',...
'Dstroke_us_TorqueAxis2DOWN_bins',...
'Dpitch_us_TorqueAxis2DOWN_bins',...
'Ddev_us_TorqueAxis2DOWN_bins',...
'Daoa_us_TorqueAxis2DOWN_bins',...
'DU_us_TorqueAxis2DOWN_bins');

end
