save 'MODsNstats_bodyNfreqNvel_indiv.mat' ...
 ...
V_indiv_intact ...
f_indiv_intact ...
pitch_indiv_intact ...
roll_indiv_intact ...
slip_indiv_intact ...
Aplus_indiv_intact ...
RS2_indiv_intact ...
RS3_indiv_intact ...
clip_type_indiv_intact ...
 ...
V_indiv ...
f_indiv ...
pitch_indiv ...
roll_indiv ...
slip_indiv ...
Aplus_indiv ...
RS2_indiv ...
RS3_indiv ...
clip_type_indiv ...
 ...
p_V_indiv ...
tbl_V_indiv ...
stats_V_indiv ...
 ...
p_freq_indiv ...
tbl_freq_indiv ...
stats_freq_indiv ...
 ...
freq_S2S3AmpRatioFunc_indiv_asympFit10 ...
freq_S2S3AmpRatioFunc_indiv_asympFit10_gof ...
freq_S2S3AmpRatioFunc_indiv_linear ...
freq_S2S3AmpRatioFunc_indiv_linear_gof ...
freq_S2S3AmpRatioFunc_indiv_power2 ...
freq_S2S3AmpRatioFunc_indiv_power2_gof ...
freq_S2S3AmpRatioFunc_indiv_smooth999 ...
freq_S2S3AmpRatioFunc_indiv_smooth999_gof ...
 ...
pitch_indiv_intact_mean ...
pitch_indiv_intact_ul ...
pitch_indiv_intact_ll ...
pitch_indiv_intact_med ...
 ...
pitch_indiv_mean ...
pitch_indiv_ul ...
pitch_indiv_ll ...
pitch_indiv_med ...
 ...
pval_pitch_indiv ...
med_pitch_indiv ...
P_pitch_indiv ...
 ...
roll_indiv_mean ...
roll_indiv_ul ...
roll_indiv_ll ...
roll_indiv_med ...
 ...
h_roll_indiv ...
mu_roll_indiv ...
ul_roll_indiv ...
ll_roll_indiv ...
 ...
roll_S2S3AmpRatioFunc_indiv_asympFit10 ...
roll_S2S3AmpRatioFunc_indiv_asympFit10_gof ...
roll_S2S3AmpRatioFunc_indiv_linear ...
roll_S2S3AmpRatioFunc_indiv_linear_gof ...
roll_S2S3AmpRatioFunc_indiv_power2 ...
roll_S2S3AmpRatioFunc_indiv_power2_gof ...
roll_S2S3AmpRatioFunc_indiv_smooth999 ...
roll_S2S3AmpRatioFunc_indiv_smooth999_gof ...
 ...
slip_indiv_mean ...
slip_indiv_ul ...
slip_indiv_ll ...
slip_indiv_med ...
 ...
h_slip_indiv ...
mu_slip_indiv ...
ul_slip_indiv ...
ll_slip_indiv

















