function [fitresult, gof] = createFourierFit_5th_order_stroke(t_per, stroke)
%CREATEFIT(T_PER,STROKE)
%  Create a fit.
%
%  Data for 'dev_steady_fourier_series_10th_order' fit:
%      X Input : t_per
%      Y Output: stroke
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 20-May-2013 23:06:59


%% Fit: 'dev_steady_fourier_series_10th_order'.
[xData, yData] = prepareCurveData( t_per, stroke );

% Set up fittype and options.
ft = fittype( 'fourier5' );
opts = fitoptions( ft );
opts.Display = 'Off';
opts.Lower = [-Inf -Inf -Inf -Inf -Inf -Inf -Inf -Inf -Inf -Inf -Inf -Inf];
opts.StartPoint = [0 0 0 0 0 0 0 0 0 0 0 1];
opts.Upper = [Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Create a figure for the plots.
figure( 'Name', 'dev_steady_fourier_series_10th_order' );

% Plot fit with data.
subplot( 2, 1, 1 );
plot( fitresult, xData, yData );
% Label axes
xlabel( 't_per' );
ylabel( 'stroke' );
grid on

% Plot residuals.
subplot( 2, 1, 2 );
plot( fitresult, xData, yData, 'residuals' );
% Label axes
xlabel( 't_per' );
ylabel( 'stroke' );
grid on


