function [fitresult, gof] = createFit(t_per, pitch)
%CREATEFIT(T_PER,PITCH)
%  Create a fit.
%
%  Data for 'dev_steady_fourier_series_10th_order' fit:
%      X Input : t_per
%      Y Output: pitch
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 20-May-2013 23:02:08


%% Fit: 'dev_steady_fourier_series_10th_order'.
[xData, yData] = prepareCurveData( t_per, pitch );

% Set up fittype and options.
ft = fittype( 'a0 + a1*cos(x) + b1*sin(x)  + a2*cos(2*x) + b2*sin(2*x)  + a3*cos(3*x) + b3*sin(3*x)  + a4*cos(4*x) + b4*sin(4*x)  + a5*cos(5*x) + b5*sin(5*x)  + a6*cos(6*x) + b6*sin(6*x)  + a7*cos(7*x) + b7*sin(7*x)  + a8*cos(8*x) + b8*sin(8*x)  + a9*cos(9*x) + b9*sin(9*x)  + a10*cos(10*x) + b10*sin(10*x)', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( ft );
opts.Algorithm = 'Levenberg-Marquardt';
opts.Display = 'Off';
opts.Lower = [-Inf -Inf -Inf -Inf -Inf -Inf -Inf -Inf -Inf -Inf -Inf -Inf -Inf -Inf -Inf -Inf -Inf -Inf -Inf -Inf -Inf];
opts.StartPoint = [0.613474881705262 0.818640735082209 0.886235039062606 0.931111627487221 0.190784648009122 0.258582251418772 0.897865684840299 0.593361860386109 0.503840081846848 0.612809588835559 0.819422242231876 0.531889169492926 0.202075096548432 0.453893465680522 0.427910919820171 0.966052749611999 0.620055054133474 0.695389951918004 0.720164612017979 0.346895190287614 0.51699042052531];
opts.Upper = [Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Create a figure for the plots.
figure( 'Name', 'dev_steady_fourier_series_10th_order' );

% Plot fit with data.
subplot( 2, 1, 1 );
plot( fitresult, xData, yData );
% Label axes
xlabel( 't_per' );
ylabel( 'pitch' );
grid on

% Plot residuals.
subplot( 2, 1, 2 );
plot( fitresult, xData, yData, 'residuals' );
% Label axes
xlabel( 't_per' );
ylabel( 'pitch' );
grid on


