function [fitresult, gof, coeffs] = create_gaussian_std_fit_normdata(t,y,plotting)

%CREATEFIT Create plot of data sets and fits
%   CREATEFIT(t,y)
%   Creates a plot, similar to the plot in the main Curve Fitting Tool,
%   using the data that you provide as input.  You can
%   use this function with the same data you used with CFTOOL
%   or with different data.  You may want to edit the function to
%   customize the code and this help message.
%
%   Number of data sets:  1
%   Number of fits:  1

% Data from data set "response":
%     X = t:
%     Y = y:
%     Unweighted

% Auto-generated by MATLAB on 24-Oct-2013 10:09:06

% --- Create fit "fit 1"
ok_ = isfinite(t) & isfinite(y);
if ~all( ok_ )
    warning( 'GenerateMFile:IgnoringNansAndInfs',...
        'Ignoring NaNs and Infs in data.' );
end
st_ = [0.3509381079706661577 ];
ft_ = fittype('exp(-(x/a)^2)',...
    'dependent',{'y'},'independent',{'x'},...
    'coefficients',{'a'});

% Fit this model using new data
[fitresult, gof] = fit(t(ok_),y(ok_),ft_,'Startpoint',st_);

if plotting == 1;
    % Plot fit with data.
    figure( 'Name', 'dFh_dir_resp' );
    plot( fitresult, t, y );
    % Label axes
    xlabel( 't' );
    ylabel( 'y' );
    grid on
end

coeffs = coeffvalues(fitresult);