%% pre & post data

%% mean
% wb kin
f_wb_seq_mean_c4 = [f_wb_seq_pre_mean_c4 f_wb_seq_post_mean_c4];

stroke_wb_L_seq_bins_mean_c4 = [stroke_wb_L_seq_bins_pre_mean_c4 stroke_wb_L_seq_bins_post_mean_c4];
stroke_wb_R_seq_bins_mean_c4 = [stroke_wb_R_seq_bins_pre_mean_c4 stroke_wb_R_seq_bins_post_mean_c4];

dev_wb_L_seq_bins_mean_c4 = [dev_wb_L_seq_bins_pre_mean_c4 dev_wb_L_seq_bins_post_mean_c4];
dev_wb_R_seq_bins_mean_c4 = [dev_wb_R_seq_bins_pre_mean_c4 dev_wb_R_seq_bins_post_mean_c4];

pitch_wb_L_seq_bins_mean_c4 = [pitch_wb_L_seq_bins_pre_mean_c4 pitch_wb_L_seq_bins_post_mean_c4];
pitch_wb_R_seq_bins_mean_c4 = [pitch_wb_R_seq_bins_pre_mean_c4 pitch_wb_R_seq_bins_post_mean_c4];

% body kin
roll_mean_wb_seq_mean_c4 = [roll_mean_wb_seq_pre_mean_c4 roll_mean_wb_seq_post_mean_c4];
roll_dot_mean_wb_seq_mean_c4 = [roll_dot_mean_wb_seq_pre_mean_c4 roll_dot_mean_wb_seq_post_mean_c4];
roll_dot_dot_mean_wb_seq_mean_c4 = [roll_dot_dot_mean_wb_seq_pre_mean_c4 roll_dot_dot_mean_wb_seq_post_mean_c4];

pitch_mean_wb_seq_mean_c4 = [pitch_mean_wb_seq_pre_mean_c4 pitch_mean_wb_seq_post_mean_c4];
pitch_dot_mean_wb_seq_mean_c4 = [pitch_dot_mean_wb_seq_pre_mean_c4 pitch_dot_mean_wb_seq_post_mean_c4];
pitch_dot_dot_mean_wb_seq_mean_c4 = [pitch_dot_dot_mean_wb_seq_pre_mean_c4 pitch_dot_dot_mean_wb_seq_post_mean_c4];

yaw_mean_wb_seq_mean_c4 = [yaw_mean_wb_seq_pre_mean_c4 yaw_mean_wb_seq_post_mean_c4];
yaw_dot_mean_wb_seq_mean_c4 = [yaw_dot_mean_wb_seq_pre_mean_c4 yaw_dot_mean_wb_seq_post_mean_c4];
yaw_dot_dot_mean_wb_seq_mean_c4 = [yaw_dot_dot_mean_wb_seq_pre_mean_c4 yaw_dot_dot_mean_wb_seq_post_mean_c4];

drot_L_mean_wb_seq_mean_c4 = [drot_L_mean_wb_seq_pre_mean_c4 drot_L_mean_wb_seq_post_mean_c4];
rot_dot_L_mean_wb_seq_mean_c4 = [rot_dot_L_mean_wb_seq_pre_mean_c4 rot_dot_L_mean_wb_seq_post_mean_c4];
rot_dot_dot_L_mean_wb_seq_mean_c4 = [rot_dot_dot_L_mean_wb_seq_pre_mean_c4 rot_dot_dot_L_mean_wb_seq_post_mean_c4];

drot_R_mean_wb_seq_mean_c4 = [drot_R_mean_wb_seq_pre_mean_c4 drot_R_mean_wb_seq_post_mean_c4];
rot_dot_R_mean_wb_seq_mean_c4 = [rot_dot_R_mean_wb_seq_pre_mean_c4 rot_dot_R_mean_wb_seq_post_mean_c4];
rot_dot_dot_R_mean_wb_seq_mean_c4 = [rot_dot_dot_R_mean_wb_seq_pre_mean_c4 rot_dot_dot_R_mean_wb_seq_post_mean_c4];

% torque
Mroll_mean_wb_accel_seq_mean_c4 = [Mroll_mean_wb_accel_seq_pre_mean_c4 Mroll_mean_wb_accel_seq_post_mean_c4];
Mroll_mean_wb_damp_seq_mean_c4 = [Mroll_mean_wb_damp_seq_pre_mean_c4 Mroll_mean_wb_damp_seq_post_mean_c4];
Mroll_mean_wb_seq_mean_c4 = [Mroll_mean_wb_seq_pre_mean_c4 Mroll_mean_wb_seq_post_mean_c4];

Mpitch_mean_wb_accel_seq_mean_c4 = [Mpitch_mean_wb_accel_seq_pre_mean_c4 Mpitch_mean_wb_accel_seq_post_mean_c4];
Mpitch_mean_wb_damp_seq_mean_c4 = [Mpitch_mean_wb_damp_seq_pre_mean_c4 Mpitch_mean_wb_damp_seq_post_mean_c4];
Mpitch_mean_wb_seq_mean_c4 = [Mpitch_mean_wb_seq_pre_mean_c4 Mpitch_mean_wb_seq_post_mean_c4];

Myaw_mean_wb_accel_seq_mean_c4 = [Myaw_mean_wb_accel_seq_pre_mean_c4 Myaw_mean_wb_accel_seq_post_mean_c4];
Myaw_mean_wb_damp_seq_mean_c4 = [Myaw_mean_wb_damp_seq_pre_mean_c4 Myaw_mean_wb_damp_seq_post_mean_c4];
Myaw_mean_wb_seq_mean_c4 = [Myaw_mean_wb_seq_pre_mean_c4 Myaw_mean_wb_seq_post_mean_c4];

M_L_mean_wb_accel_seq_mean_c4 = [M_L_mean_wb_accel_seq_pre_mean_c4 M_L_mean_wb_accel_seq_post_mean_c4];
M_L_mean_wb_damp_seq_mean_c4 = [M_L_mean_wb_damp_seq_pre_mean_c4 M_L_mean_wb_damp_seq_post_mean_c4];
M_L_mean_wb_seq_mean_c4 = [M_L_mean_wb_seq_pre_mean_c4 M_L_mean_wb_seq_post_mean_c4];

M_R_mean_wb_accel_seq_mean_c4 = [M_R_mean_wb_accel_seq_pre_mean_c4 M_R_mean_wb_accel_seq_post_mean_c4];
M_R_mean_wb_damp_seq_mean_c4 = [M_R_mean_wb_damp_seq_pre_mean_c4 M_R_mean_wb_damp_seq_post_mean_c4];
M_R_mean_wb_seq_mean_c4 = [M_R_mean_wb_seq_pre_mean_c4 M_R_mean_wb_seq_post_mean_c4];

%% ste
% wb kin
f_wb_seq_ste_c4 = [f_wb_seq_pre_ste_c4 f_wb_seq_post_ste_c4];

stroke_wb_L_seq_bins_ste_c4 = [stroke_wb_L_seq_bins_pre_ste_c4 stroke_wb_L_seq_bins_post_ste_c4];
stroke_wb_R_seq_bins_ste_c4 = [stroke_wb_R_seq_bins_pre_ste_c4 stroke_wb_R_seq_bins_post_ste_c4];

dev_wb_L_seq_bins_ste_c4 = [dev_wb_L_seq_bins_pre_ste_c4 dev_wb_L_seq_bins_post_ste_c4];
dev_wb_R_seq_bins_ste_c4 = [dev_wb_R_seq_bins_pre_ste_c4 dev_wb_R_seq_bins_post_ste_c4];

pitch_wb_L_seq_bins_ste_c4 = [pitch_wb_L_seq_bins_pre_ste_c4 pitch_wb_L_seq_bins_post_ste_c4];
pitch_wb_R_seq_bins_ste_c4 = [pitch_wb_R_seq_bins_pre_ste_c4 pitch_wb_R_seq_bins_post_ste_c4];

% body kin
roll_mean_wb_seq_ste_c4 = [roll_mean_wb_seq_pre_ste_c4 roll_mean_wb_seq_post_ste_c4];
roll_dot_mean_wb_seq_ste_c4 = [roll_dot_mean_wb_seq_pre_ste_c4 roll_dot_mean_wb_seq_post_ste_c4];
roll_dot_dot_mean_wb_seq_ste_c4 = [roll_dot_dot_mean_wb_seq_pre_ste_c4 roll_dot_dot_mean_wb_seq_post_ste_c4];

pitch_mean_wb_seq_ste_c4 = [pitch_mean_wb_seq_pre_ste_c4 pitch_mean_wb_seq_post_ste_c4];
pitch_dot_mean_wb_seq_ste_c4 = [pitch_dot_mean_wb_seq_pre_ste_c4 pitch_dot_mean_wb_seq_post_ste_c4];
pitch_dot_dot_mean_wb_seq_ste_c4 = [pitch_dot_dot_mean_wb_seq_pre_ste_c4 pitch_dot_dot_mean_wb_seq_post_ste_c4];

yaw_mean_wb_seq_ste_c4 = [yaw_mean_wb_seq_pre_ste_c4 yaw_mean_wb_seq_post_ste_c4];
yaw_dot_mean_wb_seq_ste_c4 = [yaw_dot_mean_wb_seq_pre_ste_c4 yaw_dot_mean_wb_seq_post_ste_c4];
yaw_dot_dot_mean_wb_seq_ste_c4 = [yaw_dot_dot_mean_wb_seq_pre_ste_c4 yaw_dot_dot_mean_wb_seq_post_ste_c4];

drot_L_mean_wb_seq_ste_c4 = [drot_L_mean_wb_seq_pre_ste_c4 drot_L_mean_wb_seq_post_ste_c4];
rot_dot_L_mean_wb_seq_ste_c4 = [rot_dot_L_mean_wb_seq_pre_ste_c4 rot_dot_L_mean_wb_seq_post_ste_c4];
rot_dot_dot_L_mean_wb_seq_ste_c4 = [rot_dot_dot_L_mean_wb_seq_pre_ste_c4 rot_dot_dot_L_mean_wb_seq_post_ste_c4];

drot_R_mean_wb_seq_ste_c4 = [drot_R_mean_wb_seq_pre_ste_c4 drot_R_mean_wb_seq_post_ste_c4];
rot_dot_R_mean_wb_seq_ste_c4 = [rot_dot_R_mean_wb_seq_pre_ste_c4 rot_dot_R_mean_wb_seq_post_ste_c4];
rot_dot_dot_R_mean_wb_seq_ste_c4 = [rot_dot_dot_R_mean_wb_seq_pre_ste_c4 rot_dot_dot_R_mean_wb_seq_post_ste_c4];

% torque
Mroll_mean_wb_accel_seq_ste_c4 = [Mroll_mean_wb_accel_seq_pre_ste_c4 Mroll_mean_wb_accel_seq_post_ste_c4];
Mroll_mean_wb_damp_seq_ste_c4 = [Mroll_mean_wb_damp_seq_pre_ste_c4 Mroll_mean_wb_damp_seq_post_ste_c4];
Mroll_mean_wb_seq_ste_c4 = [Mroll_mean_wb_seq_pre_ste_c4 Mroll_mean_wb_seq_post_ste_c4];

Mpitch_mean_wb_accel_seq_ste_c4 = [Mpitch_mean_wb_accel_seq_pre_ste_c4 Mpitch_mean_wb_accel_seq_post_ste_c4];
Mpitch_mean_wb_damp_seq_ste_c4 = [Mpitch_mean_wb_damp_seq_pre_ste_c4 Mpitch_mean_wb_damp_seq_post_ste_c4];
Mpitch_mean_wb_seq_ste_c4 = [Mpitch_mean_wb_seq_pre_ste_c4 Mpitch_mean_wb_seq_post_ste_c4];

Myaw_mean_wb_accel_seq_ste_c4 = [Myaw_mean_wb_accel_seq_pre_ste_c4 Myaw_mean_wb_accel_seq_post_ste_c4];
Myaw_mean_wb_damp_seq_ste_c4 = [Myaw_mean_wb_damp_seq_pre_ste_c4 Myaw_mean_wb_damp_seq_post_ste_c4];
Myaw_mean_wb_seq_ste_c4 = [Myaw_mean_wb_seq_pre_ste_c4 Myaw_mean_wb_seq_post_ste_c4];

M_L_mean_wb_accel_seq_ste_c4 = [M_L_mean_wb_accel_seq_pre_ste_c4 M_L_mean_wb_accel_seq_post_ste_c4];
M_L_mean_wb_damp_seq_ste_c4 = [M_L_mean_wb_damp_seq_pre_ste_c4 M_L_mean_wb_damp_seq_post_ste_c4];
M_L_mean_wb_seq_ste_c4 = [M_L_mean_wb_seq_pre_ste_c4 M_L_mean_wb_seq_post_ste_c4];

M_R_mean_wb_accel_seq_ste_c4 = [M_R_mean_wb_accel_seq_pre_ste_c4 M_R_mean_wb_accel_seq_post_ste_c4];
M_R_mean_wb_damp_seq_ste_c4 = [M_R_mean_wb_damp_seq_pre_ste_c4 M_R_mean_wb_damp_seq_post_ste_c4];
M_R_mean_wb_seq_ste_c4 = [M_R_mean_wb_seq_pre_ste_c4 M_R_mean_wb_seq_post_ste_c4];


%% mean ALL
% wb kin
f_wb_seq_mean_all_c4 = [f_wb_seq_pre_mean_all_c4;f_wb_seq_post_mean_all_c4];

stroke_wb_L_seq_bins_mean_all_c4 = [stroke_wb_L_seq_bins_pre_mean_all_c4;stroke_wb_L_seq_bins_post_mean_all_c4];
stroke_wb_R_seq_bins_mean_all_c4 = [stroke_wb_R_seq_bins_pre_mean_all_c4;stroke_wb_R_seq_bins_post_mean_all_c4];

dev_wb_L_seq_bins_mean_all_c4 = [dev_wb_L_seq_bins_pre_mean_all_c4;dev_wb_L_seq_bins_post_mean_all_c4];
dev_wb_R_seq_bins_mean_all_c4 = [dev_wb_R_seq_bins_pre_mean_all_c4;dev_wb_R_seq_bins_post_mean_all_c4];

pitch_wb_L_seq_bins_mean_all_c4 = [pitch_wb_L_seq_bins_pre_mean_all_c4;pitch_wb_L_seq_bins_post_mean_all_c4];
pitch_wb_R_seq_bins_mean_all_c4 = [pitch_wb_R_seq_bins_pre_mean_all_c4;pitch_wb_R_seq_bins_post_mean_all_c4];

% body kin
roll_mean_wb_seq_mean_all_c4 = [roll_mean_wb_seq_pre_mean_all_c4;roll_mean_wb_seq_post_mean_all_c4];
roll_dot_mean_wb_seq_mean_all_c4 = [roll_dot_mean_wb_seq_pre_mean_all_c4;roll_dot_mean_wb_seq_post_mean_all_c4];
roll_dot_dot_mean_wb_seq_mean_all_c4 = [roll_dot_dot_mean_wb_seq_pre_mean_all_c4;roll_dot_dot_mean_wb_seq_post_mean_all_c4];

pitch_mean_wb_seq_mean_all_c4 = [pitch_mean_wb_seq_pre_mean_all_c4;pitch_mean_wb_seq_post_mean_all_c4];
pitch_dot_mean_wb_seq_mean_all_c4 = [pitch_dot_mean_wb_seq_pre_mean_all_c4;pitch_dot_mean_wb_seq_post_mean_all_c4];
pitch_dot_dot_mean_wb_seq_mean_all_c4 = [pitch_dot_dot_mean_wb_seq_pre_mean_all_c4;pitch_dot_dot_mean_wb_seq_post_mean_all_c4];

yaw_mean_wb_seq_mean_all_c4 = [yaw_mean_wb_seq_pre_mean_all_c4;yaw_mean_wb_seq_post_mean_all_c4];
yaw_dot_mean_wb_seq_mean_all_c4 = [yaw_dot_mean_wb_seq_pre_mean_all_c4;yaw_dot_mean_wb_seq_post_mean_all_c4];
yaw_dot_dot_mean_wb_seq_mean_all_c4 = [yaw_dot_dot_mean_wb_seq_pre_mean_all_c4;yaw_dot_dot_mean_wb_seq_post_mean_all_c4];

drot_L_mean_wb_seq_mean_all_c4 = [drot_L_mean_wb_seq_pre_mean_all_c4;drot_L_mean_wb_seq_post_mean_all_c4];
rot_dot_L_mean_wb_seq_mean_all_c4 = [rot_dot_L_mean_wb_seq_pre_mean_all_c4;rot_dot_L_mean_wb_seq_post_mean_all_c4];
rot_dot_dot_L_mean_wb_seq_mean_all_c4 = [rot_dot_dot_L_mean_wb_seq_pre_mean_all_c4;rot_dot_dot_L_mean_wb_seq_post_mean_all_c4];

drot_R_mean_wb_seq_mean_all_c4 = [drot_R_mean_wb_seq_pre_mean_all_c4;drot_R_mean_wb_seq_post_mean_all_c4];
rot_dot_R_mean_wb_seq_mean_all_c4 = [rot_dot_R_mean_wb_seq_pre_mean_all_c4;rot_dot_R_mean_wb_seq_post_mean_all_c4];
rot_dot_dot_R_mean_wb_seq_mean_all_c4 = [rot_dot_dot_R_mean_wb_seq_pre_mean_all_c4;rot_dot_dot_R_mean_wb_seq_post_mean_all_c4];

% torque
Mroll_mean_wb_accel_seq_mean_all_c4 = [Mroll_mean_wb_accel_seq_pre_mean_all_c4;Mroll_mean_wb_accel_seq_post_mean_all_c4];
Mroll_mean_wb_damp_seq_mean_all_c4 = [Mroll_mean_wb_damp_seq_pre_mean_all_c4;Mroll_mean_wb_damp_seq_post_mean_all_c4];
Mroll_mean_wb_seq_mean_all_c4 = [Mroll_mean_wb_seq_pre_mean_all_c4;Mroll_mean_wb_seq_post_mean_all_c4];

Mpitch_mean_wb_accel_seq_mean_all_c4 = [Mpitch_mean_wb_accel_seq_pre_mean_all_c4;Mpitch_mean_wb_accel_seq_post_mean_all_c4];
Mpitch_mean_wb_damp_seq_mean_all_c4 = [Mpitch_mean_wb_damp_seq_pre_mean_all_c4;Mpitch_mean_wb_damp_seq_post_mean_all_c4];
Mpitch_mean_wb_seq_mean_all_c4 = [Mpitch_mean_wb_seq_pre_mean_all_c4;Mpitch_mean_wb_seq_post_mean_all_c4];

Myaw_mean_wb_accel_seq_mean_all_c4 = [Myaw_mean_wb_accel_seq_pre_mean_all_c4;Myaw_mean_wb_accel_seq_post_mean_all_c4];
Myaw_mean_wb_damp_seq_mean_all_c4 = [Myaw_mean_wb_damp_seq_pre_mean_all_c4;Myaw_mean_wb_damp_seq_post_mean_all_c4];
Myaw_mean_wb_seq_mean_all_c4 = [Myaw_mean_wb_seq_pre_mean_all_c4;Myaw_mean_wb_seq_post_mean_all_c4];

M_L_mean_wb_accel_seq_mean_all_c4 = [M_L_mean_wb_accel_seq_pre_mean_all_c4;M_L_mean_wb_accel_seq_post_mean_all_c4];
M_L_mean_wb_damp_seq_mean_all_c4 = [M_L_mean_wb_damp_seq_pre_mean_all_c4;M_L_mean_wb_damp_seq_post_mean_all_c4];
M_L_mean_wb_seq_mean_all_c4 = [M_L_mean_wb_seq_pre_mean_all_c4;M_L_mean_wb_seq_post_mean_all_c4];

M_R_mean_wb_accel_seq_mean_all_c4 = [M_R_mean_wb_accel_seq_pre_mean_all_c4;M_R_mean_wb_accel_seq_post_mean_all_c4];
M_R_mean_wb_damp_seq_mean_all_c4 = [M_R_mean_wb_damp_seq_pre_mean_all_c4;M_R_mean_wb_damp_seq_post_mean_all_c4];
M_R_mean_wb_seq_mean_all_c4 = [M_R_mean_wb_seq_pre_mean_all_c4;M_R_mean_wb_seq_post_mean_all_c4];

%% ste ALL
% wb kin
f_wb_seq_ste_all_c4 = [f_wb_seq_pre_ste_all_c4;f_wb_seq_post_ste_all_c4];

stroke_wb_L_seq_bins_ste_all_c4 = [stroke_wb_L_seq_bins_pre_ste_all_c4;stroke_wb_L_seq_bins_post_ste_all_c4];
stroke_wb_R_seq_bins_ste_all_c4 = [stroke_wb_R_seq_bins_pre_ste_all_c4;stroke_wb_R_seq_bins_post_ste_all_c4];

dev_wb_L_seq_bins_ste_all_c4 = [dev_wb_L_seq_bins_pre_ste_all_c4;dev_wb_L_seq_bins_post_ste_all_c4];
dev_wb_R_seq_bins_ste_all_c4 = [dev_wb_R_seq_bins_pre_ste_all_c4;dev_wb_R_seq_bins_post_ste_all_c4];

pitch_wb_L_seq_bins_ste_all_c4 = [pitch_wb_L_seq_bins_pre_ste_all_c4;pitch_wb_L_seq_bins_post_ste_all_c4];
pitch_wb_R_seq_bins_ste_all_c4 = [pitch_wb_R_seq_bins_pre_ste_all_c4;pitch_wb_R_seq_bins_post_ste_all_c4];

% body kin
roll_mean_wb_seq_ste_all_c4 = [roll_mean_wb_seq_pre_ste_all_c4;roll_mean_wb_seq_post_ste_all_c4];
roll_dot_mean_wb_seq_ste_all_c4 = [roll_dot_mean_wb_seq_pre_ste_all_c4;roll_dot_mean_wb_seq_post_ste_all_c4];
roll_dot_dot_mean_wb_seq_ste_all_c4 = [roll_dot_dot_mean_wb_seq_pre_ste_all_c4;roll_dot_dot_mean_wb_seq_post_ste_all_c4];

pitch_mean_wb_seq_ste_all_c4 = [pitch_mean_wb_seq_pre_ste_all_c4;pitch_mean_wb_seq_post_ste_all_c4];
pitch_dot_mean_wb_seq_ste_all_c4 = [pitch_dot_mean_wb_seq_pre_ste_all_c4;pitch_dot_mean_wb_seq_post_ste_all_c4];
pitch_dot_dot_mean_wb_seq_ste_all_c4 = [pitch_dot_dot_mean_wb_seq_pre_ste_all_c4;pitch_dot_dot_mean_wb_seq_post_ste_all_c4];

yaw_mean_wb_seq_ste_all_c4 = [yaw_mean_wb_seq_pre_ste_all_c4;yaw_mean_wb_seq_post_ste_all_c4];
yaw_dot_mean_wb_seq_ste_all_c4 = [yaw_dot_mean_wb_seq_pre_ste_all_c4;yaw_dot_mean_wb_seq_post_ste_all_c4];
yaw_dot_dot_mean_wb_seq_ste_all_c4 = [yaw_dot_dot_mean_wb_seq_pre_ste_all_c4;yaw_dot_dot_mean_wb_seq_post_ste_all_c4];

drot_L_mean_wb_seq_ste_all_c4 = [drot_L_mean_wb_seq_pre_ste_all_c4;drot_L_mean_wb_seq_post_ste_all_c4];
rot_dot_L_mean_wb_seq_ste_all_c4 = [rot_dot_L_mean_wb_seq_pre_ste_all_c4;rot_dot_L_mean_wb_seq_post_ste_all_c4];
rot_dot_dot_L_mean_wb_seq_ste_all_c4 = [rot_dot_dot_L_mean_wb_seq_pre_ste_all_c4;rot_dot_dot_L_mean_wb_seq_post_ste_all_c4];

drot_R_mean_wb_seq_ste_all_c4 = [drot_R_mean_wb_seq_pre_ste_all_c4;drot_R_mean_wb_seq_post_ste_all_c4];
rot_dot_R_mean_wb_seq_ste_all_c4 = [rot_dot_R_mean_wb_seq_pre_ste_all_c4;rot_dot_R_mean_wb_seq_post_ste_all_c4];
rot_dot_dot_R_mean_wb_seq_ste_all_c4 = [rot_dot_dot_R_mean_wb_seq_pre_ste_all_c4;rot_dot_dot_R_mean_wb_seq_post_ste_all_c4];

% torque
Mroll_mean_wb_accel_seq_ste_all_c4 = [Mroll_mean_wb_accel_seq_pre_ste_all_c4;Mroll_mean_wb_accel_seq_post_ste_all_c4];
Mroll_mean_wb_damp_seq_ste_all_c4 = [Mroll_mean_wb_damp_seq_pre_ste_all_c4;Mroll_mean_wb_damp_seq_post_ste_all_c4];
Mroll_mean_wb_seq_ste_all_c4 = [Mroll_mean_wb_seq_pre_ste_all_c4;Mroll_mean_wb_seq_post_ste_all_c4];

Mpitch_mean_wb_accel_seq_ste_all_c4 = [Mpitch_mean_wb_accel_seq_pre_ste_all_c4;Mpitch_mean_wb_accel_seq_post_ste_all_c4];
Mpitch_mean_wb_damp_seq_ste_all_c4 = [Mpitch_mean_wb_damp_seq_pre_ste_all_c4;Mpitch_mean_wb_damp_seq_post_ste_all_c4];
Mpitch_mean_wb_seq_ste_all_c4 = [Mpitch_mean_wb_seq_pre_ste_all_c4;Mpitch_mean_wb_seq_post_ste_all_c4];

Myaw_mean_wb_accel_seq_ste_all_c4 = [Myaw_mean_wb_accel_seq_pre_ste_all_c4;Myaw_mean_wb_accel_seq_post_ste_all_c4];
Myaw_mean_wb_damp_seq_ste_all_c4 = [Myaw_mean_wb_damp_seq_pre_ste_all_c4;Myaw_mean_wb_damp_seq_post_ste_all_c4];
Myaw_mean_wb_seq_ste_all_c4 = [Myaw_mean_wb_seq_pre_ste_all_c4;Myaw_mean_wb_seq_post_ste_all_c4];

M_L_mean_wb_accel_seq_ste_all_c4 = [M_L_mean_wb_accel_seq_pre_ste_all_c4;M_L_mean_wb_accel_seq_post_ste_all_c4];
M_L_mean_wb_damp_seq_ste_all_c4 = [M_L_mean_wb_damp_seq_pre_ste_all_c4;M_L_mean_wb_damp_seq_post_ste_all_c4];
M_L_mean_wb_seq_ste_all_c4 = [M_L_mean_wb_seq_pre_ste_all_c4;M_L_mean_wb_seq_post_ste_all_c4];

M_R_mean_wb_accel_seq_ste_all_c4 = [M_R_mean_wb_accel_seq_pre_ste_all_c4;M_R_mean_wb_accel_seq_post_ste_all_c4];
M_R_mean_wb_damp_seq_ste_all_c4 = [M_R_mean_wb_damp_seq_pre_ste_all_c4;M_R_mean_wb_damp_seq_post_ste_all_c4];
M_R_mean_wb_seq_ste_all_c4 = [M_R_mean_wb_seq_pre_ste_all_c4;M_R_mean_wb_seq_post_ste_all_c4];

%% all
% wb kin
f_wb_seq_all_c4 = [f_wb_seq_pre_all_c4 f_wb_seq_post_all_c4];

stroke_wb_L_seq_bins_all_c4 = [stroke_wb_L_seq_bins_pre_all_c4;stroke_wb_L_seq_bins_post_all_c4];
stroke_wb_R_seq_bins_all_c4 = [stroke_wb_R_seq_bins_pre_all_c4;stroke_wb_R_seq_bins_post_all_c4];

dev_wb_L_seq_bins_all_c4 = [dev_wb_L_seq_bins_pre_all_c4;dev_wb_L_seq_bins_post_all_c4];
dev_wb_R_seq_bins_all_c4 = [dev_wb_R_seq_bins_pre_all_c4;dev_wb_R_seq_bins_post_all_c4];

pitch_wb_L_seq_bins_all_c4 = [pitch_wb_L_seq_bins_pre_all_c4;pitch_wb_L_seq_bins_post_all_c4];
pitch_wb_R_seq_bins_all_c4 = [pitch_wb_R_seq_bins_pre_all_c4;pitch_wb_R_seq_bins_post_all_c4];

% body kin
roll_mean_wb_seq_all_c4 = [roll_mean_wb_seq_pre_all_c4 roll_mean_wb_seq_post_all_c4];
roll_dot_mean_wb_seq_all_c4 = [roll_dot_mean_wb_seq_pre_all_c4 roll_dot_mean_wb_seq_post_all_c4];
roll_dot_dot_mean_wb_seq_all_c4 = [roll_dot_dot_mean_wb_seq_pre_all_c4 roll_dot_dot_mean_wb_seq_post_all_c4];

pitch_mean_wb_seq_all_c4 = [pitch_mean_wb_seq_pre_all_c4 pitch_mean_wb_seq_post_all_c4];
pitch_dot_mean_wb_seq_all_c4 = [pitch_dot_mean_wb_seq_pre_all_c4 pitch_dot_mean_wb_seq_post_all_c4];
pitch_dot_dot_mean_wb_seq_all_c4 = [pitch_dot_dot_mean_wb_seq_pre_all_c4 pitch_dot_dot_mean_wb_seq_post_all_c4];

yaw_mean_wb_seq_all_c4 = [yaw_mean_wb_seq_pre_all_c4 yaw_mean_wb_seq_post_all_c4];
yaw_dot_mean_wb_seq_all_c4 = [yaw_dot_mean_wb_seq_pre_all_c4 yaw_dot_mean_wb_seq_post_all_c4];
yaw_dot_dot_mean_wb_seq_all_c4 = [yaw_dot_dot_mean_wb_seq_pre_all_c4 yaw_dot_dot_mean_wb_seq_post_all_c4];

drot_L_mean_wb_seq_all_c4 = [drot_L_mean_wb_seq_pre_all_c4 drot_L_mean_wb_seq_post_all_c4];
rot_dot_L_mean_wb_seq_all_c4 = [rot_dot_L_mean_wb_seq_pre_all_c4 rot_dot_L_mean_wb_seq_post_all_c4];
rot_dot_dot_L_mean_wb_seq_all_c4 = [rot_dot_dot_L_mean_wb_seq_pre_all_c4 rot_dot_dot_L_mean_wb_seq_post_all_c4];

drot_R_mean_wb_seq_all_c4 = [drot_R_mean_wb_seq_pre_all_c4 drot_R_mean_wb_seq_post_all_c4];
rot_dot_R_mean_wb_seq_all_c4 = [rot_dot_R_mean_wb_seq_pre_all_c4 rot_dot_R_mean_wb_seq_post_all_c4];
rot_dot_dot_R_mean_wb_seq_all_c4 = [rot_dot_dot_R_mean_wb_seq_pre_all_c4 rot_dot_dot_R_mean_wb_seq_post_all_c4];

% torque
Mroll_mean_wb_accel_seq_all_c4 = [Mroll_mean_wb_accel_seq_pre_all_c4 Mroll_mean_wb_accel_seq_post_all_c4];
Mroll_mean_wb_damp_seq_all_c4 = [Mroll_mean_wb_damp_seq_pre_all_c4 Mroll_mean_wb_damp_seq_post_all_c4];
Mroll_mean_wb_seq_all_c4 = [Mroll_mean_wb_seq_pre_all_c4 Mroll_mean_wb_seq_post_all_c4];

Mpitch_mean_wb_accel_seq_all_c4 = [Mpitch_mean_wb_accel_seq_pre_all_c4 Mpitch_mean_wb_accel_seq_post_all_c4];
Mpitch_mean_wb_damp_seq_all_c4 = [Mpitch_mean_wb_damp_seq_pre_all_c4 Mpitch_mean_wb_damp_seq_post_all_c4];
Mpitch_mean_wb_seq_all_c4 = [Mpitch_mean_wb_seq_pre_all_c4 Mpitch_mean_wb_seq_post_all_c4];

Myaw_mean_wb_accel_seq_all_c4 = [Myaw_mean_wb_accel_seq_pre_all_c4 Myaw_mean_wb_accel_seq_post_all_c4];
Myaw_mean_wb_damp_seq_all_c4 = [Myaw_mean_wb_damp_seq_pre_all_c4 Myaw_mean_wb_damp_seq_post_all_c4];
Myaw_mean_wb_seq_all_c4 = [Myaw_mean_wb_seq_pre_all_c4 Myaw_mean_wb_seq_post_all_c4];

M_L_mean_wb_accel_seq_all_c4 = [M_L_mean_wb_accel_seq_pre_all_c4 M_L_mean_wb_accel_seq_post_all_c4];
M_L_mean_wb_damp_seq_all_c4 = [M_L_mean_wb_damp_seq_pre_all_c4 M_L_mean_wb_damp_seq_post_all_c4];
M_L_mean_wb_seq_all_c4 = [M_L_mean_wb_seq_pre_all_c4 M_L_mean_wb_seq_post_all_c4];

M_R_mean_wb_accel_seq_all_c4 = [M_R_mean_wb_accel_seq_pre_all_c4 M_R_mean_wb_accel_seq_post_all_c4];
M_R_mean_wb_damp_seq_all_c4 = [M_R_mean_wb_damp_seq_pre_all_c4 M_R_mean_wb_damp_seq_post_all_c4];
M_R_mean_wb_seq_all_c4 = [M_R_mean_wb_seq_pre_all_c4 M_R_mean_wb_seq_post_all_c4];
